// GENERATED by tools/gen_applicability_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import FF "../src/FirmForms";
import Pg "../src/Programme";
import Json "../src/Json";
import Py "../src/Py";
import Array "mo:core/Array";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let staff = Principal.fromBlob("\04");
let client = Principal.fromBlob("\05");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func has(xs : [Text], x : Text) : Bool { for (y in xs.vals()) { if (y == x) return true }; false };
func proposal(who : Principal) : Json.J { must("proposal", Pg.proposal(s, ff, who, false, 1)) };
func rowOf(v : Json.J, pid : Text) : Json.J { for (r in Py.list(v, "rows").vals()) { if (Py.textOr(r, "procedure", "") == pid) return r }; #null_ };
func programmeRow(pid : Text) : Json.J { rowOf(must("programme", Pg.view(s, ff, manager, false, 1)), pid) };
func natOf(v : Json.J, k : Text) : Nat { Py.natOr(v, k, 0) };
func texts(v : Json.J, k : Text) : [Text] { Array.map<Json.J, Text>(Py.list(v, k), Py.scalar) };

let LINKED : [Text] = ["P-FSL-033", "P-REV-001", "P-REV-002", "P-REV-003", "P-REV-004", "P-REV-005", "P-REV-006", "P-REV-007", "P-REV-008", "P-REV-009", "P-REV-010", "P-REV-011", "P-REV-012", "P-REV-013", "P-REV-014", "P-PUR-001", "P-PUR-002", "P-PUR-003", "P-PUR-004", "P-PUR-005", "P-PUR-006", "P-PUR-007", "P-PUR-008", "P-PUR-009", "P-PUR-010", "P-PUR-011", "P-PAY-001", "P-PAY-002", "P-PAY-003", "P-PAY-004", "P-PAY-005", "P-PAY-006", "P-PAY-007", "P-INV-001", "P-INV-002", "P-INV-003", "P-INV-004", "P-INV-005", "P-INV-006", "P-INV-007", "P-INV-008", "P-INV-009", "P-PPE-001", "P-PPE-002", "P-PPE-003", "P-PPE-004", "P-PPE-005", "P-PPE-006", "P-PPE-007", "P-PPE-008", "P-PPE-009", "P-PPE-010", "P-TRE-001", "P-TRE-002", "P-TRE-003", "P-TRE-004", "P-TRE-005", "P-TRE-006", "P-TRE-007", "P-TRE-008", "P-TRE-009", "P-TRE-010", "P-EQY-001", "P-EQY-002", "P-EQY-003", "P-EQY-004", "P-EQY-005", "P-TAX-001", "P-TAX-002", "P-TAX-003", "P-TAX-004", "P-TAX-005", "P-PUR-012"];
let NA : [Text] = ["P-FSL-033", "P-PUR-006", "P-PUR-007", "P-PUR-008", "P-PUR-009", "P-PUR-010", "P-PAY-005", "P-PAY-006", "P-PPE-007", "P-PPE-008", "P-PPE-009", "P-TRE-007", "P-TRE-008", "P-EQY-002", "P-EQY-004", "P-TAX-003", "P-TAX-005", "P-PUR-012"];
let CONTRADICTED : [Text] = ["P-PUR-007", "P-PUR-009", "P-TAX-003"];
let NEWLY : [Text] = ["LS-OEXP", "LS-PROVC"];

// the engagement and its team; no trial balance yet
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Nile Trading SAE\",\"framework\":\"IFRS\",\"audit_standard\":\"ISA\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (senior, "senior"), (staff, "staff"), (client, "client")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));
let p0 = proposal(senior);
check("without a trial balance nothing is proposed", field(p0, ["trial_balance"]) == #bool(false) and Py.list(p0, "rows").size() == 0);
refused("accepting without a trial balance is refused", Pg.acceptProposal(s, ff, senior, false, 3, 1, j("{\"performed_at\":\"2026-02-01T09:00\"}")), "no trial balance");
refused("the client does not see the programme's proposal", Pg.proposal(s, ff, client, false, 1), "the audit programme is the auditor's");

// the trial balance: the proposal is the oracle's, procedure by procedure
ignore must("import the trial balance", E.importTrialBalance(s, staff, false, 3, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str("Account Code,Account Name,Debit,Credit,Prior Year Debit,Prior Year Credit\u{a}1000,Land and buildings,\"5,000,000.00\",0.00,\"4,800,000.00\",0.00\u{a}1002,Accumulated depreciation - buildings,0.00,\"1,200,000.00\",0.00,\"900,000.00\"\u{a}1350,Finished goods,\"820,000.00\",0.00,\"760,000.00\",0.00\u{a}1400,Trade receivables,\"1,450,000.00\",0.00,\"1,300,000.00\",0.00\u{a}1401,Loss allowance,0.00,\"65,000.00\",0.00,\"50,000.00\"\u{a}1500,Bank current account,\"310,500.25\",0.00,\"402,000.00\",0.00\u{a}1650,Accrued income,\"40,000.00\",0.00,0.00,0.00\u{a}2000,Share capital,0.00,\"2,000,000.00\",0.00,\"2,000,000.00\"\u{a}2200,Retained earnings,0.00,\"1,005,500.25\",0.00,\"912,000.00\"\u{a}3000,Term loan,0.00,\"1,500,000.00\",0.00,\"1,700,000.00\"\u{a}4100,Trade payables,0.00,\"780,000.00\",0.00,\"690,000.00\"\u{a}4800,VAT payable,0.00,\"120,000.00\",0.00,\"110,000.00\"\u{a}5000,Sales,0.00,\"10,450,000.00\",0.00,\"9,800,000.00\"\u{a}6000,Cost of sales,\"6,600,000.00\",0.00,\"6,150,000.00\",0.00\u{a}6300,Salaries,\"2,100,000.00\",0.00,\"1,950,000.00\",0.00\u{a}6700,Depreciation,\"300,000.00\",0.00,\"300,000.00\",0.00\u{a}6500,Interest expense,\"150,000.00\",0.00,\"160,000.00\",0.00\u{a}6600,Income tax expense,\"350,000.00\",0.00,\"340,000.00\",0.00\u{a}7100,Suspense - unmapped by design,0.00,0.00,0.00,0.00\u{a}Total,,\"17,120,500.25\",\"17,120,500.25\",\"16,162,000.00\",\"16,162,000.00\"\u{a}"))])));
let p1 = proposal(senior);
check("one row per procedure the model ties to leadsheets", Py.list(p1, "rows").size() == LINKED.size());
check("the proposed count is the oracle's", natOf(p1, "proposed") == NA.size() and natOf(p1, "confirmed") == 0 and natOf(p1, "contradicted") == 0);
var proposedRight = 0;
for (pid in NA.vals()) {
  let r = rowOf(p1, pid);
  let reason = Py.textOr(r, "reason", "");
  var namesEach = true;
  for (l in texts(r, "leadsheets").vals()) { if (not Text.contains(reason, #text l)) namesEach := false };
  if (Py.textOr(r, "state", "") == "proposed" and Py.textOr(r, "proposed", "") == "not_applicable" and texts(r, "populated").size() == 0 and namesEach) proposedRight += 1;
};
check("every procedure the oracle proposes is proposed not applicable, its reason naming each unpopulated leadsheet", proposedRight == NA.size());
var applicableRight = 0;
for (r in Py.list(p1, "rows").vals()) {
  let pid = Py.textOr(r, "procedure", "");
  if (not has(NA, pid) and Py.textOr(r, "state", "") == "applicable" and texts(r, "populated").size() > 0) applicableRight += 1;
};
check("every other linked procedure is applicable with a populated leadsheet", applicableRight + NA.size() == LINKED.size());
check("the populated leadsheets are the oracle's", texts(p1, "populated") == ["LS-PPE", "LS-INV", "LS-REC", "LS-CTRA", "LS-CASH", "LS-SCAP", "LS-RE", "LS-BORNC", "LS-AP", "LS-VAT", "LS-REV", "LS-COS", "LS-STAFF", "LS-DEPR", "LS-FINC", "LS-TAXEXP"]);

// accepting the proposal records the conclusions, once
let accepted = must("accept the proposal", Pg.acceptProposal(s, ff, senior, false, 4, 1, j("{\"performed_at\":\"2026-02-01T09:00\"}")));
check("one conclusion per proposed procedure", Py.items(accepted).size() == NA.size());
var conclusionsRight = 0;
for (c in Py.items(accepted).vals()) {
  let f = field(c, ["fields"]);
  if (Py.textOr(c, "kind", "") == Pg.CONCLUSION and Py.textOr(f, "conclusion", "") == "not_applicable" and Text.startsWith(Py.textOr(f, "rationale", ""), #text (Pg.PROPOSED)) and has(NA, Py.textOr(f, "procedure", ""))) conclusionsRight += 1;
};
check("each conclusion is not applicable, its rationale the computed reason marked as proposed", conclusionsRight == NA.size());
let p2 = proposal(manager);
check("every proposal is confirmed", natOf(p2, "confirmed") == NA.size() and natOf(p2, "proposed") == 0);
check("the programme reads the conclusion", field(programmeRow(NA[0]), ["status"]) == #str("not_applicable"));
refused("accepting again records nothing", Pg.acceptProposal(s, ff, senior, false, 5, 1, j("{\"performed_at\":\"2026-02-01T10:00\"}")), "nothing remains proposed");

// the reviewer confirms four-eyes, or overrides
var reviewedId = 0;
for (c in Py.items(accepted).vals()) { if (Py.textOr(field(c, ["fields"]), "procedure", "") == "P-PUR-006") reviewedId := Py.natOr(c, "id", 0) };
refused("four eyes: the one who accepted does not review", Pg.review(s, senior, false, 6, 1, reviewedId, "2026-02-01T11:00"), "not permitted");
ignore must("the manager reviews a confirmed proposal", Pg.review(s, manager, false, 6, 1, reviewedId, "2026-02-01T11:00"));
check("the conclusion is reviewed", field(programmeRow("P-PUR-006"), ["conclusion", "reviewed"]) == #bool(true));
ignore must("the manager overrides one: performed after all", Pg.conclude(s, manager, false, 7, 1, j("{\"procedure\":\"P-FSL-033\",\"conclusion\":\"performed_no_exception\",\"rationale\":\"Performed on the opening balances the leadsheet does not show\",\"performed_at\":\"2026-02-02T09:00\"}")));
let p3 = proposal(manager);
check("the override shows as such", Py.textOr(rowOf(p3, "P-FSL-033"), "state", "") == "overridden" and natOf(p3, "overridden") == 1 and natOf(p3, "confirmed") + 1 == NA.size());
ignore must("the senior judges an applicable procedure not applicable, with a reason", Pg.conclude(s, senior, false, 8, 1, j("{\"procedure\":\"P-REV-001\",\"conclusion\":\"not_applicable\",\"rationale\":\"The balance is clearly trivial this period; see the materiality paper\",\"performed_at\":\"2026-02-02T10:00\"}")));
let p4 = proposal(manager);
check("the auditor's own judgement is a judgement, not a contradiction", Py.textOr(rowOf(p4, "P-REV-001"), "state", "") == "judgement" and natOf(p4, "judgement") == 1 and natOf(p4, "contradicted") == 0);

// a later trial balance populates a leadsheet: the proposals it contradicts are open again
ignore must("import the trial balance with the provision", E.importTrialBalance(s, staff, false, 9, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str("Account Code,Account Name,Debit,Credit,Prior Year Debit,Prior Year Credit\u{a}1000,Land and buildings,\"5,000,000.00\",0.00,\"4,800,000.00\",0.00\u{a}1002,Accumulated depreciation - buildings,0.00,\"1,200,000.00\",0.00,\"900,000.00\"\u{a}1350,Finished goods,\"820,000.00\",0.00,\"760,000.00\",0.00\u{a}1400,Trade receivables,\"1,450,000.00\",0.00,\"1,300,000.00\",0.00\u{a}1401,Loss allowance,0.00,\"65,000.00\",0.00,\"50,000.00\"\u{a}1500,Bank current account,\"310,500.25\",0.00,\"402,000.00\",0.00\u{a}1650,Accrued income,\"40,000.00\",0.00,0.00,0.00\u{a}2000,Share capital,0.00,\"2,000,000.00\",0.00,\"2,000,000.00\"\u{a}2200,Retained earnings,0.00,\"1,005,500.25\",0.00,\"912,000.00\"\u{a}3000,Term loan,0.00,\"1,500,000.00\",0.00,\"1,700,000.00\"\u{a}4100,Trade payables,0.00,\"780,000.00\",0.00,\"690,000.00\"\u{a}4800,VAT payable,0.00,\"120,000.00\",0.00,\"110,000.00\"\u{a}5000,Sales,0.00,\"10,450,000.00\",0.00,\"9,800,000.00\"\u{a}6000,Cost of sales,\"6,600,000.00\",0.00,\"6,150,000.00\",0.00\u{a}6300,Salaries,\"2,100,000.00\",0.00,\"1,950,000.00\",0.00\u{a}6700,Depreciation,\"300,000.00\",0.00,\"300,000.00\",0.00\u{a}6500,Interest expense,\"150,000.00\",0.00,\"160,000.00\",0.00\u{a}6600,Income tax expense,\"350,000.00\",0.00,\"340,000.00\",0.00\u{a}7100,Suspense - unmapped by design,0.00,0.00,0.00,0.00\u{a}Total,,\"17,120,500.25\",\"17,120,500.25\",\"16,162,000.00\",\"16,162,000.00\"\u{a}4410,Warranty provision,\"0.00\",\"50,000.00\",0.00,0.00\u{a}6910,Warranty expense,\"50,000.00\",\"0.00\",0.00,0.00\u{a}"))])));
let p5 = proposal(manager);
check("the newly populated leadsheets are the oracle's", (func() : Bool { for (l in NEWLY.vals()) { if (not has(texts(p5, "populated"), l)) return false }; true })());
check("the contradicted procedures are the oracle's", Pg.contradicted(s, ff, 1) == CONTRADICTED and natOf(p5, "contradicted") == CONTRADICTED.size());
check("a contradicted procedure says so on the proposal and on the programme", Py.textOr(rowOf(p5, CONTRADICTED[0]), "state", "") == "contradicted" and field(programmeRow(CONTRADICTED[0]), ["contradicted"]) == #bool(true));
check("a contradicted procedure is open again", has(Pg.open(s, ff, 1), CONTRADICTED[0]));
check("the judgement stands: it was the auditor's, not the trial balance's", Py.textOr(rowOf(p5, "P-REV-001"), "state", "") == "judgement");
check("the override reads against the trial balance as it stands", Py.textOr(rowOf(p5, "P-FSL-033"), "state", "") == "applicable");
ignore must("the senior concludes the contradicted procedure anew", Pg.conclude(s, senior, false, 11, 1, j("{\"procedure\":\"P-PUR-007\",\"conclusion\":\"performed_no_exception\",\"rationale\":\"Performed on the provision the second trial balance brought in\",\"performed_at\":\"2026-02-03T09:00\"}")));
let p6 = proposal(manager);
check("concluded anew, it is applicable and nothing is contradicted", Py.textOr(rowOf(p6, CONTRADICTED[0]), "state", "") == "applicable" and natOf(p6, "contradicted") + 1 == CONTRADICTED.size());

Debug.print("count: applicability checks = " # Nat.toText(checks));
Debug.print("count: linked procedures = " # Nat.toText(LINKED.size()));
Debug.print("count: proposed not applicable = " # Nat.toText(NA.size()));
Debug.print("count: contradicted by the second trial balance = " # Nat.toText(CONTRADICTED.size()));
Debug.print("count: refusals = " # Nat.toText(refusals));
if (failed > 0) Runtime.trap("APPLICABILITY RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("APPLICABILITY GREEN");
