// GENERATED by tools/gen_analytics_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import F "../src/Forms";
import FF "../src/FirmForms";
import PF "../src/ProductForms";
import Json "../src/Json";
import Py "../src/Py";
import List "mo:core/List";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let staff = Principal.fromBlob("\04");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
var instances = 0;
var figures = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func view(who : Principal, form : Text) : Json.J {
  switch (F.view(s, ff, who, false, 1, form)) { case (#ok(v)) v; case (#err(m)) { checks += 1; failed += 1; Debug.print("FAIL view " # form # ": " # m); #null_ } };
};
func rowWhere(rows : [Json.J], key : Text, value : Text) : Json.J { for (r in rows.vals()) { if (Py.textOr(r, key, "") == value) return r }; #null_ };
func hasField(def : Json.J, id : Text) : Bool {
  for (sec in Py.list(def, "sections").vals()) { for (f in Py.list(sec, "fields").vals()) { if (Py.textOr(f, "id", "") == id) return true } };
  false
};
func blockingNames(v : Json.J) : [Text] { let o = List.empty<Text>(); for (b in Py.items(field(v, ["blocking"])).vals()) List.add(o, Py.textOr(b, "form", "")); List.toArray(o) };
func has(xs : [Text], x : Text) : Bool { for (y in xs.vals()) { if (y == x) return true }; false };
func compute(form : Text, inp : Text) : E.R {
  E.compute(s, senior, false, 40, 1, #obj([("kind", #str("analytical_review")), ("procedure_id", #str(form)), ("input", j(inp))]))
};

// the engagement, its team, the trial balance and the materiality the papers read
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Nile Trading SAE\",\"framework\":\"EAS\",\"audit_standard\":\"EAS\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (senior, "senior"), (staff, "staff")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));
check("before a trial balance the paper has no instance", Py.items(field(must("statuses", F.statuses(s, ff, manager, false, 1)), [])).size() == 38);
refused("no leadsheet is populated yet", F.save(s, ff, staff, false, 3, 1, "F40-BALANCE-ANALYTICS@LS-REV", j("{\"values\":{}}")), "not populated");
ignore must("import the trial balance", E.importTrialBalance(s, staff, false, 3, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str("Account Code,Account Name,Debit,Credit,Prior Year Debit,Prior Year Credit\u{a}1000,Land and buildings,\"5,000,000.00\",0.00,\"4,800,000.00\",0.00\u{a}1002,Accumulated depreciation - buildings,0.00,\"1,200,000.00\",0.00,\"900,000.00\"\u{a}1350,Finished goods,\"820,000.00\",0.00,\"760,000.00\",0.00\u{a}1400,Trade receivables,\"1,450,000.00\",0.00,\"1,300,000.00\",0.00\u{a}1401,Loss allowance,0.00,\"65,000.00\",0.00,\"50,000.00\"\u{a}1500,Bank current account,\"310,500.25\",0.00,\"402,000.00\",0.00\u{a}1650,Accrued income,\"40,000.00\",0.00,0.00,0.00\u{a}2000,Share capital,0.00,\"2,000,000.00\",0.00,\"2,000,000.00\"\u{a}2200,Retained earnings,0.00,\"1,005,500.25\",0.00,\"912,000.00\"\u{a}3000,Term loan,0.00,\"1,500,000.00\",0.00,\"1,700,000.00\"\u{a}4100,Trade payables,0.00,\"780,000.00\",0.00,\"690,000.00\"\u{a}4800,VAT payable,0.00,\"120,000.00\",0.00,\"110,000.00\"\u{a}5000,Sales,0.00,\"10,450,000.00\",0.00,\"9,800,000.00\"\u{a}6000,Cost of sales,\"6,600,000.00\",0.00,\"6,150,000.00\",0.00\u{a}6300,Salaries,\"2,100,000.00\",0.00,\"1,950,000.00\",0.00\u{a}6700,Depreciation,\"300,000.00\",0.00,\"300,000.00\",0.00\u{a}6500,Interest expense,\"150,000.00\",0.00,\"160,000.00\",0.00\u{a}6600,Income tax expense,\"350,000.00\",0.00,\"340,000.00\",0.00\u{a}7100,Suspense - unmapped by design,0.00,0.00,0.00,0.00\u{a}Total,,\"17,120,500.25\",\"17,120,500.25\",\"16,162,000.00\",\"16,162,000.00\"\u{a}"))])));
ignore must("compute materiality", E.compute(s, senior, false, 4, 1, #obj([("kind", #str("materiality")), ("procedure_id", #str("P-FSL-006")), ("input", j("{\"benchmark\":\"revenue\",\"benchmark_amount\":\"10450000.00\",\"percentage\":\"1\",\"pm_factor\":\"0.75\",\"trivial_factor\":\"0.05\"}"))])));

// the definition and its instances
let cat = Py.items(F.catalogue(ff));
check("the paper is catalogued once, per leadsheet", field(rowWhere(cat, "id", "F40-BALANCE-ANALYTICS"), ["per"]) == #str("leadsheet") and cat.size() == 39);
let statuses = Py.items(must("statuses", F.statuses(s, ff, manager, false, 1)));
check("one instance per populated leadsheet, beside the other thirty-eight", statuses.size() == 38 + 16);
check("an instance names its definition, its leadsheet and its own title", (func() : Bool {
  let r = rowWhere(statuses, "form", "F40-BALANCE-ANALYTICS@LS-REV");
  field(r, ["base"]) == #str("F40-BALANCE-ANALYTICS") and field(r, ["leadsheet"]) == #str("LS-REV") and Text.contains(Py.textOr(field(r, ["title"]), "en", ""), #text "LS-REV") and Text.contains(Py.textOr(field(r, ["title"]), "en", ""), #text "Revenue")
})());
check("the instance's definition reads the leadsheet it is for", (func() : Bool {
  let v = view(staff, "F40-BALANCE-ANALYTICS@LS-REV");
  var ok = field(v, ["form", "id"]) == #str("F40-BALANCE-ANALYTICS@LS-REV");
  for (sec in Py.list(field(v, ["form"]), "sections").vals()) { for (f in Py.list(sec, "fields").vals()) { if (Py.textOr(f, "id", "") == "recorded") ok := ok and Py.textOr(f, "autofill", "") == "tb.leadsheet.LS-REV" } };
  ok and field(v, ["live", "recorded"]) == #str("-10450000.00") and field(v, ["live", "performance_materiality"]) == #str("78375.00")
})());
check("the bare definition renders with its tokens unreplaced and takes no values", PF.versionText("F40-BALANCE-ANALYTICS", 1) != null and hasField(j(switch (PF.latest("F40-BALANCE-ANALYTICS")) { case (?t) t; case null "{}" }), "recorded"));
refused("the paper is filled per leadsheet, never under its bare id", F.save(s, ff, staff, false, 5, 1, "F40-BALANCE-ANALYTICS", j("{\"values\":{}}")), "filled per leadsheet");
refused("a leadsheet the trial balance does not populate has no paper", F.save(s, ff, staff, false, 5, 1, "F40-BALANCE-ANALYTICS@LS-NCI", j("{\"values\":{}}")), "not populated");
refused("a leadsheet the model does not know has no paper", F.save(s, ff, staff, false, 5, 1, "F40-BALANCE-ANALYTICS@LS-NOPE", j("{\"values\":{}}")), "not populated");

// every populated leadsheet: the paper's figures are the computation's (the standards' Python is the oracle)
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-PPE", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-PPE", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"-2.56\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-PPE", compute("F40-BALANCE-ANALYTICS@LS-PPE", "{\"lines\":[{\"name\":\"LS-PPE\",\"recorded\":\"3800000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"3900000.00\",\"growth_pct\":\"-2.56\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-PPE: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-PPE"), ["live", "expected"]) == #str("3800160.00"));
check("LS-PPE: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-PPE"), ["live", "threshold"]) == #str("39187.50"));
check("LS-PPE: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-PPE"), ["live", "difference"]) == #str("-160.00"));
check("LS-PPE: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-PPE"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-PPE", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-PPE", "prepare", "2026-02-01T09:00"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-INV", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-INV", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"7.89\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-INV", compute("F40-BALANCE-ANALYTICS@LS-INV", "{\"lines\":[{\"name\":\"LS-INV\",\"recorded\":\"820000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"760000.00\",\"growth_pct\":\"7.89\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-INV: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-INV"), ["live", "expected"]) == #str("819964.00"));
check("LS-INV: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-INV"), ["live", "threshold"]) == #str("39187.50"));
check("LS-INV: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-INV"), ["live", "difference"]) == #str("36.00"));
check("LS-INV: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-INV"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-INV", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-INV", "prepare", "2026-02-01T09:05"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-REC", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-REC", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"10.80\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-REC", compute("F40-BALANCE-ANALYTICS@LS-REC", "{\"lines\":[{\"name\":\"LS-REC\",\"recorded\":\"1385000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"1250000.00\",\"growth_pct\":\"10.80\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-REC: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-REC"), ["live", "expected"]) == #str("1385000.00"));
check("LS-REC: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-REC"), ["live", "threshold"]) == #str("39187.50"));
check("LS-REC: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-REC"), ["live", "difference"]) == #str("0.00"));
check("LS-REC: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-REC"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-REC", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-REC", "prepare", "2026-02-01T09:10"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-CTRA", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-CTRA", j("{\"values\":{\"model\":\"proof_in_total\",\"components\":[{\"name\":\"Balance per the ledger\",\"amount\":\"40000.00\"}],\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-CTRA", compute("F40-BALANCE-ANALYTICS@LS-CTRA", "{\"lines\":[{\"name\":\"LS-CTRA\",\"recorded\":\"40000.00\",\"model\":{\"kind\":\"proof_in_total\",\"components\":[\"40000.00\"]}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-CTRA: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-CTRA"), ["live", "expected"]) == #str("40000.00"));
check("LS-CTRA: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-CTRA"), ["live", "threshold"]) == #str("39187.50"));
check("LS-CTRA: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-CTRA"), ["live", "difference"]) == #str("0.00"));
check("LS-CTRA: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-CTRA"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-CTRA", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-CTRA", "prepare", "2026-02-01T09:15"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-CASH", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-CASH", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"-22.76\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-CASH", compute("F40-BALANCE-ANALYTICS@LS-CASH", "{\"lines\":[{\"name\":\"LS-CASH\",\"recorded\":\"310500.25\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"402000.00\",\"growth_pct\":\"-22.76\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-CASH: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-CASH"), ["live", "expected"]) == #str("310504.80"));
check("LS-CASH: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-CASH"), ["live", "threshold"]) == #str("39187.50"));
check("LS-CASH: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-CASH"), ["live", "difference"]) == #str("-4.55"));
check("LS-CASH: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-CASH"), ["live", "investigate"]) == #bool(false));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-SCAP", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-SCAP", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"0.00\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-SCAP", compute("F40-BALANCE-ANALYTICS@LS-SCAP", "{\"lines\":[{\"name\":\"LS-SCAP\",\"recorded\":\"-2000000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"-2000000.00\",\"growth_pct\":\"0.00\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-SCAP: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-SCAP"), ["live", "expected"]) == #str("-2000000.00"));
check("LS-SCAP: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-SCAP"), ["live", "threshold"]) == #str("39187.50"));
check("LS-SCAP: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-SCAP"), ["live", "difference"]) == #str("0.00"));
check("LS-SCAP: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-SCAP"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-SCAP", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-SCAP", "prepare", "2026-02-01T09:25"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-RE", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-RE", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"10.25\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-RE", compute("F40-BALANCE-ANALYTICS@LS-RE", "{\"lines\":[{\"name\":\"LS-RE\",\"recorded\":\"-1005500.25\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"-912000.00\",\"growth_pct\":\"10.25\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-RE: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-RE"), ["live", "expected"]) == #str("-1005480.00"));
check("LS-RE: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-RE"), ["live", "threshold"]) == #str("39187.50"));
check("LS-RE: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-RE"), ["live", "difference"]) == #str("-20.25"));
check("LS-RE: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-RE"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-RE", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-RE", "prepare", "2026-02-01T09:30"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-BORNC", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-BORNC", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"-11.76\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-BORNC", compute("F40-BALANCE-ANALYTICS@LS-BORNC", "{\"lines\":[{\"name\":\"LS-BORNC\",\"recorded\":\"-1500000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"-1700000.00\",\"growth_pct\":\"-11.76\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-BORNC: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-BORNC"), ["live", "expected"]) == #str("-1500080.00"));
check("LS-BORNC: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-BORNC"), ["live", "threshold"]) == #str("39187.50"));
check("LS-BORNC: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-BORNC"), ["live", "difference"]) == #str("80.00"));
check("LS-BORNC: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-BORNC"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-BORNC", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-BORNC", "prepare", "2026-02-01T09:35"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-AP", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-AP", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"13.04\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-AP", compute("F40-BALANCE-ANALYTICS@LS-AP", "{\"lines\":[{\"name\":\"LS-AP\",\"recorded\":\"-780000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"-690000.00\",\"growth_pct\":\"13.04\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-AP: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-AP"), ["live", "expected"]) == #str("-779976.00"));
check("LS-AP: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-AP"), ["live", "threshold"]) == #str("39187.50"));
check("LS-AP: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-AP"), ["live", "difference"]) == #str("-24.00"));
check("LS-AP: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-AP"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-AP", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-AP", "prepare", "2026-02-01T09:40"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-VAT", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-VAT", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"9.09\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-VAT", compute("F40-BALANCE-ANALYTICS@LS-VAT", "{\"lines\":[{\"name\":\"LS-VAT\",\"recorded\":\"-120000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"-110000.00\",\"growth_pct\":\"9.09\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-VAT: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-VAT"), ["live", "expected"]) == #str("-119999.00"));
check("LS-VAT: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-VAT"), ["live", "threshold"]) == #str("39187.50"));
check("LS-VAT: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-VAT"), ["live", "difference"]) == #str("-1.00"));
check("LS-VAT: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-VAT"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-VAT", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-VAT", "prepare", "2026-02-01T09:45"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-REV", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-REV", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"0\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-REV", compute("F40-BALANCE-ANALYTICS@LS-REV", "{\"lines\":[{\"name\":\"LS-REV\",\"recorded\":\"-10450000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"-9800000.00\",\"growth_pct\":\"0\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-REV: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-REV"), ["live", "expected"]) == #str("-9800000.00"));
check("LS-REV: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-REV"), ["live", "threshold"]) == #str("39187.50"));
check("LS-REV: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-REV"), ["live", "difference"]) == #str("-650000.00"));
check("LS-REV: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-REV"), ["live", "investigate"]) == #bool(true));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-COS", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-COS", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"7.32\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-COS", compute("F40-BALANCE-ANALYTICS@LS-COS", "{\"lines\":[{\"name\":\"LS-COS\",\"recorded\":\"6600000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"6150000.00\",\"growth_pct\":\"7.32\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-COS: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-COS"), ["live", "expected"]) == #str("6600180.00"));
check("LS-COS: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-COS"), ["live", "threshold"]) == #str("39187.50"));
check("LS-COS: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-COS"), ["live", "difference"]) == #str("-180.00"));
check("LS-COS: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-COS"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-COS", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-COS", "prepare", "2026-02-01T09:55"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-STAFF", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-STAFF", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"7.69\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-STAFF", compute("F40-BALANCE-ANALYTICS@LS-STAFF", "{\"lines\":[{\"name\":\"LS-STAFF\",\"recorded\":\"2100000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"1950000.00\",\"growth_pct\":\"7.69\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-STAFF: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-STAFF"), ["live", "expected"]) == #str("2099955.00"));
check("LS-STAFF: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-STAFF"), ["live", "threshold"]) == #str("39187.50"));
check("LS-STAFF: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-STAFF"), ["live", "difference"]) == #str("45.00"));
check("LS-STAFF: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-STAFF"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-STAFF", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-STAFF", "prepare", "2026-02-01T10:00"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-DEPR", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-DEPR", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"0.00\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-DEPR", compute("F40-BALANCE-ANALYTICS@LS-DEPR", "{\"lines\":[{\"name\":\"LS-DEPR\",\"recorded\":\"300000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"300000.00\",\"growth_pct\":\"0.00\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-DEPR: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-DEPR"), ["live", "expected"]) == #str("300000.00"));
check("LS-DEPR: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-DEPR"), ["live", "threshold"]) == #str("39187.50"));
check("LS-DEPR: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-DEPR"), ["live", "difference"]) == #str("0.00"));
check("LS-DEPR: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-DEPR"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-DEPR", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-DEPR", "prepare", "2026-02-01T10:05"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-FINC", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-FINC", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"-6.25\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-FINC", compute("F40-BALANCE-ANALYTICS@LS-FINC", "{\"lines\":[{\"name\":\"LS-FINC\",\"recorded\":\"150000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"160000.00\",\"growth_pct\":\"-6.25\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-FINC: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-FINC"), ["live", "expected"]) == #str("150000.00"));
check("LS-FINC: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-FINC"), ["live", "threshold"]) == #str("39187.50"));
check("LS-FINC: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-FINC"), ["live", "difference"]) == #str("0.00"));
check("LS-FINC: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-FINC"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-FINC", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-FINC", "prepare", "2026-02-01T10:10"));
instances += 1;
ignore must("fill F40-BALANCE-ANALYTICS@LS-TAXEXP", F.save(s, ff, staff, false, 20, 1, "F40-BALANCE-ANALYTICS@LS-TAXEXP", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"2.94\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\"}}")));
ignore must("compute F40-BALANCE-ANALYTICS@LS-TAXEXP", compute("F40-BALANCE-ANALYTICS@LS-TAXEXP", "{\"lines\":[{\"name\":\"LS-TAXEXP\",\"recorded\":\"350000.00\",\"model\":{\"kind\":\"prior_growth\",\"prior\":\"340000.00\",\"growth_pct\":\"2.94\"}}],\"performance_materiality\":\"78375.00\",\"threshold_pct\":\"50\"}"));
figures += 4;
check("LS-TAXEXP: the expectation is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-TAXEXP"), ["live", "expected"]) == #str("349996.00"));
check("LS-TAXEXP: the threshold is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-TAXEXP"), ["live", "threshold"]) == #str("39187.50"));
check("LS-TAXEXP: the difference is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-TAXEXP"), ["live", "difference"]) == #str("4.00"));
check("LS-TAXEXP: whether to investigate is the oracle's", field(view(staff, "F40-BALANCE-ANALYTICS@LS-TAXEXP"), ["live", "investigate"]) == #bool(false));
ignore must("prepare F40-BALANCE-ANALYTICS@LS-TAXEXP", F.sign(s, ff, staff, 21, 1, "F40-BALANCE-ANALYTICS@LS-TAXEXP", "prepare", "2026-02-01T10:15"));

// the far expectation: an uninvestigated difference beyond the acceptable amount blocks preparing
refused("a difference beyond the acceptable amount with no investigation is not prepared", F.sign(s, ff, staff, 60, 1, "F40-BALANCE-ANALYTICS@LS-REV", "prepare", "2026-02-02T09:00"), "investigation is required");
ignore must("record the investigation", F.save(s, ff, staff, false, 61, 1, "F40-BALANCE-ANALYTICS@LS-REV", j("{\"values\":{\"model\":\"prior_growth\",\"growth_pct\":\"0\",\"suitability\":\"Recorded for the graph battery.\",\"data_reliability\":\"Recorded for the graph battery.\",\"threshold_pct\":\"50\",\"precision\":\"Recorded for the graph battery.\",\"conclusion\":\"consistent\",\"rationale\":\"Recorded for the graph battery.\",\"investigation\":\"Management attributes the movement to the new export line; shipping documents and price lists corroborate it.\"}}")));
ignore must("with the investigation the paper is prepared", F.sign(s, ff, staff, 61, 1, "F40-BALANCE-ANALYTICS@LS-REV", "prepare", "2026-02-02T09:05"));
check("the far paper is prepared and its figures frozen", (func() : Bool { let v = view(manager, "F40-BALANCE-ANALYTICS@LS-REV"); field(v, ["status"]) == #str("prepared") and field(v, ["frozen", "difference"]) == #str("-650000.00") and field(v, ["frozen", "investigate"]) == #bool(true) })());
check("another instance still reads its own paper, not the far one", field(view(staff, "F40-BALANCE-ANALYTICS@LS-PPE"), ["live", "difference"]) == #str("-160.00"));

// the gate names the unsigned instance until it is prepared
let ready1 = must("readiness", F.readiness(s, ff, manager, false, 1));
check("the completion gate names the unsigned paper of a populated leadsheet", has(blockingNames(ready1), "F40-BALANCE-ANALYTICS@LS-CASH") and not has(blockingNames(ready1), "F40-BALANCE-ANALYTICS"));
check("and not the prepared ones", not has(blockingNames(ready1), "F40-BALANCE-ANALYTICS@LS-REV"));
ignore must("prepare the last paper", F.sign(s, ff, staff, 70, 1, "F40-BALANCE-ANALYTICS@LS-CASH", "prepare", "2026-02-02T10:00"));
check("once prepared it is no longer named", not has(blockingNames(must("readiness again", F.readiness(s, ff, manager, false, 1))), "F40-BALANCE-ANALYTICS@LS-CASH"));

// the file map: one node for the paper, aggregating its instances
let mapv = must("file map", F.fileMap(s, ff, manager, false, 1));
let node = rowWhere(Py.items(field(mapv, ["nodes"])), "id", "F40-BALANCE-ANALYTICS");
check("the map has one node for the paper with every instance under it", Py.items(field(node, ["instances"])).size() == 16 and field(node, ["status"]) == #str("prepared") and field(node, ["applicable"]) == #bool(true));
check("the completion view lists every instance as an upstream", (func() : Bool {
  var n = 0;
  for (u in Py.items(field(view(manager, "F14-COMPLETION"), ["upstream"])).vals()) { if (Text.startsWith(Py.textOr(u, "form", ""), #text "F40-BALANCE-ANALYTICS@")) n += 1 };
  n == 16
})());

// a re-imported trial balance moves the recorded balance: the prepared paper drifts, naming the trial balance
ignore must("import a scaled trial balance", E.importTrialBalance(s, staff, false, 80, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str("Account Code,Account Name,Debit,Credit,Prior Year Debit,Prior Year Credit\u{a}1000,Land and buildings,\"5,500,000.00\",0.00,\"5,280,000.00\",0.00\u{a}1002,Accumulated depreciation - buildings,0.00,\"1,320,000.00\",0.00,\"990,000.00\"\u{a}1350,Finished goods,\"902,000.00\",0.00,\"836,000.00\",0.00\u{a}1400,Trade receivables,\"1,595,000.00\",0.00,\"1,430,000.00\",0.00\u{a}1401,Loss allowance,0.00,\"71,500.00\",0.00,\"55,000.00\"\u{a}1500,Bank current account,\"341,550.28\",0.00,\"442,200.00\",0.00\u{a}1650,Accrued income,\"44,000.00\",0.00,0.00,0.00\u{a}2000,Share capital,0.00,\"2,200,000.00\",0.00,\"2,200,000.00\"\u{a}2200,Retained earnings,0.00,\"1,106,050.28\",0.00,\"1,003,200.00\"\u{a}3000,Term loan,0.00,\"1,650,000.00\",0.00,\"1,870,000.00\"\u{a}4100,Trade payables,0.00,\"858,000.00\",0.00,\"759,000.00\"\u{a}4800,VAT payable,0.00,\"132,000.00\",0.00,\"121,000.00\"\u{a}5000,Sales,0.00,\"11,495,000.00\",0.00,\"10,780,000.00\"\u{a}6000,Cost of sales,\"7,260,000.00\",0.00,\"6,765,000.00\",0.00\u{a}6300,Salaries,\"2,310,000.00\",0.00,\"2,145,000.00\",0.00\u{a}6700,Depreciation,\"330,000.00\",0.00,\"330,000.00\",0.00\u{a}6500,Interest expense,\"165,000.00\",0.00,\"176,000.00\",0.00\u{a}6600,Income tax expense,\"385,000.00\",0.00,\"374,000.00\",0.00\u{a}7100,Suspense - unmapped by design,0.00,0.00,0.00,0.00\u{a}Total,,\"18,832,550.28\",\"18,832,550.28\",\"17,778,200.00\",\"17,778,200.00\"\u{a}"))])));
let drifted = view(manager, "F40-BALANCE-ANALYTICS@LS-REV");
check("the paper drifts on its recorded balance", (func() : Bool { for (x in Py.items(field(drifted, ["stale"])).vals()) { if (x == #str("recorded")) return true }; false })());
check("the drift names the trial balance", (func() : Bool { for (d in Py.items(field(drifted, ["drift"])).vals()) { if (field(d, ["field"]) == #str("recorded") and field(d, ["source", "node"]) == #str("tb")) return true }; false })());

Debug.print("count: balance analytics checks = " # Nat.toText(checks));
Debug.print("count: papers instantiated per populated leadsheet = " # Nat.toText(instances));
Debug.print("count: figures against the oracle = " # Nat.toText(figures));
Debug.print("count: refusals = " # Nat.toText(refusals));
if (failed > 0) Runtime.trap("ANALYTICS RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("ANALYTICS GREEN");
