// GENERATED by tools/gen_biological_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import A "../src/Adjustments";
import E "../src/Engine";
import F "../src/Forms";
import FF "../src/FirmForms";
import Pg "../src/Programme";
import Json "../src/Json";
import Py "../src/Py";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let staff = Principal.fromBlob("\04");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func nodeOf(m : Json.J, id : Text) : Json.J { for (n in Py.list(m, "nodes").vals()) { if (Py.textOr(n, "id", "") == id) return n }; #null_ };
func statusRow(v : Json.J, id : Text) : Json.J { for (r in Py.items(v).vals()) { if (Py.textOr(r, "form", "") == id) return r }; #null_ };
func live(eng : Nat, k : Text) : Json.J { switch (F.view(s, ff, manager, false, eng, "F50-BIOLOGICAL-COUNT")) { case (#ok(v)) field(v, ["live", k]); case (#err(m)) { checks += 1; failed += 1; Debug.print("FAIL view F50: " # m); #null_ } } };
func open(client : Text, fixture : Text) : Nat {
  let created = must("open " # client, E.createEngagement(s, partner, true, 1, j("{\"client\":\"" # client # "\",\"framework\":\"IFRS\",\"audit_standard\":\"ISA\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
  let eng = Py.natOr(created, "id", 0);
  for ((p, r) in [(manager, "manager"), (senior, "senior"), (staff, "staff")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, eng, p, r));
  ignore must("import the trial balance of " # client, E.importTrialBalance(s, staff, false, 3, eng, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str(fixture))])));
  eng
};

// a trading company: the form is catalogued but does not apply, and stands in nobody's way
let e1 = open("Nile Trading SAE", "Account Code,Account Name,Debit,Credit,Prior Year Debit,Prior Year Credit\u{a}1000,Land and buildings,\"5,000,000.00\",0.00,\"4,800,000.00\",0.00\u{a}1002,Accumulated depreciation - buildings,0.00,\"1,200,000.00\",0.00,\"900,000.00\"\u{a}1350,Finished goods,\"820,000.00\",0.00,\"760,000.00\",0.00\u{a}1400,Trade receivables,\"1,450,000.00\",0.00,\"1,300,000.00\",0.00\u{a}1401,Loss allowance,0.00,\"65,000.00\",0.00,\"50,000.00\"\u{a}1500,Bank current account,\"310,500.25\",0.00,\"402,000.00\",0.00\u{a}1650,Accrued income,\"40,000.00\",0.00,0.00,0.00\u{a}2000,Share capital,0.00,\"2,000,000.00\",0.00,\"2,000,000.00\"\u{a}2200,Retained earnings,0.00,\"1,005,500.25\",0.00,\"912,000.00\"\u{a}3000,Term loan,0.00,\"1,500,000.00\",0.00,\"1,700,000.00\"\u{a}4100,Trade payables,0.00,\"780,000.00\",0.00,\"690,000.00\"\u{a}4800,VAT payable,0.00,\"120,000.00\",0.00,\"110,000.00\"\u{a}5000,Sales,0.00,\"10,450,000.00\",0.00,\"9,800,000.00\"\u{a}6000,Cost of sales,\"6,600,000.00\",0.00,\"6,150,000.00\",0.00\u{a}6300,Salaries,\"2,100,000.00\",0.00,\"1,950,000.00\",0.00\u{a}6700,Depreciation,\"300,000.00\",0.00,\"300,000.00\",0.00\u{a}6500,Interest expense,\"150,000.00\",0.00,\"160,000.00\",0.00\u{a}6600,Income tax expense,\"350,000.00\",0.00,\"340,000.00\",0.00\u{a}7100,Suspense - unmapped by design,0.00,0.00,0.00,0.00\u{a}Total,,\"17,120,500.25\",\"17,120,500.25\",\"16,162,000.00\",\"16,162,000.00\"\u{a}");
check("the form is catalogued at number 50, serving the count procedures", (func() : Bool { for (r in Py.items(F.catalogue(ff)).vals()) { if (Py.textOr(r, "id", "") == "F50-BIOLOGICAL-COUNT") return field(r, ["number"]) == #num("50") }; false })());
let map1 = must("file map", F.fileMap(s, ff, manager, false, e1));
check("without biological assets on the trial balance the form is inapplicable", field(nodeOf(map1, "F50-BIOLOGICAL-COUNT"), ["applicable"]) == #bool(false));
check("the inventory count itself still applies", field(nodeOf(map1, "F23-INVENTORY-COUNT"), ["applicable"]) == #bool(true));
check("the count procedures are not proposed inapplicable: inventories are populated", (func() : Bool {
  for (r in Py.list(must("proposal", Pg.proposal(s, ff, manager, false, e1)), "rows").vals()) { if (Py.textOr(r, "procedure", "") == "P-INV-002") return Py.textOr(r, "state", "") == "applicable" };
  false
})());
check("no per-balance analytics instance for the empty leadsheet", statusRow(must("statuses 1", F.statuses(s, ff, manager, false, e1)), "F40-BALANCE-ANALYTICS@LS-BIO") == #null_);

// a farm: the leadsheet is populated, the form applies, and its schedule agrees with the leadsheet
let e2 = open("Delta Farms SAE", "Account Code,Account Name,Debit,Credit,Prior Year Debit,Prior Year Credit\u{a}1000,Land and buildings,\"5,000,000.00\",0.00,\"4,800,000.00\",0.00\u{a}1002,Accumulated depreciation - buildings,0.00,\"1,200,000.00\",0.00,\"900,000.00\"\u{a}1350,Finished goods,\"820,000.00\",0.00,\"760,000.00\",0.00\u{a}1400,Trade receivables,\"1,450,000.00\",0.00,\"1,300,000.00\",0.00\u{a}1401,Loss allowance,0.00,\"65,000.00\",0.00,\"50,000.00\"\u{a}1500,Bank current account,\"310,500.25\",0.00,\"402,000.00\",0.00\u{a}1650,Accrued income,\"40,000.00\",0.00,0.00,0.00\u{a}2000,Share capital,0.00,\"2,000,000.00\",0.00,\"2,000,000.00\"\u{a}2200,Retained earnings,0.00,\"1,005,500.25\",0.00,\"912,000.00\"\u{a}3000,Term loan,0.00,\"1,500,000.00\",0.00,\"1,700,000.00\"\u{a}4100,Trade payables,0.00,\"780,000.00\",0.00,\"690,000.00\"\u{a}4800,VAT payable,0.00,\"120,000.00\",0.00,\"110,000.00\"\u{a}5000,Sales,0.00,\"10,450,000.00\",0.00,\"9,800,000.00\"\u{a}6000,Cost of sales,\"6,600,000.00\",0.00,\"6,150,000.00\",0.00\u{a}6300,Salaries,\"2,100,000.00\",0.00,\"1,950,000.00\",0.00\u{a}6700,Depreciation,\"300,000.00\",0.00,\"300,000.00\",0.00\u{a}6500,Interest expense,\"150,000.00\",0.00,\"160,000.00\",0.00\u{a}6600,Income tax expense,\"350,000.00\",0.00,\"340,000.00\",0.00\u{a}7100,Suspense - unmapped by design,0.00,0.00,0.00,0.00\u{a}Total,,\"17,120,500.25\",\"17,120,500.25\",\"16,162,000.00\",\"16,162,000.00\"\u{a}1980,Dairy herd at fair value less costs to sell,\"600,000.00\",\"0.00\",\"500,000.00\",\"0.00\"\u{a}1985,Standing crops at fair value less costs to sell,\"150,000.00\",\"0.00\",\"120,000.00\",\"0.00\"\u{a}2010,Share premium,\"0.00\",\"750,000.00\",\"0.00\",\"620,000.00\"\u{a}");
let map2 = must("file map 2", F.fileMap(s, ff, manager, false, e2));
check("with a herd and crops on the trial balance the form applies", field(nodeOf(map2, "F50-BIOLOGICAL-COUNT"), ["applicable"]) == #bool(true));
check("the per-balance analytics paper gains an instance for the leadsheet", statusRow(must("statuses 2", F.statuses(s, ff, manager, false, e2)), "F40-BALANCE-ANALYTICS@LS-BIO") != #null_);
check("the populated leadsheets are the oracle's", (func() : Bool { let pop = A.populatedLeadsheets(s, e2); let want : [Text] = ["LS-PPE", "LS-INV", "LS-REC", "LS-CTRA", "LS-CASH", "LS-SCAP", "LS-RE", "LS-BORNC", "LS-AP", "LS-VAT", "LS-REV", "LS-COS", "LS-STAFF", "LS-DEPR", "LS-FINC", "LS-TAXEXP", "LS-BIO"]; if (pop.size() != want.size()) return false; for (l in want.vals()) { var found = false; for (x in pop.vals()) { if (x == l) found := true }; if (not found) return false }; true })());
ignore must("fill the count with its schedule", F.save(s, ff, staff, false, 4, e2, "F50-BIOLOGICAL-COUNT", j("{\"values\":{\"categories\":[{\"category\":\"Recorded for the graph battery.\",\"location\":\"Recorded for the graph battery.\",\"date\":\"2026-02-01\",\"method\":\"physical_count\",\"recorded\":\"Recorded for the graph battery.\",\"counted\":\"Recorded for the graph battery.\"}],\"instructions\":\"yes\",\"procedures_observed\":\"yes\",\"cutoff_recorded\":\"yes\",\"basis\":\"fair_value\",\"basis_note\":\"Active market prices for dairy cattle at the Damanhour auction and for standing cotton per the exchange; costs to sell per the broker's tariff.\",\"count_date\":\"2026-02-01\",\"rollforward\":\"Recorded for the graph battery.\",\"conclusion\":\"Recorded for the graph battery.\",\"sch_bio\":[{\"component\":\"livestock\",\"opening\":\"500000.00\",\"additions\":\"80000.00\",\"disposals\":\"10000.00\",\"transfers\":\"0.00\",\"revaluation\":\"30000.00\",\"other\":\"0.00\",\"closing\":\"600000.00\"},{\"component\":\"crops\",\"opening\":\"120000.00\",\"additions\":\"20000.00\",\"disposals\":\"0.00\",\"transfers\":\"0.00\",\"revaluation\":\"10000.00\",\"other\":\"0.00\",\"closing\":\"150000.00\"},{\"component\":\"bearer_plants\",\"opening\":\"0.00\",\"additions\":\"0.00\",\"disposals\":\"0.00\",\"transfers\":\"0.00\",\"revaluation\":\"0.00\",\"other\":\"0.00\",\"closing\":\"0.00\"}]}}")));
let paper = must("roll the biological assets forward", E.compute(s, senior, false, 5, e2, #obj([("kind", #str("rollforward")), ("procedure_id", #str("F50-BIOLOGICAL-COUNT")), ("input", #obj([("schedules", j("[{\"id\":\"SCH-BIO\",\"leadsheet_id\":\"LS-BIO\",\"sign\":\"1\",\"leadsheet_balance\":\"750000.00\",\"prior_balance\":\"620000.00\",\"components\":[{\"id\":\"livestock\",\"name\":\"Livestock\",\"contra\":0,\"opening\":\"500000.00\",\"additions\":\"80000.00\",\"disposals\":\"10000.00\",\"transfers\":\"0.00\",\"revaluation\":\"30000.00\",\"other\":\"0.00\",\"closing\":\"600000.00\"},{\"id\":\"crops\",\"name\":\"Crops and produce before harvest\",\"contra\":0,\"opening\":\"120000.00\",\"additions\":\"20000.00\",\"disposals\":\"0.00\",\"transfers\":\"0.00\",\"revaluation\":\"10000.00\",\"other\":\"0.00\",\"closing\":\"150000.00\"},{\"id\":\"bearer_plants\",\"name\":\"Bearer plants and orchards\",\"contra\":0,\"opening\":\"0.00\",\"additions\":\"0.00\",\"disposals\":\"0.00\",\"transfers\":\"0.00\",\"revaluation\":\"0.00\",\"other\":\"0.00\",\"closing\":\"0.00\"}]}]"))]))])));
check("the schedule closes on the leadsheet: the oracle's difference", field(paper, ["output", "schedules", "SCH-BIO", "difference"]) == #str("0.00") and field(paper, ["output", "schedules", "SCH-BIO", "agrees"]) == #bool(true));
check("the schedule opens on the prior period", field(paper, ["output", "schedules", "SCH-BIO", "opening_difference"]) == #str("0.00"));
check("the count reads its schedule live", live(e2, "sch_bio_difference") == #str("0.00") and live(e2, "sch_bio_agrees") == #bool(true));
let short = must("a schedule short of the leadsheet", E.compute(s, senior, false, 6, e2, #obj([("kind", #str("rollforward")), ("procedure_id", #str("F50-BIOLOGICAL-COUNT")), ("input", #obj([("schedules", j("[{\"id\":\"SCH-BIO\",\"leadsheet_id\":\"LS-BIO\",\"sign\":\"1\",\"leadsheet_balance\":\"752500.00\",\"prior_balance\":\"620000.00\",\"components\":[{\"id\":\"livestock\",\"name\":\"Livestock\",\"contra\":0,\"opening\":\"500000.00\",\"additions\":\"80000.00\",\"disposals\":\"10000.00\",\"transfers\":\"0.00\",\"revaluation\":\"30000.00\",\"other\":\"0.00\",\"closing\":\"600000.00\"},{\"id\":\"crops\",\"name\":\"Crops and produce before harvest\",\"contra\":0,\"opening\":\"120000.00\",\"additions\":\"20000.00\",\"disposals\":\"0.00\",\"transfers\":\"0.00\",\"revaluation\":\"10000.00\",\"other\":\"0.00\",\"closing\":\"150000.00\"},{\"id\":\"bearer_plants\",\"name\":\"Bearer plants and orchards\",\"contra\":0,\"opening\":\"0.00\",\"additions\":\"0.00\",\"disposals\":\"0.00\",\"transfers\":\"0.00\",\"revaluation\":\"0.00\",\"other\":\"0.00\",\"closing\":\"0.00\"}]}]"))]))])));
check("a schedule short of the leadsheet shows the oracle's difference and does not agree", field(short, ["output", "schedules", "SCH-BIO", "difference"]) == #str("-2500.00") and field(short, ["output", "schedules", "SCH-BIO", "agrees"]) == #bool(false));
ignore must("rolled forward again on the leadsheet", E.compute(s, senior, false, 7, e2, #obj([("kind", #str("rollforward")), ("procedure_id", #str("F50-BIOLOGICAL-COUNT")), ("input", #obj([("schedules", j("[{\"id\":\"SCH-BIO\",\"leadsheet_id\":\"LS-BIO\",\"sign\":\"1\",\"leadsheet_balance\":\"750000.00\",\"prior_balance\":\"620000.00\",\"components\":[{\"id\":\"livestock\",\"name\":\"Livestock\",\"contra\":0,\"opening\":\"500000.00\",\"additions\":\"80000.00\",\"disposals\":\"10000.00\",\"transfers\":\"0.00\",\"revaluation\":\"30000.00\",\"other\":\"0.00\",\"closing\":\"600000.00\"},{\"id\":\"crops\",\"name\":\"Crops and produce before harvest\",\"contra\":0,\"opening\":\"120000.00\",\"additions\":\"20000.00\",\"disposals\":\"0.00\",\"transfers\":\"0.00\",\"revaluation\":\"10000.00\",\"other\":\"0.00\",\"closing\":\"150000.00\"},{\"id\":\"bearer_plants\",\"name\":\"Bearer plants and orchards\",\"contra\":0,\"opening\":\"0.00\",\"additions\":\"0.00\",\"disposals\":\"0.00\",\"transfers\":\"0.00\",\"revaluation\":\"0.00\",\"other\":\"0.00\",\"closing\":\"0.00\"}]}]"))]))])));
ignore must("the count is prepared", F.sign(s, ff, staff, 8, e2, "F50-BIOLOGICAL-COUNT", "prepare", "2026-01-20T10:00"));
check("prepared, the schedule's agreement is frozen with the paper", (func() : Bool { switch (F.view(s, ff, manager, false, e2, "F50-BIOLOGICAL-COUNT")) { case (#ok(v)) field(v, ["frozen", "sch_bio_agrees"]) == #bool(true); case (#err(_)) false } })());

Debug.print("count: biological checks = " # Nat.toText(checks));
Debug.print("count: schedule components = " # Nat.toText(3));
Debug.print("count: leadsheets populated on the farm = " # Nat.toText(17));
if (failed > 0) Runtime.trap("BIOLOGICAL RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("BIOLOGICAL GREEN");
