// GENERATED by tools/gen_governance_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import F "../src/Forms";
import FF "../src/FirmForms";
import Gv "../src/Governance";
import Json "../src/Json";
import Py "../src/Py";
import Array "mo:core/Array";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let client = Principal.fromBlob("\05");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func idOf(v : Json.J) : Nat { Py.natOr(v, "id", 0) };
func live(k : Text) : Json.J { switch (F.view(s, ff, manager, false, 1, "F14-COMPLETION")) { case (#ok(v)) field(v, ["live", k]); case (#err(m)) { checks += 1; failed += 1; Debug.print("FAIL view F14: " # m); #null_ } } };
func liveIs(expect : [(Text, Nat)]) : Bool { var ok = true; for ((k, n) in expect.vals()) { if (live(k) != #num(Nat.toText(n))) { Debug.print("  " # k # " live = " # Json.toText(live(k)) # ", expected " # Nat.toText(n)); ok := false } }; ok };
func gov() : Json.J { must("governance view", Gv.view(s, manager, false, 1)) };

// the engagement and its team
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Nile Trading SAE\",\"framework\":\"IFRS\",\"audit_standard\":\"ISA\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (senior, "senior"), (client, "client")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));
check("the completion form is at version 2 and reads the minutes, the meetings and the matters carried", (func() : Bool {
  switch (F.view(s, ff, manager, false, 1, "F14-COMPLETION")) { case (#ok(v)) field(v, ["form", "version"]) == #num("2"); case (#err(_)) false }
})());
check("with nothing recorded the counts are zero", liveIs([("minutes_reviewed", 0), ("meetings_noted", 0), ("minutes_unresolved", 0), ("meetings_unresolved", 0), ("carried_forward", 0)]));

// what the contract refuses
refused("a minutes review informs a procedure of the model", E.addRecord(s, senior, false, 3, 1, j("{\"kind\":\"RK-MINUTES-REVIEW\",\"fields\":{\"meeting\":\"Audit committee\",\"held_on\":\"2026-02-18\",\"extract\":\"The committee noted the planning letter.\",\"matter\":\"None noted\",\"significance\":\"none\",\"procedure\":\"P-XXX-999\",\"reviewed_by\":\"senior\",\"reviewed_at\":\"2026-02-20T09:30\"}}")), "not a procedure of the model");
refused("the matter is stated", E.addRecord(s, senior, false, 3, 1, j("{\"kind\":\"RK-MINUTES-REVIEW\",\"fields\":{\"meeting\":\"Audit committee\",\"held_on\":\"2026-02-18\",\"extract\":\"The committee noted the planning letter.\",\"matter\":\" \",\"significance\":\"none\",\"procedure\":\"P-FSL-008\",\"reviewed_by\":\"senior\",\"reviewed_at\":\"2026-02-20T09:30\"}}")), "matter must not be empty");
refused("significance is none or significant", E.addRecord(s, senior, false, 3, 1, j("{\"kind\":\"RK-MINUTES-REVIEW\",\"fields\":{\"meeting\":\"Audit committee\",\"held_on\":\"2026-02-18\",\"extract\":\"The committee noted the planning letter.\",\"matter\":\"None noted\",\"significance\":\"maybe\",\"procedure\":\"P-FSL-008\",\"reviewed_by\":\"senior\",\"reviewed_at\":\"2026-02-20T09:30\"}}")), "significance must be one of");
refused("a matter addressed says how", E.addRecord(s, manager, false, 3, 1, j("{\"kind\":\"RK-CARRY-FORWARD\",\"fields\":{\"matter\":\"The new term loan covenants\",\"action\":\"Confirm the covenants at the interim visit.\",\"raised_by\":\"manager\",\"raised_at\":\"2026-03-25T11:00\",\"source\":\"record:1\",\"state\":\"addressed\"}}")), "a matter addressed says how");
refused("carried_from names an engagement", E.addRecord(s, manager, false, 3, 1, j("{\"kind\":\"RK-CARRY-FORWARD\",\"fields\":{\"matter\":\"The new term loan covenants\",\"action\":\"Confirm the covenants at the interim visit.\",\"raised_by\":\"manager\",\"raised_at\":\"2026-03-25T11:00\",\"source\":\"record:1\",\"state\":\"open\",\"carried_from\":\"last year\"}}")), "carried_from names the engagement");
refused("the client sees none of it", Gv.view(s, client, false, 1), "not permitted");

// the records, and the completion form reading them live
var minutesIds : [Nat] = [];
for (m in ["{\"kind\":\"RK-MINUTES-REVIEW\",\"fields\":{\"meeting\":\"Board of directors\",\"held_on\":\"2025-11-20\",\"extract\":\"The board approved a term loan of EGP 40m for the new spinning frame.\",\"matter\":\"New borrowing after the year end: disclosure and the going-concern forecast\",\"significance\":\"significant\",\"procedure\":\"P-FSL-008\",\"reviewed_by\":\"senior\",\"reviewed_at\":\"2026-01-12T10:00\"}}", "{\"kind\":\"RK-MINUTES-REVIEW\",\"fields\":{\"meeting\":\"Audit committee\",\"held_on\":\"2026-02-18\",\"extract\":\"The committee noted the planning letter.\",\"matter\":\"None noted\",\"significance\":\"none\",\"procedure\":\"P-FSL-008\",\"reviewed_by\":\"senior\",\"reviewed_at\":\"2026-02-20T09:30\"}}", "{\"kind\":\"RK-MINUTES-REVIEW\",\"fields\":{\"meeting\":\"Remuneration committee\",\"held_on\":\"2026-01-15\",\"extract\":\"A bonus scheme tied to reported revenue was approved for the sales directors.\",\"matter\":\"Incentive to overstate revenue: fraud risk factor\",\"significance\":\"significant\",\"resolution\":\"Added to the fraud risk assessment; revenue cut-off extended.\",\"procedure\":\"P-FSL-008\",\"reviewed_by\":\"senior\",\"reviewed_at\":\"2026-01-20T11:00\"}}"].vals()) { minutesIds := Array.concat(minutesIds, [idOf(must("minutes review", E.addRecord(s, senior, false, 4, 1, j(m))))]) };
var meetingIds : [Nat] = [];
for (m in ["{\"kind\":\"RK-MEETING-NOTE\",\"fields\":{\"with_whom\":\"Chief financial officer\",\"party\":\"management\",\"held_on\":\"2026-01-22T14:00\",\"discussed\":\"December shipments invoiced before the bill of lading date.\",\"agreed\":\"Management reverses the two invoices.\",\"significance\":\"significant\",\"recorded_by\":\"senior\",\"recorded_at\":\"2026-01-22T17:00\"}}", "{\"kind\":\"RK-MEETING-NOTE\",\"fields\":{\"with_whom\":\"Audit committee chair\",\"party\":\"tcwg\",\"held_on\":\"2026-03-24T15:00\",\"discussed\":\"The uncorrected misstatements.\",\"agreed\":\"The findings letter is accepted.\",\"significance\":\"none\",\"recorded_by\":\"manager\",\"recorded_at\":\"2026-03-24T18:00\"}}"].vals()) { meetingIds := Array.concat(meetingIds, [idOf(must("meeting note", E.addRecord(s, senior, false, 5, 1, j(m))))]) };
var carryIds : [Nat] = [];
for (m in ["{\"kind\":\"RK-CARRY-FORWARD\",\"fields\":{\"matter\":\"The new term loan covenants\",\"action\":\"Confirm the covenants at the interim visit.\",\"raised_by\":\"manager\",\"raised_at\":\"2026-03-25T11:00\",\"source\":\"record:1\",\"state\":\"open\"}}", "{\"kind\":\"RK-CARRY-FORWARD\",\"fields\":{\"matter\":\"Pay-rate changes approved after the fact\",\"action\":\"Reassess the payroll control at planning.\",\"raised_by\":\"manager\",\"raised_at\":\"2026-03-25T11:10\",\"state\":\"open\"}}"].vals()) { carryIds := Array.concat(carryIds, [idOf(must("matter carried forward", E.addRecord(s, manager, false, 6, 1, j(m))))]) };
check("the completion form reads the oracle's counts", liveIs([("minutes_reviewed", 3), ("meetings_noted", 2), ("minutes_unresolved", 1), ("meetings_unresolved", 1), ("carried_forward", 2)]));
let g0 = gov();
check("the page lists every record and names what holds the file", Py.list(g0, "minutes").size() == 3 and Py.list(g0, "meetings").size() == 2 and Py.list(g0, "carried").size() == 2 and Py.list(g0, "unresolved").size() == 2 and Py.natOr(g0, "open_matters", 0) == 2);
check("the unresolved list names the matter and the discussion", (func() : Bool {
  var names = "";
  for (u in Py.list(g0, "unresolved").vals()) names #= Py.textOr(u, "matter", "") # "|";
  Text.contains(names, #text "New borrowing after the year end: disclosure and the going-concern forecast") and Text.contains(names, #text "December shipments invoiced before the bill of lading date.")
})());

// the file is not assembled over a significant matter without its resolution
ignore must("to fieldwork", E.advanceStatus(s, partner, false, 7, 1, "fieldwork"));
ignore must("to completion", E.advanceStatus(s, partner, false, 7, 1, "completion"));
refused("assembly waits for the resolutions", F.assembleFile(s, ff, partner, false, 8, 1, "2026-03-25", "2026-03-26T10:00"), "matter(s) from minutes, meetings and consultations have no resolution");
ignore must("the resolution of the minutes matter is documented", E.updateRecord(s, senior, false, 9, minutesIds[0], j("{\"fields\":{\"meeting\":\"Board of directors\",\"held_on\":\"2025-11-20\",\"extract\":\"The board approved a term loan of EGP 40m for the new spinning frame.\",\"matter\":\"New borrowing after the year end: disclosure and the going-concern forecast\",\"significance\":\"significant\",\"procedure\":\"P-FSL-008\",\"reviewed_by\":\"senior\",\"reviewed_at\":\"2026-01-12T10:00\",\"resolution\":\"Loan disclosed in note 27 and in the going-concern forecast.\"}}")));
refused("one resolution is not enough", F.assembleFile(s, ff, partner, false, 10, 1, "2026-03-25", "2026-03-26T10:00"), "record " # Nat.toText(meetingIds[0]));
ignore must("the resolution of the meeting matter is documented", E.updateRecord(s, senior, false, 11, meetingIds[0], j("{\"fields\":{\"with_whom\":\"Chief financial officer\",\"party\":\"management\",\"held_on\":\"2026-01-22T14:00\",\"discussed\":\"December shipments invoiced before the bill of lading date.\",\"agreed\":\"Management reverses the two invoices.\",\"significance\":\"significant\",\"recorded_by\":\"senior\",\"recorded_at\":\"2026-01-22T17:00\",\"resolution\":\"Reversed and recorded as a corrected misstatement.\"}}")));
ignore must("a matter is addressed with a note", E.updateRecord(s, manager, false, 12, carryIds[1], j("{\"fields\":{\"matter\":\"Pay-rate changes approved after the fact\",\"action\":\"Reassess the payroll control at planning.\",\"raised_by\":\"manager\",\"raised_at\":\"2026-03-25T11:10\",\"state\":\"addressed\",\"addressed_note\":\"Control remediated in January; walkthrough performed.\"}}")));
check("the counts follow: nothing unresolved, one matter still open", liveIs([("minutes_reviewed", 3), ("meetings_noted", 2), ("minutes_unresolved", 0), ("meetings_unresolved", 0), ("carried_forward", 1)]));
check("nothing holds the file on this account", Gv.unresolved(s, 1).size() == 0 and Gv.openMatters(s, 1).size() == 1);
switch (F.assembleFile(s, ff, partner, false, 13, 1, "2026-03-25", "2026-03-26T10:00")) {
  case (#err(m)) { checks += 1; if (Text.contains(m, #text "minutes and meetings")) { failed += 1; Debug.print("FAIL the resolved matters still hold the file: " # m) } };
  case (#ok(_)) { checks += 1; failed += 1; Debug.print("FAIL the file assembled without its completion form") };
};

Debug.print("count: governance checks = " # Nat.toText(checks));
Debug.print("count: minutes reviewed = " # Nat.toText(3));
Debug.print("count: meetings noted = " # Nat.toText(2));
Debug.print("count: matters carried = " # Nat.toText(2));
Debug.print("count: refusals = " # Nat.toText(refusals));
if (failed > 0) Runtime.trap("GOVERNANCE RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("GOVERNANCE GREEN");
