// GENERATED by tools/gen_letters_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import F "../src/Forms";
import FF "../src/FirmForms";
import Lt "../src/Letters";
import Json "../src/Json";
import Py "../src/Py";
import List "mo:core/List";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let staff = Principal.fromBlob("\04");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
var sentLetters = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func view(who : Principal, form : Text) : Json.J {
  switch (F.view(s, ff, who, false, 1, form)) { case (#ok(v)) v; case (#err(m)) { checks += 1; failed += 1; Debug.print("FAIL view " # form # ": " # m); #null_ } };
};
func send(form : Text, with_ : Text, proc : Text, addressee : Text, at : Text) : E.R {
  F.sendLetter(s, ff, staff, false, 30, 1, form, #obj([("with", #str(with_)), ("procedure", #str(proc)), ("addressee", #str(addressee)), ("sent_at", #str(at)), ("due", #str("2026-03-15"))]))
};

// the engagement and its team
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Nile Trading SAE\",\"framework\":\"EAS\",\"audit_standard\":\"EAS\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (senior, "senior"), (staff, "staff")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));
check("nine letter templates are catalogued as letters", (func() : Bool { var n = 0; for (c in Py.items(F.catalogue(ff)).vals()) { if (Py.textOr(c, "kind", "") == "letter" and Py.natOr(c, "number", 0) >= 41) n += 1 }; n == 9 })());
check("a letter's definition carries its paragraphs in both languages", (func() : Bool { let v = view(staff, "F41-CONFIRMATION-RECEIVABLE"); Py.list(field(v, ["form", "letter"]), "en").size() == 7 and Py.list(field(v, ["form", "letter"]), "ar").size() == 7 })());
check("a letter's balance date is read from the engagement", field(view(staff, "F41-CONFIRMATION-RECEIVABLE"), ["live", "balance_date"]) == #str("2025-12-31"));

// what sending refuses before any letter is prepared
refused("a letter that has not been started is not sent", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-02-01T09:00"), "not been started");
ignore must("fill the receivable confirmation", F.save(s, ff, staff, false, 3, 1, "F41-CONFIRMATION-RECEIVABLE", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"reply_by\":\"2026-03-01\",\"balance\":\"1000.00\"}}")));
refused("a draft is not sent", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-02-01T09:00"), "draft is not sent");
ignore must("prepare the receivable confirmation", F.sign(s, ff, staff, 4, 1, "F41-CONFIRMATION-RECEIVABLE", "prepare", "2026-02-01T08:00"));
refused("a form that is not a letter is not sent", F.sendLetter(s, ff, staff, false, 5, 1, "F06-MATERIALITY", #obj([("with", #str("management")), ("procedure", #str("P-FSL-006")), ("addressee", #str("x")), ("sent_at", #str("2026-02-01T09:00"))])), "not a letter");
refused("a procedure the letter does not serve", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-PUR-004", "Delta Textiles", "2026-02-01T09:00"), "does not serve");
refused("no addressee", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", " ", "2026-02-01T09:00"), "addressee is required");
refused("a party outside the six", send("F41-CONFIRMATION-RECEIVABLE", "customer", "P-REV-008", "Delta Textiles", "2026-02-01T09:00"), "must be one of");
refused("a date before the file's latest", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-01-01T09:00"), "earlier than");

// every template: filled, prepared, sent; the communication and the request read back
let sent_0 = must("send F41-CONFIRMATION-RECEIVABLE", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-02-01T10:00"));
sentLetters += 1;
check("F41-CONFIRMATION-RECEIVABLE: the communication names the party, the subject and the time", field(sent_0, ["communication", "fields", "with"]) == #str("management") and field(sent_0, ["communication", "fields", "direction"]) == #str("sent") and field(sent_0, ["communication", "fields", "form"]) == #str("written") and field(sent_0, ["communication", "fields", "at"]) == #str("2026-02-01T10:00") and Text.contains(Py.textOr(field(sent_0, ["communication", "fields"]), "subject", ""), #text "F41-CONFIRMATION-RECEIVABLE"));
check("F41-CONFIRMATION-RECEIVABLE: the request names the procedure, the addressee and the due date", field(sent_0, ["request", "fields", "procedure"]) == #str("P-REV-008") and field(sent_0, ["request", "fields", "addressee"]) == #str("Delta Textiles") and field(sent_0, ["request", "fields", "state"]) == #str("open") and field(sent_0, ["request", "fields", "due"]) == #str("2026-03-15"));
check("F41-CONFIRMATION-RECEIVABLE: the paper counts the requests of its procedure live", field(view(staff, "F41-CONFIRMATION-RECEIVABLE"), ["live", "sent"]) == #num("1"));
ignore must("fill F42-CONFIRMATION-PAYABLE", F.save(s, ff, staff, false, 11, 1, "F42-CONFIRMATION-PAYABLE", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"reply_by\":\"2026-03-01\",\"balance\":\"1000.00\"}}")));
ignore must("prepare F42-CONFIRMATION-PAYABLE", F.sign(s, ff, staff, 11, 1, "F42-CONFIRMATION-PAYABLE", "prepare", "2026-02-01T10:30"));
let sent_1 = must("send F42-CONFIRMATION-PAYABLE", send("F42-CONFIRMATION-PAYABLE", "management", "P-PUR-004", "Delta Textiles", "2026-02-01T11:00"));
sentLetters += 1;
check("F42-CONFIRMATION-PAYABLE: the communication names the party, the subject and the time", field(sent_1, ["communication", "fields", "with"]) == #str("management") and field(sent_1, ["communication", "fields", "direction"]) == #str("sent") and field(sent_1, ["communication", "fields", "form"]) == #str("written") and field(sent_1, ["communication", "fields", "at"]) == #str("2026-02-01T11:00") and Text.contains(Py.textOr(field(sent_1, ["communication", "fields"]), "subject", ""), #text "F42-CONFIRMATION-PAYABLE"));
check("F42-CONFIRMATION-PAYABLE: the request names the procedure, the addressee and the due date", field(sent_1, ["request", "fields", "procedure"]) == #str("P-PUR-004") and field(sent_1, ["request", "fields", "addressee"]) == #str("Delta Textiles") and field(sent_1, ["request", "fields", "state"]) == #str("open") and field(sent_1, ["request", "fields", "due"]) == #str("2026-03-15"));
check("F42-CONFIRMATION-PAYABLE: the paper counts the requests of its procedure live", field(view(staff, "F42-CONFIRMATION-PAYABLE"), ["live", "sent"]) == #num("1"));
ignore must("fill F43-CONFIRMATION-DEBT", F.save(s, ff, staff, false, 12, 1, "F43-CONFIRMATION-DEBT", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"reply_by\":\"2026-03-01\",\"facility\":\"Recorded for the graph battery.\",\"principal\":\"1000.00\"}}")));
ignore must("prepare F43-CONFIRMATION-DEBT", F.sign(s, ff, staff, 12, 1, "F43-CONFIRMATION-DEBT", "prepare", "2026-02-01T11:30"));
let sent_2 = must("send F43-CONFIRMATION-DEBT", send("F43-CONFIRMATION-DEBT", "management", "P-TRE-005", "Delta Textiles", "2026-02-01T12:00"));
sentLetters += 1;
check("F43-CONFIRMATION-DEBT: the communication names the party, the subject and the time", field(sent_2, ["communication", "fields", "with"]) == #str("management") and field(sent_2, ["communication", "fields", "direction"]) == #str("sent") and field(sent_2, ["communication", "fields", "form"]) == #str("written") and field(sent_2, ["communication", "fields", "at"]) == #str("2026-02-01T12:00") and Text.contains(Py.textOr(field(sent_2, ["communication", "fields"]), "subject", ""), #text "F43-CONFIRMATION-DEBT"));
check("F43-CONFIRMATION-DEBT: the request names the procedure, the addressee and the due date", field(sent_2, ["request", "fields", "procedure"]) == #str("P-TRE-005") and field(sent_2, ["request", "fields", "addressee"]) == #str("Delta Textiles") and field(sent_2, ["request", "fields", "state"]) == #str("open") and field(sent_2, ["request", "fields", "due"]) == #str("2026-03-15"));
check("F43-CONFIRMATION-DEBT: the paper counts the requests of its procedure live", field(view(staff, "F43-CONFIRMATION-DEBT"), ["live", "sent"]) == #num("1"));
ignore must("fill F44-CONFIRMATION-INVENTORY-CONSIGNED", F.save(s, ff, staff, false, 13, 1, "F44-CONFIRMATION-INVENTORY-CONSIGNED", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"reply_by\":\"2026-03-01\",\"goods\":[{\"description\":\"Recorded for the graph battery.\",\"quantity\":\"Recorded for the graph battery.\"}]}}")));
ignore must("prepare F44-CONFIRMATION-INVENTORY-CONSIGNED", F.sign(s, ff, staff, 13, 1, "F44-CONFIRMATION-INVENTORY-CONSIGNED", "prepare", "2026-02-01T12:30"));
let sent_3 = must("send F44-CONFIRMATION-INVENTORY-CONSIGNED", send("F44-CONFIRMATION-INVENTORY-CONSIGNED", "management", "P-INV-004", "Delta Textiles", "2026-02-01T13:00"));
sentLetters += 1;
check("F44-CONFIRMATION-INVENTORY-CONSIGNED: the communication names the party, the subject and the time", field(sent_3, ["communication", "fields", "with"]) == #str("management") and field(sent_3, ["communication", "fields", "direction"]) == #str("sent") and field(sent_3, ["communication", "fields", "form"]) == #str("written") and field(sent_3, ["communication", "fields", "at"]) == #str("2026-02-01T13:00") and Text.contains(Py.textOr(field(sent_3, ["communication", "fields"]), "subject", ""), #text "F44-CONFIRMATION-INVENTORY-CONSIGNED"));
check("F44-CONFIRMATION-INVENTORY-CONSIGNED: the request names the procedure, the addressee and the due date", field(sent_3, ["request", "fields", "procedure"]) == #str("P-INV-004") and field(sent_3, ["request", "fields", "addressee"]) == #str("Delta Textiles") and field(sent_3, ["request", "fields", "state"]) == #str("open") and field(sent_3, ["request", "fields", "due"]) == #str("2026-03-15"));
check("F44-CONFIRMATION-INVENTORY-CONSIGNED: the paper counts the requests of its procedure live", field(view(staff, "F44-CONFIRMATION-INVENTORY-CONSIGNED"), ["live", "sent"]) == #num("1"));
ignore must("fill F45-CONFIRMATION-INVENTORY-HELD", F.save(s, ff, staff, false, 14, 1, "F45-CONFIRMATION-INVENTORY-HELD", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"reply_by\":\"2026-03-01\",\"goods\":[{\"description\":\"Recorded for the graph battery.\",\"quantity\":\"Recorded for the graph battery.\"}]}}")));
ignore must("prepare F45-CONFIRMATION-INVENTORY-HELD", F.sign(s, ff, staff, 14, 1, "F45-CONFIRMATION-INVENTORY-HELD", "prepare", "2026-02-01T13:30"));
let sent_4 = must("send F45-CONFIRMATION-INVENTORY-HELD", send("F45-CONFIRMATION-INVENTORY-HELD", "management", "P-INV-004", "Delta Textiles", "2026-02-01T14:00"));
sentLetters += 1;
check("F45-CONFIRMATION-INVENTORY-HELD: the communication names the party, the subject and the time", field(sent_4, ["communication", "fields", "with"]) == #str("management") and field(sent_4, ["communication", "fields", "direction"]) == #str("sent") and field(sent_4, ["communication", "fields", "form"]) == #str("written") and field(sent_4, ["communication", "fields", "at"]) == #str("2026-02-01T14:00") and Text.contains(Py.textOr(field(sent_4, ["communication", "fields"]), "subject", ""), #text "F45-CONFIRMATION-INVENTORY-HELD"));
check("F45-CONFIRMATION-INVENTORY-HELD: the request names the procedure, the addressee and the due date", field(sent_4, ["request", "fields", "procedure"]) == #str("P-INV-004") and field(sent_4, ["request", "fields", "addressee"]) == #str("Delta Textiles") and field(sent_4, ["request", "fields", "state"]) == #str("open") and field(sent_4, ["request", "fields", "due"]) == #str("2026-03-15"));
check("F45-CONFIRMATION-INVENTORY-HELD: the paper counts the requests of its procedure live", field(view(staff, "F45-CONFIRMATION-INVENTORY-HELD"), ["live", "sent"]) == #num("2"));
ignore must("fill F46-LEGAL-LETTER", F.save(s, ff, staff, false, 15, 1, "F46-LEGAL-LETTER", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"reply_by\":\"2026-03-01\",\"matters\":[{\"matter\":\"Recorded for the graph battery.\",\"status\":\"Recorded for the graph battery.\"}]}}")));
ignore must("prepare F46-LEGAL-LETTER", F.sign(s, ff, staff, 15, 1, "F46-LEGAL-LETTER", "prepare", "2026-02-01T14:30"));
let sent_5 = must("send F46-LEGAL-LETTER", send("F46-LEGAL-LETTER", "management", "P-FSL-033", "Nile Legal Partners", "2026-02-01T15:00"));
sentLetters += 1;
check("F46-LEGAL-LETTER: the communication names the party, the subject and the time", field(sent_5, ["communication", "fields", "with"]) == #str("management") and field(sent_5, ["communication", "fields", "direction"]) == #str("sent") and field(sent_5, ["communication", "fields", "form"]) == #str("written") and field(sent_5, ["communication", "fields", "at"]) == #str("2026-02-01T15:00") and Text.contains(Py.textOr(field(sent_5, ["communication", "fields"]), "subject", ""), #text "F46-LEGAL-LETTER"));
check("F46-LEGAL-LETTER: the request names the procedure, the addressee and the due date", field(sent_5, ["request", "fields", "procedure"]) == #str("P-FSL-033") and field(sent_5, ["request", "fields", "addressee"]) == #str("Nile Legal Partners") and field(sent_5, ["request", "fields", "state"]) == #str("open") and field(sent_5, ["request", "fields", "due"]) == #str("2026-03-15"));
check("F46-LEGAL-LETTER: the paper counts the requests of its procedure live", field(view(staff, "F46-LEGAL-LETTER"), ["live", "sent"]) == #num("1"));
ignore must("fill F47-PREDECESSOR-LETTER", F.save(s, ff, staff, false, 16, 1, "F47-PREDECESSOR-LETTER", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"reply_by\":\"2026-03-01\",\"consent_date\":\"2026-01-20\",\"prior_period_end\":\"2024-12-31\"}}")));
ignore must("prepare F47-PREDECESSOR-LETTER", F.sign(s, ff, staff, 16, 1, "F47-PREDECESSOR-LETTER", "prepare", "2026-02-01T15:30"));
let sent_6 = must("send F47-PREDECESSOR-LETTER", send("F47-PREDECESSOR-LETTER", "predecessor", "P-FSL-004", "Previous & Co", "2026-02-01T16:00"));
sentLetters += 1;
check("F47-PREDECESSOR-LETTER: the communication names the party, the subject and the time", field(sent_6, ["communication", "fields", "with"]) == #str("predecessor") and field(sent_6, ["communication", "fields", "direction"]) == #str("sent") and field(sent_6, ["communication", "fields", "form"]) == #str("written") and field(sent_6, ["communication", "fields", "at"]) == #str("2026-02-01T16:00") and Text.contains(Py.textOr(field(sent_6, ["communication", "fields"]), "subject", ""), #text "F47-PREDECESSOR-LETTER"));
check("F47-PREDECESSOR-LETTER: the request names the procedure, the addressee and the due date", field(sent_6, ["request", "fields", "procedure"]) == #str("P-FSL-004") and field(sent_6, ["request", "fields", "addressee"]) == #str("Previous & Co") and field(sent_6, ["request", "fields", "state"]) == #str("open") and field(sent_6, ["request", "fields", "due"]) == #str("2026-03-15"));
check("F47-PREDECESSOR-LETTER: the paper counts the requests of its procedure live", field(view(staff, "F47-PREDECESSOR-LETTER"), ["live", "sent"]) == #num("1"));
ignore must("fill F48-GOVERNANCE-PLANNING-LETTER", F.save(s, ff, staff, false, 17, 1, "F48-GOVERNANCE-PLANNING-LETTER", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"scope\":\"Recorded for the graph battery.\",\"timing\":\"Recorded for the graph battery.\",\"significant_risks\":\"Recorded for the graph battery.\",\"team\":\"Recorded for the graph battery.\",\"independence\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"reply_by\":\"2026-03-01\"}}")));
ignore must("prepare F48-GOVERNANCE-PLANNING-LETTER", F.sign(s, ff, staff, 17, 1, "F48-GOVERNANCE-PLANNING-LETTER", "prepare", "2026-02-01T16:30"));
let sent_7 = must("send F48-GOVERNANCE-PLANNING-LETTER", send("F48-GOVERNANCE-PLANNING-LETTER", "tcwg", "P-FSL-047", "The audit committee", "2026-02-01T17:00"));
sentLetters += 1;
check("F48-GOVERNANCE-PLANNING-LETTER: the communication names the party, the subject and the time", field(sent_7, ["communication", "fields", "with"]) == #str("tcwg") and field(sent_7, ["communication", "fields", "direction"]) == #str("sent") and field(sent_7, ["communication", "fields", "form"]) == #str("written") and field(sent_7, ["communication", "fields", "at"]) == #str("2026-02-01T17:00") and Text.contains(Py.textOr(field(sent_7, ["communication", "fields"]), "subject", ""), #text "F48-GOVERNANCE-PLANNING-LETTER"));
check("F48-GOVERNANCE-PLANNING-LETTER: the request names the procedure, the addressee and the due date", field(sent_7, ["request", "fields", "procedure"]) == #str("P-FSL-047") and field(sent_7, ["request", "fields", "addressee"]) == #str("The audit committee") and field(sent_7, ["request", "fields", "state"]) == #str("open") and field(sent_7, ["request", "fields", "due"]) == #str("2026-03-15"));
check("F48-GOVERNANCE-PLANNING-LETTER: the paper counts the requests of its procedure live", field(view(staff, "F48-GOVERNANCE-PLANNING-LETTER"), ["live", "sent"]) == #num("1"));
ignore must("fill F49-DELIVERABLES-LETTER", F.save(s, ff, staff, false, 18, 1, "F49-DELIVERABLES-LETTER", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"deliverables\":[{\"deliverable\":\"Recorded for the graph battery.\",\"date\":\"2026-02-01\"}],\"provided_by_entity\":[{\"item\":\"Recorded for the graph battery.\",\"date\":\"2026-02-01\"}],\"fees\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"reply_by\":\"2026-03-01\"}}")));
ignore must("prepare F49-DELIVERABLES-LETTER", F.sign(s, ff, staff, 18, 1, "F49-DELIVERABLES-LETTER", "prepare", "2026-02-01T17:30"));
let sent_8 = must("send F49-DELIVERABLES-LETTER", send("F49-DELIVERABLES-LETTER", "management", "P-FSL-003", "The audit committee", "2026-02-01T18:00"));
sentLetters += 1;
check("F49-DELIVERABLES-LETTER: the communication names the party, the subject and the time", field(sent_8, ["communication", "fields", "with"]) == #str("management") and field(sent_8, ["communication", "fields", "direction"]) == #str("sent") and field(sent_8, ["communication", "fields", "form"]) == #str("written") and field(sent_8, ["communication", "fields", "at"]) == #str("2026-02-01T18:00") and Text.contains(Py.textOr(field(sent_8, ["communication", "fields"]), "subject", ""), #text "F49-DELIVERABLES-LETTER"));
check("F49-DELIVERABLES-LETTER: the request names the procedure, the addressee and the due date", field(sent_8, ["request", "fields", "procedure"]) == #str("P-FSL-003") and field(sent_8, ["request", "fields", "addressee"]) == #str("The audit committee") and field(sent_8, ["request", "fields", "state"]) == #str("open") and field(sent_8, ["request", "fields", "due"]) == #str("2026-03-15"));
check("F49-DELIVERABLES-LETTER: the paper counts the requests of its procedure live", field(view(staff, "F49-DELIVERABLES-LETTER"), ["live", "sent"]) == #num("1"));

// a letter changed after sending is a new version, sent again; the same version never twice
refused("the same version of a letter is not sent twice", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-02-02T09:00"), "sent already");
ignore must("the partner reopens the letter", F.reopen(s, partner, false, 40, 1, "F41-CONFIRMATION-RECEIVABLE", "the balance was restated"));
ignore must("fill the letter again", F.save(s, ff, staff, false, 41, 1, "F41-CONFIRMATION-RECEIVABLE", j("{\"values\":{\"party\":\"Recorded for the graph battery.\",\"address\":\"Recorded for the graph battery.\",\"reply_to\":\"Recorded for the graph battery.\",\"request_date\":\"2026-02-01\",\"reply_by\":\"2026-03-01\",\"balance\":\"250000.00\"}}")));
ignore must("prepare it again", F.sign(s, ff, staff, 42, 1, "F41-CONFIRMATION-RECEIVABLE", "prepare", "2026-02-02T09:30"));
ignore must("the new version is sent", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-02-02T10:00"));
sentLetters += 1;
check("the paper counts both requests live", field(view(staff, "F41-CONFIRMATION-RECEIVABLE"), ["live", "sent"]) == #num("2"));
check("the letters sent list every request they opened", Lt.sent(s, 1).size() == 10);

Debug.print("count: letter checks = " # Nat.toText(checks));
Debug.print("count: letters sent = " # Nat.toText(sentLetters));
Debug.print("count: placeholders resolved in both languages = " # Nat.toText(182));
Debug.print("count: refusals = " # Nat.toText(refusals));
if (failed > 0) Runtime.trap("LETTERS RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("LETTERS GREEN");
