// GENERATED by tools/gen_signing_test.py from Python cryptography. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import G "../src/Signing";
import Json "../src/Json";
import Py "../src/Py";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let client = Principal.fromBlob("\06");
let other = Principal.fromBlob("\07");
let engine = E.init();
let s = G.init();
let DOC = "612becafc2519a2c2bf0a293551d75f88a8a0d6441e2b6c807f38c6027acc59f";
var doc = DOC;
let c : G.Ctx = { engine; contract = "test-contract"; origin = "https://<thebes-gateway>";
  lookup = func(p : Principal, t : Text) : ?Text { if (t == "evidence:7" and (Principal.equal(p, client) or Principal.equal(p, other))) ?doc else null } };

var checks = 0;
var failed = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func must(name : Text, r : E.R) : Json.J { checks += 1; switch (r) { case (#ok(x)) x; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } } };
func refused(name : Text, r : E.R, why : Text) {
  checks += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": refused for the wrong reason: " # m) } };
  };
};
func try_(name : Text, nonce : Text, cred : Text, a : (Text, Text, Text), why : Text) { refused(name, G.complete(s, c, client, 10, nonce, cred, a.0, a.1, a.2), why) };

// base64url round trip (the challenge encoding)
check("base64url round-trips", switch (G.unb64(G.b64url("\00\01\fe\ff\10"))) { case (?b) b == "\00\01\fe\ff\10"; case null false });

// keys
refused("a key that is not on the curve is refused", G.registerKey(s, c, client, 1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEAAAA", "phone"), "P-256");
ignore must("the client registers a signing passkey", G.registerKey(s, c, client, 1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXvVggflIZCmNNx6SqBpQcRX1Ifk+qiG1xPrjAW/vgSgxJ9DV0aG5w+jf7FZ4x3fpnTwBuaCYm7kKdD++cGvHPQ==", "phone"));
ignore must("another person registers theirs", G.registerKey(s, c, other, 1, "_-HCpUkHdxkK6YLBJz9gYLTOfxhkFmR0mnjZJHYr7Zo", "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGPGfr8ewF0RXvdTWiN8wTRXEasDEKz17lwqWqsDxh9WFq/y7Kensw1Dgi0JUGB5RkHpJxdI8bUUDj9TPU3b2cw==", "laptop"));
refused("one credential cannot be registered by two people", G.registerKey(s, c, other, 2, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXvVggflIZCmNNx6SqBpQcRX1Ifk+qiG1xPrjAW/vgSgxJ9DV0aG5w+jf7FZ4x3fpnTwBuaCYm7kKdD++cGvHPQ==", "x"), "already registered");

// a challenge is only for what the signer can see
refused("nothing unseen can be signed", G.begin(s, c, client, 3, "evidence:8"), "not permitted");
let b1 = must("the client asks to sign the letter", G.begin(s, c, client, 3, "evidence:7"));
let n1 = Py.textOr(b1, "nonce", "");
check("the contract names the hash it derived", Py.textOr(b1, "doc_hash", "") == DOC);
refused("another person cannot answer the client's challenge", G.complete(s, c, other, 4, n1, "_-HCpUkHdxkK6YLBJz9gYLTOfxhkFmR0mnjZJHYr7Zo", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEUCIQD7iDj7NvhBhkyvdjx3TwHYMmU5NXMndfEnTp+3lH6imgIgVFfEz/xVpnC6agThhJo5cOX6Copl5ARagRCwqlMYW/M=").0, ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEUCIQD7iDj7NvhBhkyvdjx3TwHYMmU5NXMndfEnTp+3lH6imgIgVFfEz/xVpnC6agThhJo5cOX6Copl5ARagRCwqlMYW/M=").1, ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEUCIQD7iDj7NvhBhkyvdjx3TwHYMmU5NXMndfEnTp+3lH6imgIgVFfEz/xVpnC6agThhJo5cOX6Copl5ARagRCwqlMYW/M=").2), "issued to someone else");
try_("an assertion without user verification is refused", n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMBAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEYCIQCJckc3bYorKv7AF9GKsDCIYyt/t6mlVvymbA57wKhJGgIhANh9QjSQfimSYs0TZtXXo6BbIpqzfOi2w4lcPOWMQ2/9"), "did not verify the user");
try_("an assertion made on another origin is refused", n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vZXZpbC5leGFtcGxlIiwiY3Jvc3NPcmlnaW4iOmZhbHNlfQ==", "MEQCICZqdPOHPxtvysZqPZd3gCgEge5kNhP949HUXgw6uLJuAiBjvp/ZCe00Gp2NFjvmDxb1v2vumHWQZRmL1OORKZRasw=="), "another origin");
try_("an assertion for another relying party is refused", n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("nBgN4M1pnueIl8R8/bPn7h11kG4xt3RqR0fepTaQmDcFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEQCIBZJQAfTbyQbv/PxlOO08GdvoCCLxC74beu55aAjmsJbAiBCUzVLBHsvluIrrCRRRAt+Rz6TPua0cYd+PhW0LZEh7Q=="), "another relying party");
try_("a registration is not a signature", n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEUCIQDE2UZsZNM3phpFbZBQzEW2jHUa8yTmtpyc6NUYL41NGgIgFC4knSj8lNbyL5WKJLP64/fLCcSVAkmebe43wEYJVXY="), "not a WebAuthn get");
try_("a signature by another key under the client's credential fails", n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEUCIQD7iDj7NvhBhkyvdjx3TwHYMmU5NXMndfEnTp+3lH6imgIgVFfEz/xVpnC6agThhJo5cOX6Copl5ARagRCwqlMYW/M="), "does not verify");
try_("a tampered authenticatorData fails", n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAg==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEYCIQCwHpK3H475GsglA0s176rn5dCzlpWOUoN1BhIyHUZuQQIhAO9qCHzITLY33klRFI9z7mrB7s/SxcV0/QbTYOUP2Ki0"), "does not verify");
try_("an assertion for a different challenge is refused", n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiY2dyTnRNenRZTmNyYUZfVlhrRmdhUy04cUFIWmRwTDAzVU5sdzZENEZBYyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEYCIQDCVsynI+hzdFhKYYJgBxuDJ+JHg6h3TCLmGNYie4c7uAIhAI3QSpvMFSDWfTbExbnvMQUrHpe5a0qf1uCrC5Xtcdkb"), "different challenge");
doc := "0000000000000000000000000000000000000000000000000000000000000000";
try_("a document changed since the challenge cannot be signed", n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEQCIDi0mLC2Qj3j7YBa1oM+UlnuOFf0pu7mX7eNLoPFVkUDAiBRlcxhG5WeWZtLGZD7lrArao3hcVxD1sr5YhT9JOUePg=="), "document changed");
doc := DOC;
let sg = must("the passkey signature is accepted", G.complete(s, c, client, 11, n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEQCIDi0mLC2Qj3j7YBa1oM+UlnuOFf0pu7mX7eNLoPFVkUDAiBRlcxhG5WeWZtLGZD7lrArao3hcVxD1sr5YhT9JOUePg==").0, ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEQCIDi0mLC2Qj3j7YBa1oM+UlnuOFf0pu7mX7eNLoPFVkUDAiBRlcxhG5WeWZtLGZD7lrArao3hcVxD1sr5YhT9JOUePg==").1, ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEQCIDi0mLC2Qj3j7YBa1oM+UlnuOFf0pu7mX7eNLoPFVkUDAiBRlcxhG5WeWZtLGZD7lrArao3hcVxD1sr5YhT9JOUePg==").2));
check("the signature records the hash and the signer", Py.textOr(sg, "doc_hash", "") == DOC and Py.textOr(sg, "signer", "") == Principal.toText(client));
try_("a challenge is used once", n1, "CmqYPRb_BNWS_WsQ2yKmYwFpXdexYjlz1xc6bS5y0nE", ("FzW5fhRIxH+dWz0aYBrheT9Q3siRxzThHIIJxG6+ANMFAAAAAQ==", "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoieXhlNzFEQ1F1ZS16RS1LUlgxOENzemhndzBxekRFb3VmNWZ5UXNWOG8xcyIsIm9yaWdpbiI6Imh0dHBzOi8vbWVtcGhpcy5tZXJjYXR1cmFmb3J1bS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9", "MEQCIDi0mLC2Qj3j7YBa1oM+UlnuOFf0pu7mX7eNLoPFVkUDAiBRlcxhG5WeWZtLGZD7lrArao3hcVxD1sr5YhT9JOUePg=="), "was used or withdrawn");
check("the signature is listed on the document", Py.items(must("signatures", G.signaturesOn(s, c, client, "evidence:7"))).size() == 1);
let bd = must("the bundle for verification off the chain", G.bundle(s, c, client, 1));
check("the bundle carries the public key and the origin", Py.textOr(bd, "public_key_spki", "") == "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXvVggflIZCmNNx6SqBpQcRX1Ifk+qiG1xPrjAW/vgSgxJ9DV0aG5w+jf7FZ4x3fpnTwBuaCYm7kKdD++cGvHPQ==" and Py.textOr(bd, "origin", "") == "https://<thebes-gateway>");
check("the trail records the key registrations and the signature, intact", Json.get(E.verifyTrail(engine), "intact") == ?#bool(true) and Py.natOr(E.verifyTrail(engine), "entries_examined", 0) == 3);
ignore must("the client revokes the passkey", G.revokeKey(s, c, client, 12, 1));
refused("a revoked passkey cannot start a signature", G.begin(s, c, client, 13, "evidence:7"), "register a signing passkey first");

Debug.print("count: signing checks = " # Nat.toText(checks));
if (failed > 0) Runtime.trap("SIGNING RED: " # Nat.toText(failed) # " of " # Nat.toText(checks));
Debug.print("SIGNING GREEN");
