#!/usr/bin/env python3
"""Test vectors for motoko/src/Signing.mo: WebAuthn assertions built and signed with the
Python `cryptography` library exactly as a browser's authenticator would, then broken in
every way the contract must refuse. Writes motoko/test/Signing.test.mo.

The contract's nonces are SHA-256("nonce|<counter>") and its challenges
SHA-256("thebes-audit/sign/v1|<contract>|<target>|<hash>|<nonce>"), so the assertions can
be prepared here for the challenges the test will be issued, in order.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import base64, hashlib, json, os
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'motoko', 'test', 'Signing.test.mo')
CONTRACT, ORIGIN, RP = 'test-contract', 'https://memphis.mercaturaforum.com', 'memphis.mercaturaforum.com'
DOC = hashlib.sha256(b'representation letter, 31 December 2025').hexdigest()
TARGET = 'evidence:7'

def b64(b): return base64.b64encode(b).decode()
def b64url(b): return base64.urlsafe_b64encode(b).decode().rstrip('=')
def sha(b): return hashlib.sha256(b).digest()
def nonce(n): return hashlib.sha256(f'nonce|{n}'.encode()).hexdigest()
def challenge(n, target=TARGET, doc=DOC): return sha(f'thebes-audit/sign/v1|{CONTRACT}|{target}|{doc}|{nonce(n)}'.encode())

def key():
    k = ec.generate_private_key(ec.SECP256R1())
    spki = k.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    return k, b64(spki)

def assertion(k, chal, origin=ORIGIN, rp=RP, flags=0x05, typ='webauthn.get', tamper_auth=False):
    cd = json.dumps({'type': typ, 'challenge': b64url(chal), 'origin': origin, 'crossOrigin': False}, separators=(',', ':')).encode()
    ad = sha(rp.encode()) + bytes([flags]) + (1).to_bytes(4, 'big')
    sig = k.sign(ad + sha(cd), ec.ECDSA(hashes.SHA256()))
    if tamper_auth:
        ad = ad[:-1] + b'\x02'
    return b64(ad), b64(cd), b64(sig)

k1, spki1 = key()   # the client's signing passkey
k2, spki2 = key()   # someone else's
cred1, cred2 = b64url(os.urandom(32)), b64url(os.urandom(32))

# challenges are issued in this order by the test (counter 1, 2, ...)
v = {
    'no_uv': assertion(k1, challenge(1), flags=0x01),
    'wrong_origin': assertion(k1, challenge(1), origin='https://evil.example'),
    'wrong_rp': assertion(k1, challenge(1), rp='evil.example'),
    'wrong_type': assertion(k1, challenge(1), typ='webauthn.create'),
    'other_key': assertion(k2, challenge(1)),
    'tampered': assertion(k1, challenge(1), tamper_auth=True),
    'wrong_challenge': assertion(k1, challenge(2)),
    'good': assertion(k1, challenge(1)),
}

def mo(s): return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
def trip(name):
    a, c, s = v[name]
    return f'({mo(a)}, {mo(c)}, {mo(s)})'

body = f'''// GENERATED by tools/gen_signing_test.py from Python cryptography. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import G "../src/Signing";
import Json "../src/Json";
import Py "../src/Py";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let client = Principal.fromBlob("\\06");
let other = Principal.fromBlob("\\07");
let engine = E.init();
let s = G.init();
let DOC = {mo(DOC)};
var doc = DOC;
let c : G.Ctx = {{ engine; contract = {mo(CONTRACT)}; origin = {mo(ORIGIN)};
  lookup = func(p : Principal, t : Text) : ?Text {{ if (t == {mo(TARGET)} and (Principal.equal(p, client) or Principal.equal(p, other))) ?doc else null }} }};

var checks = 0;
var failed = 0;
func check(name : Text, cond : Bool) {{ checks += 1; if (not cond) {{ failed += 1; Debug.print("FAIL " # name) }} }};
func must(name : Text, r : E.R) : Json.J {{ checks += 1; switch (r) {{ case (#ok(x)) x; case (#err(m)) {{ failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ }} }} }};
func refused(name : Text, r : E.R, why : Text) {{
  checks += 1;
  switch (r) {{
    case (#ok(_)) {{ failed += 1; Debug.print("FAIL " # name # ": was accepted") }};
    case (#err(m)) {{ if (not Text.contains(m, #text why)) {{ failed += 1; Debug.print("FAIL " # name # ": refused for the wrong reason: " # m) }} }};
  }};
}};
func try_(name : Text, nonce : Text, cred : Text, a : (Text, Text, Text), why : Text) {{ refused(name, G.complete(s, c, client, 10, nonce, cred, a.0, a.1, a.2), why) }};

// base64url round trip (the challenge encoding)
check("base64url round-trips", switch (G.unb64(G.b64url("\\00\\01\\fe\\ff\\10"))) {{ case (?b) b == "\\00\\01\\fe\\ff\\10"; case null false }});

// keys
refused("a key that is not on the curve is refused", G.registerKey(s, c, client, 1, {mo(cred1)}, "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEAAAA", "phone"), "P-256");
ignore must("the client registers a signing passkey", G.registerKey(s, c, client, 1, {mo(cred1)}, {mo(spki1)}, "phone"));
ignore must("another person registers theirs", G.registerKey(s, c, other, 1, {mo(cred2)}, {mo(spki2)}, "laptop"));
refused("one credential cannot be registered by two people", G.registerKey(s, c, other, 2, {mo(cred1)}, {mo(spki1)}, "x"), "already registered");

// a challenge is only for what the signer can see
refused("nothing unseen can be signed", G.begin(s, c, client, 3, "evidence:8"), "not permitted");
let b1 = must("the client asks to sign the letter", G.begin(s, c, client, 3, {mo(TARGET)}));
let n1 = Py.textOr(b1, "nonce", "");
check("the contract names the hash it derived", Py.textOr(b1, "doc_hash", "") == DOC);
refused("another person cannot answer the client's challenge", G.complete(s, c, other, 4, n1, {mo(cred2)}, {trip('other_key')}.0, {trip('other_key')}.1, {trip('other_key')}.2), "issued to someone else");
try_("an assertion without user verification is refused", n1, {mo(cred1)}, {trip('no_uv')}, "did not verify the user");
try_("an assertion made on another origin is refused", n1, {mo(cred1)}, {trip('wrong_origin')}, "another origin");
try_("an assertion for another relying party is refused", n1, {mo(cred1)}, {trip('wrong_rp')}, "another relying party");
try_("a registration is not a signature", n1, {mo(cred1)}, {trip('wrong_type')}, "not a WebAuthn get");
try_("a signature by another key under the client's credential fails", n1, {mo(cred1)}, {trip('other_key')}, "does not verify");
try_("a tampered authenticatorData fails", n1, {mo(cred1)}, {trip('tampered')}, "does not verify");
try_("an assertion for a different challenge is refused", n1, {mo(cred1)}, {trip('wrong_challenge')}, "different challenge");
doc := "0000000000000000000000000000000000000000000000000000000000000000";
try_("a document changed since the challenge cannot be signed", n1, {mo(cred1)}, {trip('good')}, "document changed");
doc := DOC;
let sg = must("the passkey signature is accepted", G.complete(s, c, client, 11, n1, {mo(cred1)}, {trip('good')}.0, {trip('good')}.1, {trip('good')}.2));
check("the signature records the hash and the signer", Py.textOr(sg, "doc_hash", "") == DOC and Py.textOr(sg, "signer", "") == Principal.toText(client));
try_("a challenge is used once", n1, {mo(cred1)}, {trip('good')}, "was used or withdrawn");
check("the signature is listed on the document", Py.items(must("signatures", G.signaturesOn(s, c, client, {mo(TARGET)}))).size() == 1);
let bd = must("the bundle for verification off the chain", G.bundle(s, c, client, 1));
check("the bundle carries the public key and the origin", Py.textOr(bd, "public_key_spki", "") == {mo(spki1)} and Py.textOr(bd, "origin", "") == {mo(ORIGIN)});
check("the trail records the key registrations and the signature, intact", Json.get(E.verifyTrail(engine), "intact") == ?#bool(true) and Py.natOr(E.verifyTrail(engine), "entries_examined", 0) == 3);
ignore must("the client revokes the passkey", G.revokeKey(s, c, client, 12, 1));
refused("a revoked passkey cannot start a signature", G.begin(s, c, client, 13, {mo(TARGET)}), "register a signing passkey first");

Debug.print("count: signing checks = " # Nat.toText(checks));
if (failed > 0) Runtime.trap("SIGNING RED: " # Nat.toText(failed) # " of " # Nat.toText(checks));
Debug.print("SIGNING GREEN");
'''
open(OUT, 'w').write(body)
print('wrote', os.path.relpath(OUT))
