#!/usr/bin/env python3
"""Generate motoko/test/Letters.test.mo: the letter templates and the act of sending them.

Every template (forms/F41 to F49) is checked here before anything is generated: each of its
paragraphs, in both languages, refers only to fields the template carries or to attributes of
the engagement, so the letter renders from the file with nothing missing. Then, on an
engagement, every letter is filled with its required values, prepared and sent: the
communication record and the request record are checked against what was sent (with whom,
the subject, the procedure the letter serves, the addressee, the dates), the request counts
on the paper live, a draft is refused, a second send of the same version is refused, a
procedure the letter does not serve is refused, and a letter changed after sending is a new
version that can be sent again.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
OUT = os.path.join(ROOT, 'motoko', 'test', 'Letters.test.mo')
sys.path.insert(0, HERE)
from gen_graph_test import load_forms, required_values, mo  # noqa: E402
from forms_letters import SENT  # noqa: E402

FORMS = load_forms()
LETTERS = [FORMS[f] for f in sorted(FORMS) if f in SENT]
assert len(LETTERS) == 9, [f['id'] for f in LETTERS]
ENGAGEMENT_ATTRS = {'client', 'period_start', 'period_end', 'currency', 'framework', 'audit_standard'}
PLACEHOLDER = re.compile(r'\{\{(engagement\.([a-z_]+)|field:([a-z_]+)|table:([a-z_]+))\}\}')


def jl(obj):
    return mo(json.dumps(obj, ensure_ascii=False, separators=(',', ':')))


def check_template(f):
    """Every placeholder of every paragraph in both languages resolves; both languages have the
    same number of paragraphs; every table placeholder names a table field."""
    fields = {fd['id']: fd for s_ in f['sections'] for fd in s_['fields']}
    assert f['kind'] == 'letter' and 'letter' in f, f['id']
    assert len(f['letter']['en']) == len(f['letter']['ar']), f['id']
    n = 0
    for lang in ('en', 'ar'):
        for para in f['letter'][lang]:
            for m in PLACEHOLDER.finditer(para):
                n += 1
                if m.group(2):
                    assert m.group(2) in ENGAGEMENT_ATTRS, (f['id'], m.group(0))
                elif m.group(3):
                    assert m.group(3) in fields, (f['id'], m.group(0))
                else:
                    assert m.group(4) in fields and fields[m.group(4)]['type'] == 'table', (f['id'], m.group(0))
    assert n > 0
    return n


PLACEHOLDERS = {f['id']: check_template(f) for f in LETTERS}

HEAD = r'''// GENERATED by tools/gen_letters_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import F "../src/Forms";
import FF "../src/FirmForms";
import Lt "../src/Letters";
import Json "../src/Json";
import Py "../src/Py";
import List "mo:core/List";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let staff = Principal.fromBlob("\04");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
var sentLetters = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func view(who : Principal, form : Text) : Json.J {
  switch (F.view(s, ff, who, false, 1, form)) { case (#ok(v)) v; case (#err(m)) { checks += 1; failed += 1; Debug.print("FAIL view " # form # ": " # m); #null_ } };
};
func send(form : Text, with_ : Text, proc : Text, addressee : Text, at : Text) : E.R {
  F.sendLetter(s, ff, staff, false, 30, 1, form, #obj([("with", #str(with_)), ("procedure", #str(proc)), ("addressee", #str(addressee)), ("sent_at", #str(at)), ("due", #str("2026-03-15"))]))
};

// the engagement and its team
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Nile Trading SAE\",\"framework\":\"EAS\",\"audit_standard\":\"EAS\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (senior, "senior"), (staff, "staff")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));
check("nine letter templates are catalogued as letters", (func() : Bool { var n = 0; for (c in Py.items(F.catalogue(ff)).vals()) { if (Py.textOr(c, "kind", "") == "letter" and Py.natOr(c, "number", 0) >= 41) n += 1 }; n == 9 })());
check("a letter's definition carries its paragraphs in both languages", (func() : Bool { let v = view(staff, "F41-CONFIRMATION-RECEIVABLE"); Py.list(field(v, ["form", "letter"]), "en").size() == __F41_PARAS__ and Py.list(field(v, ["form", "letter"]), "ar").size() == __F41_PARAS__ })());
check("a letter's balance date is read from the engagement", field(view(staff, "F41-CONFIRMATION-RECEIVABLE"), ["live", "balance_date"]) == #str("2025-12-31"));

// what sending refuses before any letter is prepared
refused("a letter that has not been started is not sent", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-02-01T09:00"), "not been started");
ignore must("fill the receivable confirmation", F.save(s, ff, staff, false, 3, 1, "F41-CONFIRMATION-RECEIVABLE", j(__F41_FILL__)));
refused("a draft is not sent", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-02-01T09:00"), "draft is not sent");
ignore must("prepare the receivable confirmation", F.sign(s, ff, staff, 4, 1, "F41-CONFIRMATION-RECEIVABLE", "prepare", "2026-02-01T08:00"));
refused("a form that is not a letter is not sent", F.sendLetter(s, ff, staff, false, 5, 1, "F06-MATERIALITY", #obj([("with", #str("management")), ("procedure", #str("P-FSL-006")), ("addressee", #str("x")), ("sent_at", #str("2026-02-01T09:00"))])), "not a letter");
refused("a procedure the letter does not serve", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-PUR-004", "Delta Textiles", "2026-02-01T09:00"), "does not serve");
refused("no addressee", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", " ", "2026-02-01T09:00"), "addressee is required");
refused("a party outside the six", send("F41-CONFIRMATION-RECEIVABLE", "customer", "P-REV-008", "Delta Textiles", "2026-02-01T09:00"), "must be one of");
refused("a date before the file's latest", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-01-01T09:00"), "earlier than");

// every template: filled, prepared, sent; the communication and the request read back
__LETTERS__

// a letter changed after sending is a new version, sent again; the same version never twice
refused("the same version of a letter is not sent twice", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-02-02T09:00"), "sent already");
ignore must("the partner reopens the letter", F.reopen(s, partner, false, 40, 1, "F41-CONFIRMATION-RECEIVABLE", "the balance was restated"));
ignore must("fill the letter again", F.save(s, ff, staff, false, 41, 1, "F41-CONFIRMATION-RECEIVABLE", j(__F41_FILL2__)));
ignore must("prepare it again", F.sign(s, ff, staff, 42, 1, "F41-CONFIRMATION-RECEIVABLE", "prepare", "2026-02-02T09:30"));
ignore must("the new version is sent", send("F41-CONFIRMATION-RECEIVABLE", "management", "P-REV-008", "Delta Textiles", "2026-02-02T10:00"));
sentLetters += 1;
check("the paper counts both requests live", field(view(staff, "F41-CONFIRMATION-RECEIVABLE"), ["live", "sent"]) == #num("2"));
check("the letters sent list every request they opened", Lt.sent(s, 1).size() == __N_SENT__);

Debug.print("count: letter checks = " # Nat.toText(checks));
Debug.print("count: letters sent = " # Nat.toText(sentLetters));
Debug.print("count: placeholders resolved in both languages = " # Nat.toText(__N_PLACEHOLDERS__));
Debug.print("count: refusals = " # Nat.toText(refusals));
if (failed > 0) Runtime.trap("LETTERS RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("LETTERS GREEN");
'''


def fill_for(f):
    v = required_values(f)
    for k in ('request_date',):
        if k in v:
            v[k] = '2026-02-01'
    if 'reply_by' in v:
        v['reply_by'] = '2026-03-01'
    if 'consent_date' in v:
        v['consent_date'] = '2026-01-20'
    if 'prior_period_end' in v:
        v['prior_period_end'] = '2024-12-31'
    return v


def letters_block():
    out = []
    n = 0
    per_proc = {}
    for k, f in enumerate(LETTERS):
        fid = f['id']
        with_, proc = SENT[fid]
        per_proc[proc] = per_proc.get(proc, 0) + 1              # two templates may serve one procedure: the count is shared
        stamp = f'2026-02-01T{10 + k:02d}:00'
        addressee = 'Delta Textiles' if 'CONFIRMATION' in fid else ('Nile Legal Partners' if 'LEGAL' in fid else ('Previous & Co' if 'PREDECESSOR' in fid else 'The audit committee'))
        if fid != 'F41-CONFIRMATION-RECEIVABLE':
            out.append(f'ignore must("fill {fid}", F.save(s, ff, staff, false, {10 + k}, 1, {mo(fid)}, j({jl({"values": fill_for(f)})})));')
            out.append(f'ignore must("prepare {fid}", F.sign(s, ff, staff, {10 + k}, 1, {mo(fid)}, "prepare", "2026-02-01T{9 + k:02d}:30"));')
        out.append(f'let sent_{k} = must("send {fid}", send({mo(fid)}, {mo(with_)}, {mo(proc)}, {mo(addressee)}, {mo(stamp)}));')
        out.append('sentLetters += 1;')
        out.append(f'check("{fid}: the communication names the party, the subject and the time", field(sent_{k}, ["communication", "fields", "with"]) == #str({mo(with_)}) and field(sent_{k}, ["communication", "fields", "direction"]) == #str("sent") and field(sent_{k}, ["communication", "fields", "form"]) == #str("written") and field(sent_{k}, ["communication", "fields", "at"]) == #str({mo(stamp)}) and Text.contains(Py.textOr(field(sent_{k}, ["communication", "fields"]), "subject", ""), #text {mo(fid)}));')
        out.append(f'check("{fid}: the request names the procedure, the addressee and the due date", field(sent_{k}, ["request", "fields", "procedure"]) == #str({mo(proc)}) and field(sent_{k}, ["request", "fields", "addressee"]) == #str({mo(addressee)}) and field(sent_{k}, ["request", "fields", "state"]) == #str("open") and field(sent_{k}, ["request", "fields", "due"]) == #str("2026-03-15"));')
        out.append(f'check("{fid}: the paper counts the requests of its procedure live", field(view(staff, {mo(fid)}), ["live", "sent"]) == #num("{per_proc[proc]}"));')
        n += 1
    return '\n'.join(out), n


def main():
    block, n = letters_block()
    f41 = FORMS['F41-CONFIRMATION-RECEIVABLE']
    fill = fill_for(f41)
    fill2 = dict(fill, balance='250000.00')
    body = HEAD
    subs = {
        '__F41_PARAS__': str(len(f41['letter']['en'])), '__F41_FILL__': jl({'values': fill}), '__F41_FILL2__': jl({'values': fill2}),
        '__LETTERS__': block, '__N_SENT__': str(n + 1), '__N_PLACEHOLDERS__': str(sum(PLACEHOLDERS.values())),
    }
    for k, v in subs.items():
        assert k in body, k
        body = body.replace(k, v)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(body)
    print(f'wrote {os.path.relpath(OUT)}: {len(LETTERS)} templates, {sum(PLACEHOLDERS.values())} placeholders resolved in both languages, {n + 1} letters sent')


if __name__ == '__main__':
    main()
