#!/usr/bin/env python3
"""Generate motoko/test/AgentPull.test.mo: the connector-agent pull machine replayed against
the bodies recorded from a running thebes-agent beside a seeded self-hosted Odoo 17
(motoko/test/fixtures/agent, captured through a one-time capability). The agent already
serves the population schema, so every page's SHA-256 is its part fingerprint; the parts are
fed to the real Population module, which must accept completeness against the balances the
agent served and screen exactly as the one-call oracle does. The request URLs, the gate
(read-only, hostname, adapter, not-provided criteria), refusals, retries, a changed ledger
and the capability discipline are each checked.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import hashlib
import json
import os

HERE = os.path.dirname(__file__)
FIX = os.path.join(HERE, '..', 'motoko', 'test', 'fixtures', 'agent')
OUT = os.path.join(HERE, '..', 'motoko', 'test', 'AgentPull.test.mo')

TOKEN = 'eyJwYXlsb2FkIjp7InYiOjF9LCJhc3NlcnRpb24iOnt9fQ-CAPABILITY-TOKEN-NEVER-PERSISTED-0123456789abcdef0123456789abcdef'
PARAMS = {"PC-MANUAL": {}, "PC-SELF-APPROVED": {}, "PC-LARGE-AMOUNT": {"threshold": "250000"},
          "PC-NO-DESCRIPTION": {"min_length": 8}, "PC-KEYWORD": {"keywords": ["adjust", "reclass", "correct", "write off", "write-off", "plug", "per management", "reserve release"]},
          "PC-REVERSAL-AFTER-PERIOD": {"period_end": "2025-12-31"}, "PC-UNUSUAL-ACCOUNT": {"accounts": ["7700"]}, "PC-UNUSUAL-USER": {"users": ["cfo"]},
          "PC-ROUND-AMOUNT": {"base": "1000", "minimum": "10000"}, "PC-SELDOM-USED-ACCOUNT": {"max_entries": 3}}


def compact(o):
    return json.dumps(o, separators=(',', ':'), ensure_ascii=False, sort_keys=True)


def lit(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t') + '"'


def main():
    meta = json.load(open(os.path.join(FIX, 'meta.json')))
    host, frm, to, pl = meta['hostname'], meta['from'], meta['to'], meta['page_lines']
    bodies = {t: open(os.path.join(FIX, t.replace(':', '_') + '.body'), 'rb').read().decode('utf-8') for t in meta['requests']}
    bodies['gate'] = bodies.pop('meta')   # the machine's tag for /v1/meta
    pages = sorted(t for t in bodies if t.startswith('page:'))
    shas = [hashlib.sha256(bodies[t].encode('utf-8')).hexdigest() for t in pages]
    lines = [json.loads(bodies[t]) for t in pages]
    counts = [len(x) for x in lines]
    ids = [(int(x[0]['line_no']), int(x[-1]['line_no'])) for x in lines]
    count = int(bodies['count'])
    assert sum(counts) == count
    period = f'?from={frm}&to={to}'
    urls = {'gate': f'https://{host}/v1/meta', 'accounts': f'https://{host}/v1/accounts', 'journals': f'https://{host}/v1/journals',
            'balances': f'https://{host}/v1/balances{period}', 'count': f'https://{host}/v1/count{period}', 'recount': f'https://{host}/v1/count{period}'}
    for k in range(len(pages)):
        urls[f'page:{k}'] = f'https://{host}/v1/lines{period}&offset={k * pl}&limit={pl}'
    kept = {k: v for k, v in PARAMS.items() if k != 'PC-SELF-APPROVED'}
    begin = {"parts": shas, "lines": count, "source_sha256": hashlib.sha256(''.join(shas).encode()).hexdigest(), "params": kept,
             "trial_balance": json.loads(bodies['balances']), "places": 2}

    w = []
    w.append('// Generated by tools/gen_agent_test.py: the connector-agent pull replayed against bodies recorded')
    w.append('// from a running thebes-agent beside a seeded Odoo 17. Do not edit by hand.')
    w.append('// Attribution: Thebes Core Team. Licence: Apache 2.0.')
    for imp in ['import A "../src/AgentPull";', 'import Pop "../src/Population";', 'import Journals "../src/calc/Journals";', 'import Json "../src/Json";', 'import Py "../src/Py";',
                'import Array "mo:core/Array";', 'import List "mo:core/List";', 'import Map "mo:core/Map";', 'import Nat "mo:core/Nat";', 'import Principal "mo:core/Principal";',
                'import Text "mo:core/Text";', 'import Debug "mo:core/Debug";', 'import Runtime "mo:core/Runtime";']:
        w.append(imp)
    w.append('')
    w.append('var checks = 0;')
    w.append('var failed = 0;')
    w.append('func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };')
    w.append('func same(name : Text, got : Text, want : Text) { if (got != want) Debug.print("GOT  " # got # "\\nWANT " # want); check(name, got == want) };')
    w.append('let by = Principal.fromBlob("\\03");')
    w.append(f'let TOKEN = {lit(TOKEN)};')
    w.append(f'let HOST = {lit(host)};')
    w.append(f'let BEGIN = {lit(compact({"agent": 1, "token": TOKEN, "from": frm, "to": to, "params": PARAMS, "page_lines": pl, "window": 2}))};')
    w.append('func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(m)) Runtime.trap(m) } };')
    w.append('')
    for tag, body in bodies.items():
        w.append(f'let B_{tag.replace(":", "_").upper()} = {lit(body)};')
    w.append('func body(tag : Text) : Text {')
    w.append('  switch (tag) {')
    for tag in bodies:
        w.append(f'    case {lit(tag)} B_{tag.replace(":", "_").upper()};')
    w.append('    case "recount" B_COUNT;')
    w.append('    case _ Runtime.trap("no body for " # tag);')
    w.append('  }')
    w.append('};')
    w.append('let URLS : [(Text, Text)] = [' + ', '.join(f'({lit(t)}, {lit(u)})' for t, u in urls.items()) + '];')
    w.append(f'let PART_SHAS : [Text] = [{", ".join(lit(x) for x in shas)}];')
    w.append(f'let PART_LINES : [Nat] = [{", ".join(str(c) for c in counts)}];')
    w.append(f'let PART_IDS : [(Nat, Nat)] = [{", ".join("(%d, %d)" % x for x in ids)}];')
    w.append(f'let SOURCE_SHA = {lit(begin["source_sha256"])};')
    w.append(f'let BEGIN_JSON = {lit(compact(begin))};')
    w.append('''
func expected(tag : Text) : Text {
  switch (Array.find<(Text, Text)>(URLS, func(r) { r.0 == tag })) { case (?r) r.1; case null Runtime.trap("no expected url " # tag) }
};
func hasToken(t : Text) : Bool { Text.contains(t, #text TOKEN) };
func begin(s : A.State, json : Text) : { #ok : A.Pull; #err : Text } { A.begin(s, by, 1, 7, 1, HOST, "odoo-rpc", j(json)) };

type Delivery = { #reply : (Nat, Text); #lost : Text; #hold };
func drive(s : A.State, p : A.Pull, deliver : (Text, Nat) -> Delivery, shuffle : Bool) : Nat {
  var at : Int = 1_000_000_000;
  var rounds = 0;
  var handle : Int64 = 1;
  var held = Map.empty<Text, Nat>();
  label run while (rounds < 400) {
    rounds += 1;
    let tags = A.advance(s, p, at);
    if (p.status == "ready" or p.status == "failed" or p.status == "done") break run;
    for (t in tags.vals()) {
      switch (A.requestFor(p, t)) {
        case (?r) {
          same("request " # t # " url", r.url, expected(t));
          check("request " # t # " carries no token", not hasToken(r.url));
          A.submitted(p, t, handle, at);
          handle += 1;
        };
        case null { failed += 1; Debug.print("FAIL no request for " # t) };
      };
    };
    var inflight = Array.fromIter<Text>(Map.keys(p.inflight));
    if (shuffle) inflight := Array.reverse<Text>(inflight);
    at += 1_000_000_000;
    for (t in inflight.vals()) {
      let n = switch (Map.get(held, Text.compare, t)) { case (?v) v; case null 0 };
      switch (deliver(t, n)) {
        case (#reply((st, b))) ignore A.landed(s, p, t, st, b, at);
        case (#lost(why)) ignore A.failed(p, t, why);
        case (#hold) Map.add(held, Text.compare, t, n + 1);
      };
    };
    if (tags.size() == 0 and inflight.size() == 0 and List.size(p.queue) == 0) break run;
  };
  rounds
};
func recorded(tag : Text, _n : Nat) : Delivery { #reply((200, body(tag))) };
func patched(patch : [(Text, Json.J)]) : Text {
  switch (j(BEGIN)) {
    case (#obj(kvs)) {
      var out : [(Text, Json.J)] = [];
      for ((k, v) in kvs.vals()) { switch (Array.find<(Text, Json.J)>(patch, func(x) { x.0 == k })) { case (?x) out := Array.concat(out, [x]); case null out := Array.concat(out, [(k, v)]) } };
      Json.toText(#obj(out))
    };
    case _ Runtime.trap("BEGIN");
  }
};

// ------------------------------------------------------------------ refusals at begin
do {
  let s = A.init();
  func refused(name : Text, json : Text, why : Text) {
    switch (begin(s, json)) { case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": accepted") }; case (#err(m)) same(name, m, why) }
  };
  refused("token missing", patched([("token", #str(""))]), "token is required: the capability the client's browser minted for this pull");
  refused("from after to", patched([("from", #str("2027-01-01"))]), "from must not be after to");
  refused("no criteria", patched([("params", #obj([]))]), "choose at least one criterion");
  refused("page_lines too large", patched([("page_lines", Json.nat(900))]), "page_lines is 50 to 500");
  check("hostname: bad char", A.hostnameProblem("Agent_1.connect.test") != null);
  check("hostname: not qualified", A.hostnameProblem("localhost") != null);
  check("hostname: ok", A.hostnameProblem("k7q2m.connect.mercaturaforum.com") == null);
  check("url: not allowlisted", A.url(HOST, "/v1/admin") == null);
  check("url: allowlisted", A.url(HOST, "/v1/meta") == ?("https://" # HOST # "/v1/meta"));
  check("a registration on a bad hostname is refused at begin", switch (A.begin(s, by, 1, 7, 1, "bad host", "odoo-rpc", j(BEGIN))) { case (#err(m)) Text.contains(m, #text "hostname"); case _ false });
};

// ------------------------------------------------------------------ the recorded pull, ordered and shuffled
func fullPull(shuffle : Bool) : (A.State, A.Pull) {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  let label_ = if (shuffle) "shuffled: " else "ordered: ";
  check(label_ # "a second pull is refused while one runs", switch (begin(s, BEGIN)) { case (#err(m)) m == "pull 1 is still running; wait for it to finish"; case _ false });
  check(label_ # "the view never shows the token", not hasToken(Json.toText(A.view(p))));
  let rounds = drive(s, p, recorded, shuffle);
  same(label_ # "status", p.status # " " # p.failure, "ready ");
  check(label_ # "rounds bounded", rounds < 40);
  check(label_ # "read-only confirmed from meta", p.writeAccess == ?false);
  check(label_ # "the gate dropped the not-provided criterion", Array.equal<Text>(p.notAssessable, ["PC-SELF-APPROVED"], Text.equal) and p.params.size() == 9);
  check(label_ # "system named from meta", p.systemName == "Odoo" and p.systemVersion == "17.0");
  check(label_ # "pages", List.size(p.pages) == PART_SHAS.size());
  for (i in PART_SHAS.keys()) {
    if (i < List.size(p.pages)) {
      let pg = List.at(p.pages, i);
      same(label_ # "part " # Nat.toText(i) # " fingerprint is the page's SHA-256", pg.partSha, PART_SHAS[i]);
      check(label_ # "part " # Nat.toText(i) # " lines", pg.lines == PART_LINES[i]);
      check(label_ # "part " # Nat.toText(i) # " ids", pg.firstId == PART_IDS[i].0 and pg.lastId == PART_IDS[i].1);
      switch (A.partText(s, p, i)) { case (#ok(t)) same(label_ # "part " # Nat.toText(i) # " text is the agreed body", t, body("page:" # Nat.toText(i))); case (#err(m)) { failed += 1; Debug.print("FAIL part text " # m) } };
    };
  };
  same(label_ # "source fingerprint", A.sourceSha(p), SOURCE_SHA);
  same(label_ # "begin input", Json.toText(A.beginJson(p)), BEGIN_JSON);
  check(label_ # "metadata kept by tag", Array.equal<Text>(A.metaTags(p), ["accounts", "balances", "gate", "journals"], Text.equal));
  (s, p)
};
do { ignore fullPull(true) };
do {
  let (s, p) = fullPull(false);
  let pops = Pop.init();
  let pop = switch (Pop.begin(pops, by, 3, 7, A.beginJson(p))) { case (#ok(v)) Py.natOr(v, "id", 0); case (#err(m)) Runtime.trap("begin: " # m) };
  var all : [Json.J] = [];
  for (i in Nat.range(0, List.size(p.pages))) {
    let t = switch (A.partText(s, p, i)) { case (#ok(t)) t; case (#err(m)) Runtime.trap(m) };
    switch (Pop.putPart(pops, by, pop, i, t)) { case (#ok(_)) {}; case (#err(m)) { failed += 1; Debug.print("FAIL putPart " # Nat.toText(i) # ": " # m) } };
    all := Array.concat(all, Py.items(j(t)));
  };
  let c = switch (Pop.seal(pops, pop)) { case (#ok(c)) c; case (#err(m)) Runtime.trap("seal: " # m) };
  check("completeness accepted against the balances the agent served", Py.truthy(Json.get(c, "accepted")));
  let oracleC = switch (Journals.completeness(#obj([("lines", #arr(all)), ("trial_balance", #arr(p.balances)), ("places", Json.nat(2))]))) { case (#ok(v)) v; case (#err(m)) Runtime.trap(m) };
  same("completeness equals the one-call oracle", Json.toText(c), Json.toText(oracleC));
  var steps = 0;
  label screen while (steps < 400) { steps += 1; let v = switch (Pop.step(pops, pop, 200)) { case (#ok(v)) v; case (#err(m)) Runtime.trap(m) }; if (Py.textOr(v, "status", "") == "screened") break screen };
  let pp = switch (Pop.get(pops, pop)) { case (?x) x; case null Runtime.trap("pop") };
  let oracleS = switch (Journals.screen(#obj([("lines", #arr(all)), ("params", #obj(p.params))]))) { case (#ok(v)) v; case (#err(m)) Runtime.trap(m) };
  same("screen equals the one-call oracle", Json.toText(Pop.fullOutput(pops, pp)), Json.toText(oracleS));
  check("eighteen entries flagged (the seeded plants)", pp.flagged == 18);
  p.popId := pop;
  let (input, output) = A.paper(p);
  check("paper input carries no token and names route A", not hasToken(Json.toText(input)) and Text.contains(Json.toText(input), #text "route"));
  check("paper output carries no token", not hasToken(Json.toText(output)));
  A.finish(p);
  same("token overwritten at the end", p.key, "");
  check("after the pull a new one may begin", switch (begin(s, BEGIN)) { case (#ok(q)) q.id == 2 and not p.pagesKept; case (#err(_)) false });
};

// ------------------------------------------------------------------ the gate
func gateBody(patch : [(Text, Json.J)]) : Text {
  switch (j(B_GATE)) {
    case (#obj(kvs)) {
      var out : [(Text, Json.J)] = [];
      for ((k, v) in kvs.vals()) { switch (Array.find<(Text, Json.J)>(patch, func(x) { x.0 == k })) { case (?x) out := Array.concat(out, [x]); case null out := Array.concat(out, [(k, v)]) } };
      Json.toText(#obj(out))
    };
    case _ Runtime.trap("gate");
  }
};
do {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "gate") #reply((200, gateBody([("read_only", #bool(false))]))) else #reply((200, body(t))) }, false);
  check("an agent that is not read-only ends the pull", p.status == "failed" and Text.contains(p.failure, #text "not read-only"));
  same("gate: token overwritten", p.key, "");
};
do {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "gate") #reply((200, gateBody([("hostname", #str("other.connect.test"))]))) else #reply((200, body(t))) }, false);
  check("an agent naming another hostname ends the pull", p.status == "failed" and Text.contains(p.failure, #text "another hostname"));
};
do {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "gate") #reply((200, gateBody([("adapter", #str("tally-xml"))]))) else #reply((200, body(t))) }, false);
  check("an agent running another adapter than registered ends the pull", p.status == "failed" and Text.contains(p.failure, #text "another adapter"));
};
do {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "gate") #reply((401, "{\\"detail\\":\\"the capability expired\\"}")) else #reply((200, body(t))) }, false);
  check("a refused capability ends the pull", p.status == "failed" and Text.startsWith(p.failure, #text "the agent refused the capability (HTTP 401)"));
  same("401: token overwritten", p.key, "");
};

// ------------------------------------------------------------------ a ledger that changes, retries
do {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "recount") #reply((200, "2002")) else #reply((200, body(t))) }, false);
  check("a changed count is refused", p.status == "failed" and Text.contains(p.failure, #text "the ledger changed during the pull: 2002 lines now"));
};
do {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "page:1") #reply((200, body("page:0"))) else #reply((200, body(t))) }, false);
  check("an overlapping page is refused", p.status == "failed" and Text.contains(p.failure, #text "page 1 overlaps the previous page"));
};
do {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "page:0") #reply((200, "[{\\"entry_id\\":\\"x\\"}]")) else #reply((200, body(t))) }, false);
  check("a page lacking required fields is refused", p.status == "failed" and Text.contains(p.failure, #text "lacks"));
};
do {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  var tries = 0;
  ignore drive(s, p, func(t, _) { if (t == "page:2" and tries < 2) { tries += 1; #reply((503, "busy")) } else #reply((200, body(t))) }, false);
  check("a page refused twice is retried and completes", p.status == "ready" and tries == 2);
};
do {
  let s = A.init();
  let p = switch (begin(s, BEGIN)) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "balances") #lost("no agreement among the validators within the deadline") else #reply((200, body(t))) }, false);
  check("a request without agreement ends the pull after the retries", p.status == "failed" and Text.contains(p.failure, #text "(balances, after 2 retries)"));
};
''')
    w.append('Debug.print("count: checks = " # Nat.toText(checks));')
    w.append('if (failed > 0) Runtime.trap("agent pull: " # Nat.toText(failed) # " checks failed");')
    w.append('Debug.print("AGENT GREEN");')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(w) + '\n')
    print(OUT, len(pages), 'pages', count, 'lines')


if __name__ == '__main__':
    main()
