#!/usr/bin/env python3
"""Generate motoko/test/Steps.test.mo: programme steps at requirement granularity.

Every cycle working paper's procedure section carries one step per requirement the
procedure discharges (the model's procedure_requirements table), each with its own
conclusion, the evidence links citing the step and their tick marks, and, when an exception
is noted, the record it cites. The expected steps of the revenue paper are read here from the
model, never typed; an evidence link naming a step counts on that step alone; a step
concluded with an exception cannot be prepared without citing a misstatement, a review note
or a communication of the file, and a citation of a record the file does not hold is refused.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
STD = os.environ.get('AUDIT_STANDARDS', '../thebes-audit-standards')
OUT = os.path.join(ROOT, 'motoko', 'test', 'Steps.test.mo')
sys.path.insert(0, HERE)
from gen_graph_test import load_forms, required_values, mo  # noqa: E402

S = lambda name: json.load(open(os.path.join(STD, 'seed', name + '.json'), encoding='utf-8'))
LINKS = S('procedure_requirements')
FORMS = load_forms()
PAPER = 'F31-REVENUE-RECEIVABLES'
F31 = FORMS[PAPER]
assert F31.get('version') == 3, F31.get('version')
PROCS = F31['procedures']
STEPS = {pid: [l['requirement_id'] for l in LINKS if l['procedure_id'] == pid] for pid in PROCS}
FIELDS = {fd['id']: fd for s_ in F31['sections'] for fd in s_['fields']}
for pid, reqs in STEPS.items():
    key = pid.lower().replace('-', '_')
    for n, rid in enumerate(reqs, 1):
        fd = FIELDS[f'{key}_s{n}_conclusion']
        assert fd['step'] == rid and fd['required'] and fd['type'] == 'select', (pid, n)
        assert FIELDS[f'{key}_s{n}_evidence']['autofill'] == f'records.RK-EVIDENCE-LINK.for.{pid}.step.{rid}'
        assert FIELDS[f'{key}_s{n}_citation']['required_if']['field'] == f'{key}_s{n}_conclusion'
N_STEPS = sum(len(v) for v in STEPS.values())
FIRST = PROCS[0]
FIRST_KEY = FIRST.lower().replace('-', '_')
FIRST_REQ = STEPS[FIRST][0]
FILL = required_values(F31)
TICK = S('tick_marks')[0]['id']


def jl(obj):
    return mo(json.dumps(obj, ensure_ascii=False, separators=(',', ':')))


HEAD = r'''// GENERATED by tools/gen_steps_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import F "../src/Forms";
import FF "../src/FirmForms";
import Json "../src/Json";
import Py "../src/Py";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let staff = Principal.fromBlob("\04");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func idOf(v : Json.J) : Nat { Py.natOr(v, "id", 0) };
func view(who : Principal, form : Text) : Json.J {
  switch (F.view(s, ff, who, false, 1, form)) { case (#ok(v)) v; case (#err(m)) { checks += 1; failed += 1; Debug.print("FAIL view " # form # ": " # m); #null_ } };
};
func stepFields(def : Json.J) : Nat { var n = 0; for (sec in Py.list(def, "sections").vals()) { for (f in Py.list(sec, "fields").vals()) { if (Py.textOr(f, "step", "") != "") n += 1 } }; n };

// the engagement and its team
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Nile Trading SAE\",\"framework\":\"EAS\",\"audit_standard\":\"EAS\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (senior, "senior"), (staff, "staff")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));

// the steps come from the model's procedure requirements
let v0 = view(staff, "__PAPER__");
check("the revenue paper is at version 3", field(v0, ["form", "version"]) == #num("3"));
check("its steps are the procedure requirements of the model, one per link", stepFields(field(v0, ["form"])) == __N_STEPS__);
check("the first step of the first procedure names its requirement", (func() : Bool {
  for (sec in Py.list(field(v0, ["form"]), "sections").vals()) { for (f in Py.list(sec, "fields").vals()) { if (Py.textOr(f, "id", "") == "__FIRST_KEY___s1_conclusion") return Py.textOr(f, "step", "") == "__FIRST_REQ__" } };
  false
})());

// evidence linked to a step counts on that step alone; the tick mark shows
ignore must("link evidence to the first step", E.addRecord(s, staff, false, 3, 1, j("{\"kind\":\"RK-EVIDENCE-LINK\",\"fields\":{\"procedure\":\"__FIRST__\",\"step\":\"__FIRST_REQ__\",\"evidence_item\":\"doc:1\",\"evidence_kind\":\"EK-CONFIRMATION-REPLY\",\"tick_mark\":\"__TICK__\",\"linked_by\":\"staff\",\"linked_at\":\"2026-02-01T09:00\"}}")));
ignore must("link evidence to the procedure without a step", E.addRecord(s, staff, false, 3, 1, j("{\"kind\":\"RK-EVIDENCE-LINK\",\"fields\":{\"procedure\":\"__FIRST__\",\"evidence_item\":\"doc:2\",\"evidence_kind\":\"EK-CONFIRMATION-REPLY\",\"linked_by\":\"staff\",\"linked_at\":\"2026-02-01T09:10\"}}")));
let v1 = view(staff, "__PAPER__");
check("the step counts the link that names it", field(v1, ["live", "__FIRST_KEY___s1_evidence"]) == #num("1"));
check("the step shows the tick mark of its evidence", field(v1, ["live", "__FIRST_KEY___s1_ticks"]) == #str("__TICK__"));
check("the procedure counts both links", field(v1, ["live", "__FIRST_KEY___evidence"]) == #num("2"));
check("a second step of the same procedure counts nothing", field(v1, ["live", "__FIRST_KEY___s2_evidence"]) == #num("0") or Json.get(field(v1, ["live"]), "__FIRST_KEY___s2_evidence") == null);

// the paper is prepared with every step concluded
ignore must("fill the revenue paper", F.save(s, ff, staff, false, 4, 1, "__PAPER__", j(__FILL__)));
ignore must("prepare the revenue paper", F.sign(s, ff, staff, 5, 1, "__PAPER__", "prepare", "2026-02-02T09:00"));
check("the step's evidence count and tick marks are frozen with the paper", field(view(manager, "__PAPER__"), ["frozen", "__FIRST_KEY___s1_evidence"]) == #num("1") and field(view(manager, "__PAPER__"), ["frozen", "__FIRST_KEY___s1_ticks"]) == #str("__TICK__"));

// a step concluded with an exception cites the record it raised
ignore must("the partner reopens the paper", F.reopen(s, partner, false, 6, 1, "__PAPER__", "an exception on the first step"));
ignore must("conclude the first step with an exception", F.save(s, ff, staff, false, 7, 1, "__PAPER__", j(__FILL_EXCEPTION__)));
refused("an exception without a citation is not prepared", F.sign(s, ff, staff, 8, 1, "__PAPER__", "prepare", "2026-02-03T09:00"), "cites the misstatement, review note or communication");
ignore must("cite a record the file does not hold", F.save(s, ff, staff, false, 9, 1, "__PAPER__", j(__FILL_BAD_CITE__)));
refused("a citation of a record the file does not hold is refused", F.sign(s, ff, staff, 10, 1, "__PAPER__", "prepare", "2026-02-03T09:00"), "cites no RK-MISSTATEMENT, RK-REVIEW-NOTE, RK-COMMUNICATION record");
let note = idOf(must("raise a review note on the step", E.addRecord(s, manager, false, 11, 1, j("{\"kind\":\"RK-REVIEW-NOTE\",\"fields\":{\"object\":\"engagement:1/__PAPER__\",\"raised_by\":\"manager\",\"raised_at\":\"2026-02-03T08:00\",\"text\":\"Cut-off exception on the December shipments\",\"state\":\"open\"}}"))));
ignore must("cite the review note", F.save(s, ff, staff, false, 12, 1, "__PAPER__", j(Text.replace(__FILL_CITE__, #text "__NOTE__", Nat.toText(note)))));
ignore must("with the citation the paper is prepared", F.sign(s, ff, staff, 13, 1, "__PAPER__", "prepare", "2026-02-03T10:00"));
check("the citation is the note's id", field(view(manager, "__PAPER__"), ["values", "__FIRST_KEY___s1_citation"]) == #str(Nat.toText(note)));

Debug.print("count: step checks = " # Nat.toText(checks));
Debug.print("count: steps on the revenue paper = " # Nat.toText(__N_STEPS__));
Debug.print("count: refusals = " # Nat.toText(refusals));
if (failed > 0) Runtime.trap("STEPS RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("STEPS GREEN");
'''


def main():
    fill_exc = dict(FILL, **{f'{FIRST_KEY}_s1_conclusion': 'performed_exception'})
    fill_bad = dict(fill_exc, **{f'{FIRST_KEY}_s1_citation': '999999'})
    fill_cite = dict(fill_exc, **{f'{FIRST_KEY}_s1_citation': '__NOTE__'})
    body = HEAD
    subs = {
        '__PAPER__': PAPER, '__N_STEPS__': str(N_STEPS), '__FIRST__': FIRST, '__FIRST_KEY__': FIRST_KEY, '__FIRST_REQ__': FIRST_REQ, '__TICK__': TICK,
        '__FILL__': jl({'values': FILL}), '__FILL_EXCEPTION__': jl({'values': fill_exc}), '__FILL_BAD_CITE__': jl({'values': fill_bad}), '__FILL_CITE__': jl({'values': fill_cite}),
    }
    for k, v in subs.items():
        assert k in body, k
        body = body.replace(k, v)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(body)
    print(f'wrote {os.path.relpath(OUT)}: {N_STEPS} steps over {len(PROCS)} procedures of {PAPER}, first step {FIRST} / {FIRST_REQ}')


if __name__ == '__main__':
    main()
