#!/usr/bin/env python3
"""Generate motoko/src/Seed.mo: the auditing-standards model (seed/*.json of
thebes-audit-standards) embedded in the canister, one JSON document per table, in
the source order of each file. The generated module records the commit it was
built from, so a canister can state which edition of the model it carries.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import glob, json, os, subprocess

STD = os.environ.get('AUDIT_STANDARDS', os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'thebes-audit-standards'))
OUT = os.path.join(os.path.dirname(__file__), '..', 'motoko', 'src', 'Seed.mo')


def mo(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif o < 32 or o == 127:
            out.append('\\u{%x}' % o)
        else:
            out.append(ch)
    return '"' + ''.join(out) + '"'


def main():
    commit = subprocess.run(['git', '-C', STD, 'rev-parse', 'HEAD'], capture_output=True, text=True).stdout.strip()
    dirty = subprocess.run(['git', '-C', STD, 'status', '--porcelain', 'seed'], capture_output=True, text=True).stdout.strip()
    if dirty:
        raise SystemExit('seed/ has uncommitted changes; commit them so the embedded edition is identifiable')
    tables = []
    for f in sorted(glob.glob(os.path.join(STD, 'seed', '*.json'))):
        rows = json.load(open(f, encoding='utf-8'))
        tables.append((os.path.basename(f)[:-5], json.dumps(rows, ensure_ascii=False, separators=(',', ':')), len(rows)))
    # adapter profiles, one table each, named "profile:<id>"; row count 1
    for f in sorted(glob.glob(os.path.join(STD, 'adapters', 'profiles', '*.json'))):
        prof = json.load(open(f, encoding='utf-8'))
        tables.append(('profile:' + prof['id'], json.dumps(prof, ensure_ascii=False, separators=(',', ':')), 1))
    lines = ['// GENERATED by tools/gen_seed.py from thebes-audit-standards/seed. Do not edit.',
             '// Attribution: Thebes Core Team. Licence: Apache 2.0.', '',
             'module {',
             f'  /// thebes-audit-standards commit the tables were taken from.',
             f'  public let SOURCE_COMMIT : Text = "{commit}";',
             '',
             '  /// (table, row count, canonical JSON array in source order)',
             '  public let TABLES : [(Text, Nat, Text)] = [']
    for name, text, n in tables:
        lines.append(f'    ("{name}", {n}, {mo(text)}),')
    lines += ['  ];', '',
              '  public func table(name : Text) : ?Text {',
              '    for ((k, _, v) in TABLES.vals()) { if (k == name) return ?v };',
              '    null',
              '  };',
              '};']
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')
    print(f'wrote {len(tables)} tables ({sum(n for _, _, n in tables)} rows, {sum(len(t.encode()) for _, t, _ in tables)} bytes) from {commit[:9]}')


if __name__ == '__main__':
    main()
