#!/usr/bin/env python3
"""Generate motoko/test/RouteB.test.mo from a real agent export (motoko/test/fixtures/routeb):
the manifest verifies under the registered key and reads back exactly; every tamper is
refused (flipped signature, another key, an edited manifest, a wrong fingerprint, a part
that is not a manifest page, a trial balance that is not the exported balances); the
not-provided criterion is dropped; the real pages add up to the signed control totals.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import base64
import hashlib
import json
import os

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec

HERE = os.path.dirname(__file__)
FIX = os.path.join(HERE, '..', 'motoko', 'test', 'fixtures', 'routeb')
OUT = os.path.join(HERE, '..', 'motoko', 'test', 'RouteB.test.mo')


def lit(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t') + '"'


def main():
    manifest = open(os.path.join(FIX, 'manifest.json'), encoding='utf-8').read()
    sig = open(os.path.join(FIX, 'manifest.sig')).read().strip()
    spki = open(os.path.join(FIX, 'manifest.spki')).read().strip()
    balances = open(os.path.join(FIX, 'balances.json'), encoding='utf-8').read()
    m = json.loads(manifest)
    fp = hashlib.sha256(base64.b64decode(spki)).hexdigest()
    assert fp == m['spki_fingerprint']
    pages = [open(os.path.join(FIX, f'page-{i:04}.json'), encoding='utf-8').read() for i in range(len(m['pages']))]
    for i, p in enumerate(pages):
        assert hashlib.sha256(p.encode()).hexdigest() == m['pages'][i]['sha256']
    # another key signing the same manifest
    other = ec.generate_private_key(ec.SECP256R1())
    other_sig = base64.urlsafe_b64encode(other.sign(manifest.encode(), ec.ECDSA(hashes.SHA256()))).rstrip(b'=').decode()
    other_spki = base64.b64encode(other.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)).decode()
    other_fp = hashlib.sha256(base64.b64decode(other_spki)).hexdigest()
    flipped = list(sig)
    flipped[10] = 'A' if flipped[10] != 'A' else 'B'
    begin = {'parts': [p['sha256'] for p in m['pages']], 'lines': m['lines'], 'source_sha256': hashlib.sha256(manifest.encode()).hexdigest(),
             'params': {'PC-MANUAL': {}, 'PC-SELF-APPROVED': {}, 'PC-LARGE-AMOUNT': {'threshold': '250000'}}, 'trial_balance': json.loads(balances), 'places': m['places']}
    w = ['// Generated by tools/gen_routeb_test.py from a real agent export. Do not edit by hand.',
         '// Attribution: Thebes Core Team. Licence: Apache 2.0.',
         'import R "../src/RouteB";', 'import Dec "../src/Dec";', 'import Json "../src/Json";', 'import Py "../src/Py";',
         'import Array "mo:core/Array";', 'import Nat "mo:core/Nat";', 'import Text "mo:core/Text";', 'import Debug "mo:core/Debug";', 'import Runtime "mo:core/Runtime";', '',
         'var checks = 0;', 'var failed = 0;',
         'func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };',
         'func refused(name : Text, r : { #ok : R.Manifest; #err : Text }, why : Text) { switch (r) { case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": accepted") }; case (#err(m)) { if (not Text.contains(m, #text why)) Debug.print("GOT " # m); check(name, Text.contains(m, #text why)) } } };',
         'func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(m)) Runtime.trap(m) } };',
         f'let MANIFEST = {lit(manifest)};', f'let SIG = {lit(sig)};', f'let SPKI = {lit(spki)};', f'let FP = {lit(fp)};',
         f'let OTHER_SIG = {lit(other_sig)};', f'let OTHER_SPKI = {lit(other_spki)};', f'let OTHER_FP = {lit(other_fp)};', f'let FLIPPED = {lit("".join(flipped))};',
         f'let BALANCES = {lit(balances)};', f'let BEGIN = {lit(json.dumps(begin, separators=(",", ":"), sort_keys=True))};',
         f'let PAGES : [Text] = [{", ".join(lit(p) for p in pages)}];']
    w.append(f'''
do {{
  let m = switch (R.verify(MANIFEST, SIG, SPKI, FP)) {{ case (#ok(m)) m; case (#err(e)) Runtime.trap(e) }};
  check("the manifest verifies under the registered key", true);
  check("agent and adapter read back", m.agent == {lit(m['agent'])} and m.adapter == {lit(m['adapter'])} and m.systemName == {lit(m['system'])});
  check("pages read back", m.pages.size() == {len(pages)} and m.lines == {m['lines']} and m.pages[0].0 == {lit(m['pages'][0]['sha256'])});
  check("control totals read back", m.controlEntries == {m['control_totals']['entries']} and Dec.toText(m.controlDebit) == {lit(m['control_totals']['debit'])});
  check("the not-provided field is carried", m.notProvided.size() == 1 and m.notProvided[0].1 == "PC-SELF-APPROVED");
  check("the manifest's own hash", m.manifestSha == {lit(hashlib.sha256(manifest.encode()).hexdigest())});
  check("the import matches the manifest", R.matches(m, j(BEGIN)) == null);
  let (kept, dropped) = R.assessable([("PC-MANUAL", #obj([])), ("PC-SELF-APPROVED", #obj([])), ("PC-LARGE-AMOUNT", #obj([]))], m);
  check("the not-provided criterion is dropped", kept.size() == 2 and Array.equal<Text>(dropped, ["PC-SELF-APPROVED"], Text.equal));
  var d = Dec.zero; var c = Dec.zero;
  for (p in PAGES.vals()) {{ switch (R.partSums(p)) {{ case (#ok((pd, pc))) {{ d := Dec.add(d, pd, Dec.PREC); c := Dec.add(c, pc, Dec.PREC) }}; case (#err(e)) Runtime.trap(e) }} }};
  check("the real pages add up to the signed control totals", Dec.eq(Dec.money(d, 2), m.controlDebit) and Dec.eq(Dec.money(c, 2), m.controlCredit));
  // tampers
  refused("a flipped signature", R.verify(MANIFEST, FLIPPED, SPKI, FP), "does not verify");
  refused("another key, registered fingerprint unchanged", R.verify(MANIFEST, OTHER_SIG, OTHER_SPKI, FP), "not the registered agent key");
  refused("another key even when it is the registered one: the manifest names the agent key", R.verify(MANIFEST, OTHER_SIG, OTHER_SPKI, OTHER_FP), "names another key");
  refused("an edited manifest", R.verify(Text.replace(MANIFEST, #text "\\"lines\\":{m['lines']}", "\\"lines\\":{m['lines'] + 1}"), SIG, SPKI, FP), "does not verify");
  refused("a garbage signature", R.verify(MANIFEST, "!!!", SPKI, FP), "not base64");
  // the import must be exactly the manifest's pages and balances
  switch (j(BEGIN)) {{
    case (#obj(kvs)) {{
      let wrongPart = #obj(Array.map<(Text, Json.J), (Text, Json.J)>(kvs, func(kv) {{ if (kv.0 == "parts") ("parts", #arr(Array.tabulate<Json.J>({len(pages)}, func(i) {{ if (i == 1) #str({lit("0" * 64)}) else Py.items(Py.optJ(Json.get(j(BEGIN), "parts")))[i] }}))) else kv }}));
      check("a part that is not a manifest page is refused", switch (R.matches(m, wrongPart)) {{ case (?e) Text.contains(e, #text "part 1 is not"); case null false }});
      let wrongTb = #obj(Array.map<(Text, Json.J), (Text, Json.J)>(kvs, func(kv) {{ if (kv.0 == "trial_balance") ("trial_balance", #arr([])) else kv }}));
      check("a trial balance that is not the exported balances is refused", switch (R.matches(m, wrongTb)) {{ case (?e) Text.contains(e, #text "fingerprint differs"); case null false }});
      let wrongLines = #obj(Array.map<(Text, Json.J), (Text, Json.J)>(kvs, func(kv) {{ if (kv.0 == "lines") ("lines", Json.nat(5)) else kv }}));
      check("a different line count is refused", R.matches(m, wrongLines) != null);
    }};
    case _ Runtime.trap("BEGIN");
  }};
}};
Debug.print("count: checks = " # Nat.toText(checks));
if (failed > 0) Runtime.trap("route b: " # Nat.toText(failed) # " checks failed");
Debug.print("ROUTEB GREEN");''')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(w) + '\n')
    print(OUT, len(pages), 'pages')


if __name__ == '__main__':
    main()
