#!/usr/bin/env python3
"""Generate motoko/test/JsonRoundtrip.test.mo. Python json is the oracle for src/Json.mo:
each case is a source document in some formatting, and the Motoko parser + canonical
writer must print exactly json.dumps(v, sort_keys=True, separators=(',', ':'), ensure_ascii=False).

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import glob, json, os

STD = os.environ.get('AUDIT_STANDARDS', os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'thebes-audit-standards'))
OUT = os.path.join(os.path.dirname(__file__), '..', 'motoko', 'test', 'JsonRoundtrip.test.mo')


def canon(v):
    return json.dumps(v, sort_keys=True, separators=(',', ':'), ensure_ascii=False)


def mo(s):
    """A Motoko text literal for s."""
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif o < 32 or o == 127:
            out.append('\\u{%x}' % o)
        else:
            out.append(ch)
    return '"' + ''.join(out) + '"'


def main():
    docs = []
    files = sorted(glob.glob(STD + '/computations/vectors/*.json'))
    files += [STD + '/seed/leadsheets.json', STD + '/seed/record_kinds.json', STD + '/seed/cycles.json']
    for f in files:
        docs.append(json.load(open(f, encoding='utf-8')))
    docs.append({'q': 'quote " back \\ slash / tab\t nl\n cr\r bs\b ff\f nul\x00 us\x1f del\x7f',
                 'ar': 'مراجعة الحسابات', 'emoji': '\U0001F600', 'e': [], 'o': {}})
    docs.append({'b': [True, False, None], 'ints': [0, -1, 42, 123456789012345678901234567890],
                 'z': {'b': 1, 'a': 2, 'B': 3, '_': 4, 'é': 5, 'ب': 6}})
    cases = []
    for v in docs:
        want = canon(v)
        cases.append((json.dumps(v, indent=2, ensure_ascii=False), want))   # pretty, raw unicode
        cases.append((json.dumps(v, ensure_ascii=True), want))              # \u escapes, surrogate pairs
    bad = ['', '{', '[1,]', '{"a" 1}', 'tru', '"unterminated', '01', '1.', '[1] x', '"\\ud800"', '{"a":1,}', '[\x01]']
    lines = ['// GENERATED by tools/gen_json_cases.py from Python json. Do not edit.',
             '// Attribution: Thebes Core Team. Licence: Apache 2.0.',
             'import Json "../src/Json";', 'import Nat "mo:core/Nat";',
             'import Debug "mo:core/Debug";', 'import Runtime "mo:core/Runtime";', '',
             'let cases : [(Text, Text)] = [']
    lines += [f'  ({mo(s)}, {mo(w)}),' for s, w in cases]
    lines += ['];', 'let bad : [Text] = [' + ', '.join(mo(b) for b in bad) + '];', '',
              'var passed = 0;', 'var failed = 0;',
              'for ((src, want) in cases.vals()) {',
              '  switch (Json.parse(src)) {',
              '    case (#ok(j)) { let got = Json.toText(j); if (got == want) passed += 1 else { failed += 1; if (failed <= 5) Debug.print("FAIL want=" # want # " got=" # got) } };',
              '    case (#err(e)) { failed += 1; Debug.print("FAIL parse error " # e) };',
              '  }',
              '};',
              'var rejected = 0;',
              'for (b in bad.vals()) { switch (Json.parse(b)) { case (#err(_)) rejected += 1; case (#ok(_)) Debug.print("FAIL accepted malformed: " # b) } };',
              'Debug.print("count: json documents round-tripped = " # Nat.toText(passed));',
              'Debug.print("count: malformed documents rejected = " # Nat.toText(rejected));',
              'if (failed > 0 or rejected != bad.size()) Runtime.trap("JSON RED");',
              'Debug.print("JSON GREEN");']
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'wrote {len(cases)} round-trip cases and {len(bad)} malformed cases')


if __name__ == '__main__':
    main()
