#!/usr/bin/env python3
"""Generate motoko/test/FormGraph.test.mo: one case per edge of forms/GRAPH.json. For an
edge whose downstream field reads a live source, the case sets the upstream (a value saved
on the source form, a paper computed, a record added, a trial balance imported), prepares the
downstream form, changes the upstream, and observes the downstream view listing exactly
that field as drifted with the edge's source node named. For a declared edge (a link the
fourteen carry in prose), the case prepares the downstream, reopens the upstream, and
observes the downstream's upstream list naming the source form as unsigned.

The engagement is set up once (a trial balance, the materiality paper); every downstream
form is filled from its definition with a value per required field, so preparing it is
accepted.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.join(HERE, '..')
STD = os.environ.get('AUDIT_STANDARDS', '../thebes-audit-standards')
OUT = os.path.join(R, 'motoko', 'test', 'FormGraph.test.mo')


def mo(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif o < 32 or o == 127:
            out.append('\\u{%x}' % o)
        else:
            out.append(ch)
    return '"' + ''.join(out) + '"'


def scaled(text, factor='1.1'):
    """Every amount of the fixture, current and prior, multiplied by the factor: the trial balance still balances and every populated leadsheet moves."""
    import csv, io
    from decimal import Decimal, ROUND_HALF_EVEN
    rows = list(csv.reader(io.StringIO(text, newline='')))
    header = rows[0]
    cols = [i for i, h in enumerate(header) if h in ('Debit', 'Credit', 'Prior Year Debit', 'Prior Year Credit')]
    for r in rows[1:]:
        if not r:
            continue
        for i in cols:
            v = Decimal(r[i].replace(',', '') or '0')
            r[i] = f"{(v * Decimal(factor)).quantize(Decimal('0.01'), rounding=ROUND_HALF_EVEN):,.2f}"
    out = io.StringIO()
    csv.writer(out, lineterminator='\n').writerows(rows)
    return out.getvalue()


def jl(obj):
    """A Motoko `j("...")` literal for a JSON value."""
    return 'j(' + mo(json.dumps(obj, ensure_ascii=False, separators=(',', ':'))) + ')'


def load_forms():
    forms = {}
    for f in sorted(os.listdir(os.path.join(R, 'forms'))):
        if f.startswith('F') and f.endswith('.json'):
            d = json.load(open(os.path.join(R, 'forms', f), encoding='utf-8'))
            forms[d['id']] = d
    return forms


def fields_of(form):
    return {fd['id']: fd for s in form['sections'] for fd in s['fields']}


def filler(fd):
    """A value that satisfies the field's type and required columns."""
    t = fd['type']
    if t == 'select':
        return fd['options'][0]['value']
    if t == 'yesno':
        return 'yes'
    if t == 'date':
        return '2026-02-01'
    if t == 'money':
        return '1000.00'
    if t == 'percent':
        return '5'
    if t == 'integer':
        return 3
    if t == 'table':
        return [{c['id']: filler(c) for c in fd['columns'] if c['required']}]
    return 'Recorded for the graph battery.'


def required_values(form, without=()):
    vals = {}
    for fd in fields_of(form).values():
        if fd['required'] and not fd.get('readonly') and fd['id'] not in without:
            vals[fd['id']] = filler(fd)
    return vals


def other_value(fd, current):
    """A different valid value for the same field, to move an upstream."""
    t = fd['type']
    if t == 'select':
        opts = [o['value'] for o in fd['options']]
        return opts[1] if len(opts) > 1 and opts[0] == current else opts[0]
    if t == 'yesno':
        return 'no' if current == 'yes' else 'yes'
    if t == 'date':
        return '2026-02-02'
    if t == 'money':
        return '2000.00'
    if t == 'percent':
        return '6'
    if t == 'integer':
        return 4
    if t == 'table':
        return [{c['id']: filler(c) for c in fd['columns'] if c['required']}, {c['id']: filler(c) for c in fd['columns'] if c['required']}]
    return 'Changed for the graph battery.'


HEAD = r'''// GENERATED by tools/gen_graph_test.py from forms/GRAPH.json. Do not edit.
// One case per edge of the dependency graph: the upstream changes, the downstream observes.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import F "../src/Forms";
import FF "../src/FirmForms";
import Json "../src/Json";
import Py "../src/Py";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let staff = Principal.fromBlob("\04");
let eqr = Principal.fromBlob("\05");
let s = E.init();
let ff = FF.init();
var checks = 0;
var failed = 0;
var cases = 0;
var stamp = 100;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J { checks += 1; switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } } };
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func view(form : Text) : Json.J { switch (F.view(s, ff, manager, false, 1, form)) { case (#ok(v)) v; case (#err(m)) { checks += 1; failed += 1; Debug.print("FAIL view " # form # ": " # m); #null_ } } };
/// A stated date and time later than every earlier one: the counter runs through days, months and years.
func when() : Text {
  stamp += 1;
  let d = stamp % 28 + 1;
  let m = (stamp / 28) % 12 + 1;
  let y = 2026 + stamp / 336;
  Nat.toText(y) # "-" # (if (m < 10) "0" else "") # Nat.toText(m) # "-" # (if (d < 10) "0" else "") # Nat.toText(d) # "T10:00"
};
/// The drift entry for a field, if the view lists one.
func driftOf(v : Json.J, fieldId : Text) : ?Json.J { for (d in Py.items(field(v, ["drift"])).vals()) { if (field(d, ["field"]) == #str(fieldId)) return ?d }; null };
/// Whether the view's upstream list names a form with a status.
func isEmpty(v : Json.J) : Bool { switch (v) { case (#null_) true; case (#str(x)) x == "0.00" or x == "0" or x == ""; case (#arr(xs)) xs.size() == 0; case _ false } };
func upstreamIs(v : Json.J, form : Text, status : Text) : Bool { for (u in Py.items(field(v, ["upstream"])).vals()) { if (field(u, ["form"]) == #str(form) and field(u, ["status"]) == #str(status)) return true }; false };
/// Save the form's values and prepare it; a form already beyond draft is reopened first.
func prepare(form : Text, values : Text) {
  let v = view(form);
  let st = Py.textOr(v, "status", "not_started");
  if (st != "draft" and st != "not_started") ignore must("reopen " # form, F.reopen(s, partner, false, stamp, 1, form, "graph battery"));
  ignore must("save " # form, F.save(s, ff, partner, false, stamp, 1, form, j("{\"values\":" # values # "}")));
  ignore must("prepare " # form, F.sign(s, ff, partner, stamp, 1, form, "prepare", when()));
};
func saveOnly(form : Text, values : Text) {
  let v = view(form);
  let st = Py.textOr(v, "status", "not_started");
  if (st != "draft" and st != "not_started") ignore must("reopen " # form, F.reopen(s, partner, false, stamp, 1, form, "graph battery"));
  ignore must("save " # form, F.save(s, ff, partner, false, stamp, 1, form, j("{\"values\":" # values # "}")));
};

// the engagement: a partner who also prepares (the graph is about values, not roles), a team, a trial balance
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Graph Trading SAE\",\"framework\":\"IFRS\",\"audit_standard\":\"ISA\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (staff, "staff"), (eqr, "eqr")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));
ignore must("import the trial balance", E.importTrialBalance(s, staff, false, 3, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str(__FIXTURE__))])));
ignore must("compute materiality", E.compute(s, staff, false, 4, 1, j("{\"kind\":\"materiality\",\"procedure_id\":\"P-FSL-006\",\"input\":{\"benchmark\":\"revenue\",\"benchmark_amount\":\"10450000.00\",\"percentage\":\"1\"}}")));
'''

TAIL = r'''
Debug.print("count: graph edge cases = " # Nat.toText(cases));
Debug.print("count: graph checks = " # Nat.toText(checks));
if (failed > 0) Runtime.trap("GRAPH RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("GRAPH GREEN");
'''

# For each computation a form owns: a first input (the figure the downstream freezes) and a
# second (the figure that moves it).
PAPER_MOVES = {
    'materiality': ({'benchmark': 'revenue', 'benchmark_amount': '10450000.00', 'percentage': '1'}, {'benchmark': 'revenue', 'benchmark_amount': '10450000.00', 'percentage': '2'}),
    'aggregation': ({'items': [{'id': 'M1', 'description': 'x', 'type': 'factual', 'status': 'uncorrected', 'assets': '-10000.00', 'liabilities': '0', 'equity': '0', 'profit': '-10000.00'}], 'overall_materiality': '104500.00', 'performance_materiality': '78375.00', 'clearly_trivial': '5225.00'},
                    {'items': [{'id': 'M1', 'description': 'x', 'type': 'factual', 'status': 'uncorrected', 'assets': '-20000.00', 'liabilities': '0', 'equity': '0', 'profit': '-20000.00'}], 'overall_materiality': '104500.00', 'performance_materiality': '78375.00', 'clearly_trivial': '5225.00'}),
    'going_concern': ({'financial_statement_date': '2025-12-31', 'approval_date': '2026-03-25', 'assessment_end_date': '2026-12-31', 'opening_cash': '1000.00', 'monthly_forecast': [{'month': '2026-01', 'inflows': '10.00', 'outflows': '5.00'}], 'facilities': '0', 'standard': 'ISA-570'},
                      {'financial_statement_date': '2025-12-31', 'approval_date': '2026-03-25', 'assessment_end_date': '2026-11-30', 'opening_cash': '1000.00', 'monthly_forecast': [{'month': '2026-01', 'inflows': '10.00', 'outflows': '5.00'}], 'facilities': '0', 'standard': 'ISA-570'}),
    'mus_sample_size': ({'book_value': '1000000.00', 'tolerable_misstatement': '50000.00', 'expected_misstatement': '0', 'beta': '0.05'}, {'book_value': '900000.00', 'tolerable_misstatement': '50000.00', 'expected_misstatement': '0', 'beta': '0.05'}),
    'mus_evaluate': ({'results': [{'id': 'S1', 'book_value': '1000.00', 'audit_value': '900.00', 'stratum': 'sampled'}], 'interval': '5000.00', 'beta': '0.05', 'tolerable_misstatement': '78375.00'}, {'results': [{'id': 'S1', 'book_value': '1000.00', 'audit_value': '950.00', 'stratum': 'sampled'}], 'interval': '5000.00', 'beta': '0.05', 'tolerable_misstatement': '78375.00'}),
    'trend': ({'series': [{'period': '2023', 'value': '100'}, {'period': '2024', 'value': '110'}, {'period': '2025', 'value': '121'}], 'method': 'linear', 'precision_pct': '10'}, {'series': [{'period': '2023', 'value': '100'}, {'period': '2024', 'value': '110'}, {'period': '2025', 'value': '130'}], 'method': 'linear', 'precision_pct': '10'}),
    'attribute_sample_size': ({'tolerable_rate': '0.05', 'beta': '0.10', 'expected_rate': '0'}, {'tolerable_rate': '0.10', 'beta': '0.10', 'expected_rate': '0'}),
    'attribute_evaluate': ({'sample_size': 45, 'deviations': 1, 'beta': '0.10'}, {'sample_size': 45, 'deviations': 2, 'beta': '0.10'}),
    'component_materiality': ({'group_overall': '104500.00', 'group_performance': '78375.00', 'group_clearly_trivial': '5225.00', 'components': [{'id': 'C1', 'name': 'D', 'performance': '50000.00', 'threshold': '1000.00'}]}, {'group_overall': '104500.00', 'group_performance': '78375.00', 'group_clearly_trivial': '5225.00', 'components': [{'id': 'C1', 'name': 'D', 'performance': '90000.00', 'threshold': '1000.00'}]}),
    'analytical_review': ({'lines': [{'name': 'Revenue', 'recorded': '10450000.00', 'model': {'kind': 'prior_growth', 'prior': '9000000.00', 'growth_pct': '5'}}], 'performance_materiality': '78375.00'}, {'lines': [{'name': 'Revenue', 'recorded': '10450000.00', 'model': {'kind': 'prior_growth', 'prior': '10000000.00', 'growth_pct': '4.5'}}], 'performance_materiality': '78375.00'}),
    'tieout': ({'statement_lines': [{'line_id': 'REV', 'caption': 'Revenue', 'presented': '1.00', 'leadsheets': ['LS-REV'], 'sign': '-1'}], 'leadsheet_totals': {'LS-REV': '-1.00'}}, {'statement_lines': [{'line_id': 'REV', 'caption': 'Revenue', 'presented': '2.00', 'leadsheets': ['LS-REV'], 'sign': '-1'}], 'leadsheet_totals': {'LS-REV': '-1.00'}}),
}

# how an upstream source node is moved, by node id; the downstream then observes drift
MOVES = {
    'tb': ('ignore must("import the scaled trial balance", E.importTrialBalance(s, staff, false, stamp, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str(__SCALED__))])));',
           'ignore must("restore the trial balance", E.importTrialBalance(s, staff, false, stamp, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str(__FIXTURE__))])));'),
    'paper:journal_completeness': None,
    'paper:journal_screen': None,
    'paper:analytical_review': None,
}


def main():
    forms = load_forms()
    graph = json.load(open(os.path.join(R, 'forms', 'GRAPH.json'), encoding='utf-8'))
    fixture = open(os.path.join(STD, 'adapters', 'fixtures', 'spreadsheet-basic.csv'), encoding='utf-8', newline='').read()
    import sys
    sys.path.insert(0, HERE)
    body = [HEAD]
    n = 0
    skipped = []
    for e in graph['edges']:
        dst = forms[e['to']]
        dfields = fields_of(dst)
        to_field = e['to_field']
        kind = e['kind']
        src = e['from']
        label = f'{src}{"." + e["from_field"] if e.get("from_field") else ""} -> {e["to"]}.{to_field}'
        body.append(f'\n// {label} ({kind})')
        body.append('cases += 1;')
        if kind == 'form':
            sf = fields_of(forms[src])[e['from_field']]
            v1 = filler(sf) if not sf.get('readonly') else None
            if v1 is None:
                skipped.append(label + ': the source field is read-only; its own edge is tested upstream')
                body.append('// the source field is itself derived; its upstream edge carries the case')
                continue
            v2 = other_value(sf, v1)
            body.append(f'saveOnly({mo(src)}, {mo(json.dumps({e["from_field"]: v1}, ensure_ascii=False))});')
            body.append(f'prepare({mo(e["to"])}, {mo(json.dumps(required_values(dst), ensure_ascii=False))});')
            body.append(f'check("{label}: frozen on the source value", field(view({mo(e["to"])}), ["frozen", {mo(to_field)}]) != #null_);')
            body.append(f'saveOnly({mo(src)}, {mo(json.dumps({e["from_field"]: v2}, ensure_ascii=False))});')
            body.append(f'switch (driftOf(view({mo(e["to"])}), {mo(to_field)})) {{ case (?d) check("{label}: the source is named", field(d, ["source", "node"]) == #str({mo(src)}) and field(d, ["source", "field"]) == #str({mo(e["from_field"])})); case null check("{label}: drifted", false) }};')
        elif kind == 'computed':
            paper_kind = e['via'].split('.')[1]
            if paper_kind not in PAPER_MOVES:
                skipped.append(label + f': no mover for paper {paper_kind}')
                body.append(f'// no mover for the paper kind {paper_kind}')
                continue
            first, second = PAPER_MOVES[paper_kind]
            body.append(f'ignore must("compute {paper_kind}", E.compute(s, staff, false, stamp, 1, {jl({"kind": paper_kind, "input": first})}));')
            body.append(f'prepare({mo(e["to"])}, {mo(json.dumps(required_values(dst), ensure_ascii=False))});')
            body.append(f'ignore must("recompute {paper_kind}", E.compute(s, staff, false, stamp, 1, {jl({"kind": paper_kind, "input": second})}));')
            body.append(f'switch (driftOf(view({mo(e["to"])}), {mo(to_field)})) {{ case (?d) check("{label}: the source is named", field(d, ["source", "node"]) == #str({mo(src)})); case null check("{label}: drifted", false) }};')
            body.append(f'ignore must("compute {paper_kind} back", E.compute(s, staff, false, stamp, 1, {jl({"kind": paper_kind, "input": first})}));')
        elif kind in ('trial_balance', 'records', 'paper', 'model', 'checklist', 'programme', 'group'):
            if kind == 'trial_balance':
                body.append(f'prepare({mo(e["to"])}, {mo(json.dumps(required_values(dst), ensure_ascii=False))});')
                body.append(MOVES['tb'][0])
                body.append(f'switch (driftOf(view({mo(e["to"])}), {mo(to_field)})) {{ case (?d) check("{label}: the source is named", field(d, ["source", "node"]) == #str("tb")); case null check("{label}: an empty leadsheet stays empty", isEmpty(field(view({mo(e["to"])}), ["frozen", {mo(to_field)}]))) }};')
                body.append(MOVES['tb'][1])
            elif kind == 'records':
                rk = src.split(':')[1]
                if rk == 'RK-MISSTATEMENT':
                    add = 'ignore must("add a misstatement", E.addRecord(s, staff, false, stamp, 1, j("{\\"kind\\":\\"RK-MISSTATEMENT\\",\\"fields\\":{\\"description\\":\\"g\\",\\"type\\":\\"factual\\",\\"status\\":\\"uncorrected\\",\\"assets\\":\\"-1.00\\",\\"liabilities\\":\\"0\\",\\"equity\\":\\"0\\",\\"profit\\":\\"-1.00\\",\\"procedure\\":\\"P-REV-004\\"}}")));'
                elif rk == 'RK-REVIEW-NOTE':
                    add = 'ignore must("add a review note", E.addRecord(s, manager, false, stamp, 1, j("{\\"kind\\":\\"RK-REVIEW-NOTE\\",\\"fields\\":{\\"object\\":\\"engagement:1\\",\\"raised_by\\":\\"manager\\",\\"raised_at\\":\\"2026-03-01T09:00\\",\\"text\\":\\"graph\\",\\"state\\":\\"open\\"}}")));'
                elif rk == 'RK-SAMPLE':
                    proc = e['via'].split('.')[-1]
                    add = f'ignore must("add a sample", E.addRecord(s, staff, false, stamp, 1, j("{{\\"kind\\":\\"RK-SAMPLE\\",\\"fields\\":{{\\"procedure\\":\\"{proc}\\",\\"population\\":\\"pop:1\\",\\"selection_method\\":\\"SM-MUS\\",\\"statistical\\":true,\\"size\\":5,\\"items\\":[]}}}}")));'
                elif rk == 'RK-EVIDENCE-LINK':
                    proc = e['via'].split('.')[-1]
                    add = f'ignore must("link evidence", E.addRecord(s, staff, false, stamp, 1, j("{{\\"kind\\":\\"RK-EVIDENCE-LINK\\",\\"fields\\":{{\\"procedure\\":\\"{proc}\\",\\"evidence_item\\":\\"doc:1\\",\\"evidence_kind\\":\\"EK-INSPECTION\\",\\"linked_by\\":\\"staff\\",\\"linked_at\\":\\"2026-02-01T09:00\\"}}}}")));'
                else:
                    skipped.append(label + f': no mover for {rk}')
                    body.append(f'// no mover for record kind {rk}')
                    continue
                body.append(f'prepare({mo(e["to"])}, {mo(json.dumps(required_values(dst), ensure_ascii=False))});')
                if e['via'].endswith('.open'):
                    body.append(f'let before_{n} = field(view({mo(e["to"])}), ["live", {mo(to_field)}]);')
                    body.append(add)
                    body.append(f'let after_{n} = view({mo(e["to"])});')
                    body.append(f'check("{label}: a live count moves and is never frozen", field(after_{n}, ["live", {mo(to_field)}]) != before_{n} and Json.get(field(after_{n}, ["frozen"]), {mo(to_field)}) == null);')
                else:
                    body.append(add)
                    body.append(f'switch (driftOf(view({mo(e["to"])}), {mo(to_field)})) {{ case (?d) check("{label}: the source is named", field(d, ["source", "node"]) == #str({mo(src)})); case null check("{label}: drifted", false) }};')
            elif kind == 'paper':
                pk = src.split(':')[1]
                if MOVES.get(src) is None:
                    body.append(f'// the {pk} paper is produced by a population run, not a one-call computation; its downstream is observed in the journal battery')
                    skipped.append(label + ': population paper')
                    continue
                body.append(f'prepare({mo(e["to"])}, {mo(json.dumps(required_values(dst), ensure_ascii=False))});')
                body.append(MOVES[src][0])
                body.append(f'switch (driftOf(view({mo(e["to"])}), {mo(to_field)})) {{ case (?d) check("{label}: the source is named", field(d, ["source", "node"]) == #str({mo(src)})); case null check("{label}: drifted", false) }};')
            elif kind in ('checklist', 'programme'):
                mover = 'ignore must("answer a disclosure item", Dc_answer());' if kind == 'checklist' else 'ignore must("conclude a procedure", Pg_conclude());'
                body.append(f'prepare({mo(e["to"])}, {mo(json.dumps(required_values(dst), ensure_ascii=False))});')
                body.append(f'let before_{n} = field(view({mo(e["to"])}), ["live", {mo(to_field)}]);')
                body.append(mover)
                body.append(f'let after_{n} = view({mo(e["to"])});')
                body.append(f'check("{label}: a live count moves and is never frozen", field(after_{n}, ["live", {mo(to_field)}]) != before_{n} and Json.get(field(after_{n}, ["frozen"]), {mo(to_field)}) == null);')
            elif kind == 'group':
                body.append(f'prepare({mo(e["to"])}, {mo(json.dumps(required_values(dst), ensure_ascii=False))});')
                body.append(f'ignore must("identify a component", E.addRecord(s, manager, false, stamp, 1, {jl({"kind": "RK-COMPONENT", "fields": {"name": "Delta", "entity": "Delta SAE", "component_auditor": "Other & Co", "scope": "full", "performance_materiality": "50000.00", "threshold": "1000.00"}})}));')
                body.append(f'switch (driftOf(view({mo(e["to"])}), {mo(to_field)})) {{ case (?d) check("{label}: the source is named", field(d, ["source", "node"]) == #str("group")); case null check("{label}: drifted", false) }};')
            elif kind == 'model':
                body.append('// the model is the contract\'s own seed and never changes on an engagement: the edge is exercised by the register loading the presumed risks')
                body.append(f'check("{label}: the presumed risks are live", Py.items(field(view({mo(e["to"])}), ["live", {mo(to_field)}])).size() >= 1);')
        elif kind == 'declared':
            body.append(f'prepare({mo(src)}, {mo(json.dumps(required_values(forms[src]), ensure_ascii=False))});')
            body.append(f'prepare({mo(e["to"])}, {mo(json.dumps(required_values(dst), ensure_ascii=False))});')
            body.append(f'check("{label}: the upstream is listed as prepared", upstreamIs(view({mo(e["to"])}), {mo(src)}, "prepared"));')
            body.append(f'ignore must("reopen the upstream {src}", F.reopen(s, partner, false, stamp, 1, {mo(src)}, "graph battery"));')
            body.append(f'check("{label}: the upstream is listed as unsigned after reopening", upstreamIs(view({mo(e["to"])}), {mo(src)}, "draft"));')
        n += 1
    body.append(TAIL)
    helpers = r'''
import Dc "../src/Disclosures";
import Pg "../src/Programme";
// each move answers a different checklist item or concludes a different procedure, so the count moves every time
let DR_ITEMS : [Text] = __DR_ITEMS__;
var dri = 0;
func Dc_answer() : E.R { let item = DR_ITEMS[dri % DR_ITEMS.size()]; dri += 1; Dc.answer(s, staff, false, stamp, 1, j("{\"item\":\"" # item # "\",\"applicable\":true,\"disclosed\":true,\"reference\":\"Note 2\"}")) };
let PROCS : [Text] = __PROCS__;
var pri = 0;
func Pg_conclude() : E.R { let pid = PROCS[pri % PROCS.size()]; pri += 1; Pg.conclude(s, staff, false, stamp, 1, j("{\"procedure\":\"" # pid # "\",\"conclusion\":\"not_applicable\",\"rationale\":\"Graph battery: not applicable here.\",\"performed_at\":\"" # when() # "\"}")) };
'''
    drs = [d['id'] for d in json.load(open(os.path.join(STD, 'seed', 'disclosure_requirements.json'), encoding='utf-8'))]
    procs = [p['id'] for p in json.load(open(os.path.join(STD, 'seed', 'procedures.json'), encoding='utf-8'))]
    text = '\n'.join(body).replace('__FIXTURE__', mo(fixture)).replace('__SCALED__', mo(scaled(fixture)))
    text = text.replace("let s = E.init();\nlet ff = FF.init();", "let s = E.init();\nlet ff = FF.init();" + helpers.replace('import Dc "../src/Disclosures";\nimport Pg "../src/Programme";\n', ''), 1)
    text = text.replace('__DR_ITEMS__', '[' + ', '.join(mo(x) for x in drs) + ']').replace('__PROCS__', '[' + ', '.join(mo(x) for x in procs) + ']')
    text = text.replace('import Runtime "mo:core/Runtime";', 'import Runtime "mo:core/Runtime";\nimport Dc "../src/Disclosures";\nimport Pg "../src/Programme";', 1)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(text)
    print(f'wrote {os.path.relpath(OUT)}: {n} cases of {len(graph["edges"])} edges' + (f'; without a mover: {len(skipped)}' if skipped else ''))
    for sk in skipped:
        print('  ', sk)


if __name__ == '__main__':
    main()
