#!/usr/bin/env python3
"""Test vectors for motoko/src/P256.mo from the Python `cryptography` library (OpenSSL):
valid signatures on random messages under random keys, and the same signatures broken
every way a verifier must notice. Writes motoko/test/P256.test.mo.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import hashlib, os, random
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature, encode_dss_signature

N = 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551
rng = random.Random(2026_09_10)
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'motoko', 'test', 'P256.test.mo')

def blob(b): return '"' + ''.join('\\%02x' % x for x in b) + '"'

cases = []   # (name, spki, digest, der, expected)
for i in range(24):
    key = ec.generate_private_key(ec.SECP256R1())
    spki = key.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    msg = rng.randbytes(rng.randint(1, 200))
    der = key.sign(msg, ec.ECDSA(hashes.SHA256()))
    digest = hashlib.sha256(msg).digest()
    r, s = decode_dss_signature(der)
    cases.append((f'valid {i}', spki, digest, der, True))
    if i < 6:
        cases.append((f'the other s (n - s) also verifies {i}', spki, digest, encode_dss_signature(r, N - s), True))
        cases.append((f'another message fails {i}', spki, hashlib.sha256(msg + b'x').digest(), der, False))
        cases.append((f'r + 1 fails {i}', spki, digest, encode_dss_signature((r + 1) % N or 1, s), False))
        cases.append((f's + 1 fails {i}', spki, digest, encode_dss_signature(r, (s + 1) % N or 1), False))
        other = ec.generate_private_key(ec.SECP256R1()).public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
        cases.append((f'another key fails {i}', other, digest, der, False))
    if i == 0:
        cases.append(('r = 0 fails', spki, digest, encode_dss_signature(0, s), False))
        cases.append(('s = n fails', spki, digest, encode_dss_signature(r, N), False))
        bad = bytearray(spki); bad[-1] ^= 1
        cases.append(('a point off the curve is refused', bytes(bad), digest, der, None))
        cases.append(('a truncated signature is refused', spki, digest, der[:-1], None))

lines = []
for name, spki, digest, der, want in cases:
    lines.append(f'case_({repr(name).replace(chr(39), chr(34))}, {blob(spki)}, {blob(digest)}, {blob(der)}, {"?true" if want else "?false" if want is False else "null"});')

body = '''// GENERATED by tools/gen_p256_test.py from Python cryptography (OpenSSL). Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import P "../src/P256";
import Blob "mo:core/Blob";
import Nat "mo:core/Nat";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

var checks = 0;
var failed = 0;
/// `want`: ?true verifies, ?false parses but does not verify, null is refused before verifying.
func case_(name : Text, spki : Blob, digest : Blob, der : Blob, want : ?Bool) {
  checks += 1;
  let got : ?Bool = switch (P.parseSpki(spki), P.parseDerSignature(der)) {
    case (?(x, y), ?(r, s)) ?P.verify(x, y, P.natOf(Blob.toArray(digest)), r, s);
    case _ null;
  };
  if (got != want) { failed += 1; Debug.print("FAIL " # name) };
};

''' + '\n'.join(lines) + '''

Debug.print("count: P-256 vectors = " # Nat.toText(checks));
if (failed > 0) Runtime.trap("P256 RED: " # Nat.toText(failed) # " of " # Nat.toText(checks));
Debug.print("P256 GREEN");
'''
open(OUT, 'w').write(body)
print('wrote', os.path.relpath(OUT), len(cases), 'vectors')
