#!/usr/bin/env python3
"""Generate motoko/test/Applicability.test.mo: applicability proposed from the trial balance.

The model names the leadsheets each procedure serves (seed procedure_leadsheets). A procedure
whose every leadsheet is unpopulated on the accepted trial balance is proposed not applicable
with that reason; accepting the proposal records the conclusions; the reviewer confirms them
four-eyes or overrides; a conclusion recorded from the proposal is contradicted when a later
trial balance populates one of its leadsheets, and the procedure is open again.

The oracle is the standards' own import reference (tools/tb_import.py: normalise and map to
leadsheets) folded with the procedure_leadsheets table in Python: the expected proposal on the
fixture, and on a second fixture that populates one more leadsheet, are generated here as
vectors the test compares with, never typed.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import json, os, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
STD = os.environ.get('AUDIT_STANDARDS', '../thebes-audit-standards')
OUT = os.path.join(ROOT, 'motoko', 'test', 'Applicability.test.mo')
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(STD, 'tools'))
from gen_graph_test import mo  # noqa: E402
import tb_import as T  # noqa: E402

S = lambda name: json.load(open(os.path.join(STD, 'seed', name + '.json'), encoding='utf-8'))
PROCS = [p['id'] for p in S('procedures')]
LINKS = {}
for l in S('procedure_leadsheets'):
    LINKS.setdefault(l['procedure_id'], []).append(l['leadsheet_id'])
LINKED = [p for p in PROCS if p in LINKS]
FIXTURE_PATH = os.path.join(STD, 'adapters', 'fixtures', 'spreadsheet-basic.csv')
FIXTURE = open(FIXTURE_PATH, encoding='utf-8', newline='').read()
# the second trial balance: the fixture plus a current provision and its expense, balanced,
# populating one leadsheet the fixture leaves empty
EXTRA = [('4410', 'Warranty provision', '0.00', '50,000.00'), ('6910', 'Warranty expense', '50,000.00', '0.00')]
FIXTURE2 = FIXTURE.rstrip('\r\n') + '\n' + '\n'.join(f'{c},{n},"{d}","{k}",0.00,0.00' for c, n, d, k in EXTRA) + '\n'


def populated(text):
    """The leadsheets a trial balance populates, from the standards' import reference."""
    profile = json.load(open(os.path.join(STD, 'adapters', 'profiles', 'spreadsheet-generic-csv.json'), encoding='utf-8'))
    with tempfile.NamedTemporaryFile('w', suffix='.csv', delete=False, encoding='utf-8', newline='') as fh:
        fh.write(text)
        path = fh.name
    try:
        tb, _counts = T.normalise(profile, path, 'Nile Trading SAE', '2025-01-01', '2025-12-31', 'EGP')
        return [l['leadsheet_id'] for l in T.map_to_leadsheets(tb, 'IFRS-4D')['leadsheets']]
    finally:
        os.unlink(path)


POP1 = populated(FIXTURE)
POP2 = populated(FIXTURE2)
NA1 = [p for p in LINKED if not any(l in POP1 for l in LINKS[p])]
APPLICABLE1 = [p for p in LINKED if p not in NA1]
NEWLY = sorted(set(POP2) - set(POP1))
assert NEWLY, 'the second fixture populates a leadsheet the first does not'
OVERRIDE = NA1[0]                       # the reviewer overrides the first proposal: performed after all
JUDGED = APPLICABLE1[0]                 # the auditor's own judgement on an applicable one
CONTRADICTED = [p for p in NA1 if p != OVERRIDE and any(l in POP2 for l in LINKS[p])]
assert CONTRADICTED, 'the second fixture contradicts at least one accepted proposal'
REVIEWED = [p for p in NA1 if p != OVERRIDE and p not in CONTRADICTED][0]


def jl(obj):
    return mo(json.dumps(obj, ensure_ascii=False, separators=(',', ':')))


HEAD = r'''// GENERATED by tools/gen_applicability_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import FF "../src/FirmForms";
import Pg "../src/Programme";
import Json "../src/Json";
import Py "../src/Py";
import Array "mo:core/Array";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let staff = Principal.fromBlob("\04");
let client = Principal.fromBlob("\05");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func has(xs : [Text], x : Text) : Bool { for (y in xs.vals()) { if (y == x) return true }; false };
func proposal(who : Principal) : Json.J { must("proposal", Pg.proposal(s, ff, who, false, 1)) };
func rowOf(v : Json.J, pid : Text) : Json.J { for (r in Py.list(v, "rows").vals()) { if (Py.textOr(r, "procedure", "") == pid) return r }; #null_ };
func programmeRow(pid : Text) : Json.J { rowOf(must("programme", Pg.view(s, ff, manager, false, 1)), pid) };
func natOf(v : Json.J, k : Text) : Nat { Py.natOr(v, k, 0) };
func texts(v : Json.J, k : Text) : [Text] { Array.map<Json.J, Text>(Py.list(v, k), Py.scalar) };

let LINKED : [Text] = __LINKED__;
let NA : [Text] = __NA__;
let CONTRADICTED : [Text] = __CONTRADICTED__;
let NEWLY : [Text] = __NEWLY__;

// the engagement and its team; no trial balance yet
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Nile Trading SAE\",\"framework\":\"IFRS\",\"audit_standard\":\"ISA\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (senior, "senior"), (staff, "staff"), (client, "client")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));
let p0 = proposal(senior);
check("without a trial balance nothing is proposed", field(p0, ["trial_balance"]) == #bool(false) and Py.list(p0, "rows").size() == 0);
refused("accepting without a trial balance is refused", Pg.acceptProposal(s, ff, senior, false, 3, 1, j("{\"performed_at\":\"2026-02-01T09:00\"}")), "no trial balance");
refused("the client does not see the programme's proposal", Pg.proposal(s, ff, client, false, 1), "the audit programme is the auditor's");

// the trial balance: the proposal is the oracle's, procedure by procedure
ignore must("import the trial balance", E.importTrialBalance(s, staff, false, 3, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str(__FIXTURE__))])));
let p1 = proposal(senior);
check("one row per procedure the model ties to leadsheets", Py.list(p1, "rows").size() == LINKED.size());
check("the proposed count is the oracle's", natOf(p1, "proposed") == NA.size() and natOf(p1, "confirmed") == 0 and natOf(p1, "contradicted") == 0);
var proposedRight = 0;
for (pid in NA.vals()) {
  let r = rowOf(p1, pid);
  let reason = Py.textOr(r, "reason", "");
  var namesEach = true;
  for (l in texts(r, "leadsheets").vals()) { if (not Text.contains(reason, #text l)) namesEach := false };
  if (Py.textOr(r, "state", "") == "proposed" and Py.textOr(r, "proposed", "") == "not_applicable" and texts(r, "populated").size() == 0 and namesEach) proposedRight += 1;
};
check("every procedure the oracle proposes is proposed not applicable, its reason naming each unpopulated leadsheet", proposedRight == NA.size());
var applicableRight = 0;
for (r in Py.list(p1, "rows").vals()) {
  let pid = Py.textOr(r, "procedure", "");
  if (not has(NA, pid) and Py.textOr(r, "state", "") == "applicable" and texts(r, "populated").size() > 0) applicableRight += 1;
};
check("every other linked procedure is applicable with a populated leadsheet", applicableRight + NA.size() == LINKED.size());
check("the populated leadsheets are the oracle's", texts(p1, "populated") == __POP1__);

// accepting the proposal records the conclusions, once
let accepted = must("accept the proposal", Pg.acceptProposal(s, ff, senior, false, 4, 1, j("{\"performed_at\":\"2026-02-01T09:00\"}")));
check("one conclusion per proposed procedure", Py.items(accepted).size() == NA.size());
var conclusionsRight = 0;
for (c in Py.items(accepted).vals()) {
  let f = field(c, ["fields"]);
  if (Py.textOr(c, "kind", "") == Pg.CONCLUSION and Py.textOr(f, "conclusion", "") == "not_applicable" and Text.startsWith(Py.textOr(f, "rationale", ""), #text (Pg.PROPOSED)) and has(NA, Py.textOr(f, "procedure", ""))) conclusionsRight += 1;
};
check("each conclusion is not applicable, its rationale the computed reason marked as proposed", conclusionsRight == NA.size());
let p2 = proposal(manager);
check("every proposal is confirmed", natOf(p2, "confirmed") == NA.size() and natOf(p2, "proposed") == 0);
check("the programme reads the conclusion", field(programmeRow(NA[0]), ["status"]) == #str("not_applicable"));
refused("accepting again records nothing", Pg.acceptProposal(s, ff, senior, false, 5, 1, j("{\"performed_at\":\"2026-02-01T10:00\"}")), "nothing remains proposed");

// the reviewer confirms four-eyes, or overrides
var reviewedId = 0;
for (c in Py.items(accepted).vals()) { if (Py.textOr(field(c, ["fields"]), "procedure", "") == __REVIEWED__) reviewedId := Py.natOr(c, "id", 0) };
refused("four eyes: the one who accepted does not review", Pg.review(s, senior, false, 6, 1, reviewedId, "2026-02-01T11:00"), "not permitted");
ignore must("the manager reviews a confirmed proposal", Pg.review(s, manager, false, 6, 1, reviewedId, "2026-02-01T11:00"));
check("the conclusion is reviewed", field(programmeRow(__REVIEWED__), ["conclusion", "reviewed"]) == #bool(true));
ignore must("the manager overrides one: performed after all", Pg.conclude(s, manager, false, 7, 1, j(__OVERRIDE__)));
let p3 = proposal(manager);
check("the override shows as such", Py.textOr(rowOf(p3, __OVERRIDE_ID__), "state", "") == "overridden" and natOf(p3, "overridden") == 1 and natOf(p3, "confirmed") + 1 == NA.size());
ignore must("the senior judges an applicable procedure not applicable, with a reason", Pg.conclude(s, senior, false, 8, 1, j(__JUDGED__)));
let p4 = proposal(manager);
check("the auditor's own judgement is a judgement, not a contradiction", Py.textOr(rowOf(p4, __JUDGED_ID__), "state", "") == "judgement" and natOf(p4, "judgement") == 1 and natOf(p4, "contradicted") == 0);

// a later trial balance populates a leadsheet: the proposals it contradicts are open again
ignore must("import the trial balance with the provision", E.importTrialBalance(s, staff, false, 9, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str(__FIXTURE2__))])));
let p5 = proposal(manager);
check("the newly populated leadsheets are the oracle's", (func() : Bool { for (l in NEWLY.vals()) { if (not has(texts(p5, "populated"), l)) return false }; true })());
check("the contradicted procedures are the oracle's", Pg.contradicted(s, ff, 1) == CONTRADICTED and natOf(p5, "contradicted") == CONTRADICTED.size());
check("a contradicted procedure says so on the proposal and on the programme", Py.textOr(rowOf(p5, CONTRADICTED[0]), "state", "") == "contradicted" and field(programmeRow(CONTRADICTED[0]), ["contradicted"]) == #bool(true));
check("a contradicted procedure is open again", has(Pg.open(s, ff, 1), CONTRADICTED[0]));
check("the judgement stands: it was the auditor's, not the trial balance's", Py.textOr(rowOf(p5, __JUDGED_ID__), "state", "") == "judgement");
check("the override reads against the trial balance as it stands", Py.textOr(rowOf(p5, __OVERRIDE_ID__), "state", "") == __OVERRIDE_STATE2__);
ignore must("the senior concludes the contradicted procedure anew", Pg.conclude(s, senior, false, 11, 1, j(__RECONCLUDE__)));
let p6 = proposal(manager);
check("concluded anew, it is applicable and nothing is contradicted", Py.textOr(rowOf(p6, CONTRADICTED[0]), "state", "") == "applicable" and natOf(p6, "contradicted") + 1 == CONTRADICTED.size());

Debug.print("count: applicability checks = " # Nat.toText(checks));
Debug.print("count: linked procedures = " # Nat.toText(LINKED.size()));
Debug.print("count: proposed not applicable = " # Nat.toText(NA.size()));
Debug.print("count: contradicted by the second trial balance = " # Nat.toText(CONTRADICTED.size()));
Debug.print("count: refusals = " # Nat.toText(refusals));
if (failed > 0) Runtime.trap("APPLICABILITY RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("APPLICABILITY GREEN");
'''


def main():
    texts = lambda xs: '[' + ', '.join(mo(x) for x in xs) + ']'
    subs = {
        '__LINKED__': texts(LINKED), '__NA__': texts(NA1), '__CONTRADICTED__': texts(CONTRADICTED), '__NEWLY__': texts(NEWLY),
        '__POP1__': texts(POP1),
        '__FIXTURE2__': mo(FIXTURE2), '__FIXTURE__': mo(FIXTURE),
        '__REVIEWED__': mo(REVIEWED),
        '__OVERRIDE_ID__': mo(OVERRIDE), '__JUDGED_ID__': mo(JUDGED),
        # an overridden proposal whose leadsheet the second trial balance populates is simply applicable and performed
        '__OVERRIDE_STATE2__': mo('applicable' if any(l in POP2 for l in LINKS[OVERRIDE]) else 'overridden'),
        '__OVERRIDE__': jl({'procedure': OVERRIDE, 'conclusion': 'performed_no_exception', 'rationale': 'Performed on the opening balances the leadsheet does not show', 'performed_at': '2026-02-02T09:00'}),
        '__JUDGED__': jl({'procedure': JUDGED, 'conclusion': 'not_applicable', 'rationale': 'The balance is clearly trivial this period; see the materiality paper', 'performed_at': '2026-02-02T10:00'}),
        '__RECONCLUDE__': jl({'procedure': CONTRADICTED[0], 'conclusion': 'performed_no_exception', 'rationale': 'Performed on the provision the second trial balance brought in', 'performed_at': '2026-02-03T09:00'}),
    }
    body = HEAD
    for k, v in subs.items():
        assert k in body, k
        body = body.replace(k, v)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(body)
    print(f'wrote {os.path.relpath(OUT)}: {len(LINKED)} linked procedures, {len(NA1)} proposed not applicable on the fixture ({", ".join(NA1)}), '
          f'{NEWLY} newly populated by the second fixture contradicting {CONTRADICTED}; override {OVERRIDE}, judgement {JUDGED}, reviewed {REVIEWED}')


if __name__ == '__main__':
    main()
