#!/usr/bin/env python3
"""Generate motoko/test/BalanceAnalytics.test.mo: the per-balance substantive analytical
procedure paper (F40), one instance for every populated leadsheet.

The reference spreadsheet fixture is imported and the materiality paper computed; the
populated leadsheets come from the standards' Python import reference. For every one of
them an instance of the paper is filled with an expectation built from the prior period,
its computation is run under the instance's own id, and the figures the paper reads
(expected, threshold, difference, whether to investigate) are compared with the standards'
own analytical review (computations/analytics.py): never typed here. One instance is
given an expectation far from the recorded balance, so that the contract refuses to
prepare it until the investigation is recorded. The completion gate names an unsigned
instance until it is prepared, and a re-imported trial balance drifts a prepared paper on
its recorded balance.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import json, os, sys
from decimal import Decimal

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
STD = os.environ.get('AUDIT_STANDARDS', '../thebes-audit-standards')
OUT = os.path.join(ROOT, 'motoko', 'test', 'BalanceAnalytics.test.mo')
sys.path.insert(0, os.path.join(STD, 'tools'))
sys.path.insert(0, STD)
sys.path.insert(0, HERE)
import tb_import as T  # noqa: E402
import computations as c  # noqa: E402
from gen_graph_test import load_forms, required_values, mo, scaled  # noqa: E402

FIXTURE_PATH = os.path.join(STD, 'adapters', 'fixtures', 'spreadsheet-basic.csv')
FIXTURE = open(FIXTURE_PATH, encoding='utf-8', newline='').read()
SCALED = scaled(FIXTURE)
PROFILE = json.load(open(os.path.join(STD, 'adapters', 'profiles', 'spreadsheet-generic-csv.json'), encoding='utf-8'))
LEADSHEETS = {l['id']: l for l in json.load(open(os.path.join(STD, 'seed', 'leadsheets.json'), encoding='utf-8'))}
FORM = load_forms()['F40-BALANCE-ANALYTICS']
BASE = 'F40-BALANCE-ANALYTICS'


def q(x):
    return Decimal(x).quantize(Decimal('0.01'))


def jl(obj):
    return mo(json.dumps(obj, ensure_ascii=False, separators=(',', ':')))


# ---------------------------------------------------------------- the balances and the materiality (oracles)

tb, _counts = T.normalise(PROFILE, FIXTURE_PATH, 'Nile Trading SAE', '2025-01-01', '2025-12-31', 'EGP')
MAPPING = T.map_to_leadsheets(tb, 'IFRS-4D')
POPULATED = [l['leadsheet_id'] for l in MAPPING['leadsheets']]
NET = {l['leadsheet_id']: q(l['net']) for l in MAPPING['leadsheets']}
PRIOR = {l['leadsheet_id']: q(l['prior_net']) for l in MAPPING['leadsheets']}
MAT_INPUT = {'benchmark': 'revenue', 'benchmark_amount': '10450000.00', 'percentage': '1', 'pm_factor': '0.75', 'trivial_factor': '0.05'}
MATERIALITY = c.compute_materiality(**MAT_INPUT)
PM = MATERIALITY['performance']
FAR = 'LS-REV'                     # the instance whose expectation is far from the balance
UNSIGNED = 'LS-CASH'               # the instance left unsigned when the gate is read


def paper_for(ls):
    """An expectation from the prior period: the growth the ledger shows, so the difference is
    the rounding of the rate; for one leadsheet a flat expectation, far from the balance."""
    recorded, prior = NET[ls], PRIOR.get(ls, Decimal(0))
    if ls == FAR:
        model = {'kind': 'prior_growth', 'prior': str(prior), 'growth_pct': '0'}
        values = {'model': 'prior_growth', 'growth_pct': '0'}
    elif prior != 0:
        growth = ((recorded / prior - 1) * 100).quantize(Decimal('0.01'))
        model = {'kind': 'prior_growth', 'prior': str(prior), 'growth_pct': str(growth)}
        values = {'model': 'prior_growth', 'growth_pct': str(growth)}
    else:
        model = {'kind': 'proof_in_total', 'components': [str(recorded)]}
        values = {'model': 'proof_in_total', 'components': [{'name': 'Balance per the ledger', 'amount': str(recorded)}]}
    inp = {'lines': [{'name': ls, 'recorded': str(recorded), 'model': model}], 'performance_materiality': PM, 'threshold_pct': '50'}
    expected = c.analytical_review(inp['lines'], PM, '50', '0')
    line = expected['lines'][0]
    values.update({k: v for k, v in required_values(FORM).items() if k not in values})
    values['threshold_pct'] = '50'
    return inp, expected, line, values


PAPERS = {ls: paper_for(ls) for ls in POPULATED}
assert PAPERS[FAR][2]['investigate'] is True, PAPERS[FAR][2]
assert sum(1 for ls in POPULATED if PAPERS[ls][2]['investigate']) == 1
assert UNSIGNED in POPULATED and FAR in POPULATED and UNSIGNED != FAR

HEAD = r'''// GENERATED by tools/gen_analytics_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import F "../src/Forms";
import FF "../src/FirmForms";
import PF "../src/ProductForms";
import Json "../src/Json";
import Py "../src/Py";
import List "mo:core/List";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let staff = Principal.fromBlob("\04");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
var instances = 0;
var figures = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func view(who : Principal, form : Text) : Json.J {
  switch (F.view(s, ff, who, false, 1, form)) { case (#ok(v)) v; case (#err(m)) { checks += 1; failed += 1; Debug.print("FAIL view " # form # ": " # m); #null_ } };
};
func rowWhere(rows : [Json.J], key : Text, value : Text) : Json.J { for (r in rows.vals()) { if (Py.textOr(r, key, "") == value) return r }; #null_ };
func hasField(def : Json.J, id : Text) : Bool {
  for (sec in Py.list(def, "sections").vals()) { for (f in Py.list(sec, "fields").vals()) { if (Py.textOr(f, "id", "") == id) return true } };
  false
};
func blockingNames(v : Json.J) : [Text] { let o = List.empty<Text>(); for (b in Py.items(field(v, ["blocking"])).vals()) List.add(o, Py.textOr(b, "form", "")); List.toArray(o) };
func has(xs : [Text], x : Text) : Bool { for (y in xs.vals()) { if (y == x) return true }; false };
func compute(form : Text, inp : Text) : E.R {
  E.compute(s, senior, false, 40, 1, #obj([("kind", #str("analytical_review")), ("procedure_id", #str(form)), ("input", j(inp))]))
};

// the engagement, its team, the trial balance and the materiality the papers read
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Nile Trading SAE\",\"framework\":\"EAS\",\"audit_standard\":\"EAS\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (senior, "senior"), (staff, "staff")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));
check("before a trial balance the paper has no instance", Py.items(field(must("statuses", F.statuses(s, ff, manager, false, 1)), [])).size() == 47);
refused("no leadsheet is populated yet", F.save(s, ff, staff, false, 3, 1, "__BASE__@LS-REV", j("{\"values\":{}}")), "not populated");
ignore must("import the trial balance", E.importTrialBalance(s, staff, false, 3, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str(__FIXTURE__))])));
ignore must("compute materiality", E.compute(s, senior, false, 4, 1, #obj([("kind", #str("materiality")), ("procedure_id", #str("P-FSL-006")), ("input", j(__MAT_INPUT__))])));

// the definition and its instances
let cat = Py.items(F.catalogue(ff));
check("the paper is catalogued once, per leadsheet", field(rowWhere(cat, "id", "__BASE__"), ["per"]) == #str("leadsheet") and cat.size() == 48);
let statuses = Py.items(must("statuses", F.statuses(s, ff, manager, false, 1)));
check("one instance per populated leadsheet, beside the other thirty-eight", statuses.size() == 47 + __N__);
check("an instance names its definition, its leadsheet and its own title", (func() : Bool {
  let r = rowWhere(statuses, "form", "__BASE__@LS-REV");
  field(r, ["base"]) == #str("__BASE__") and field(r, ["leadsheet"]) == #str("LS-REV") and Text.contains(Py.textOr(field(r, ["title"]), "en", ""), #text "LS-REV") and Text.contains(Py.textOr(field(r, ["title"]), "en", ""), #text "Revenue")
})());
check("the instance's definition reads the leadsheet it is for", (func() : Bool {
  let v = view(staff, "__BASE__@LS-REV");
  var ok = field(v, ["form", "id"]) == #str("__BASE__@LS-REV");
  for (sec in Py.list(field(v, ["form"]), "sections").vals()) { for (f in Py.list(sec, "fields").vals()) { if (Py.textOr(f, "id", "") == "recorded") ok := ok and Py.textOr(f, "autofill", "") == "tb.leadsheet.LS-REV" } };
  ok and field(v, ["live", "recorded"]) == #str(__REV_NET__) and field(v, ["live", "performance_materiality"]) == #str(__PM__)
})());
check("the bare definition renders with its tokens unreplaced and takes no values", PF.versionText("__BASE__", 1) != null and hasField(j(switch (PF.latest("__BASE__")) { case (?t) t; case null "{}" }), "recorded"));
refused("the paper is filled per leadsheet, never under its bare id", F.save(s, ff, staff, false, 5, 1, "__BASE__", j("{\"values\":{}}")), "filled per leadsheet");
refused("a leadsheet the trial balance does not populate has no paper", F.save(s, ff, staff, false, 5, 1, "__BASE__@LS-NCI", j("{\"values\":{}}")), "not populated");
refused("a leadsheet the model does not know has no paper", F.save(s, ff, staff, false, 5, 1, "__BASE__@LS-NOPE", j("{\"values\":{}}")), "not populated");

// every populated leadsheet: the paper's figures are the computation's (the standards' Python is the oracle)
__INSTANCES__

// the far expectation: an uninvestigated difference beyond the acceptable amount blocks preparing
refused("a difference beyond the acceptable amount with no investigation is not prepared", F.sign(s, ff, staff, 60, 1, "__BASE__@__FAR__", "prepare", "2026-02-02T09:00"), "investigation is required");
ignore must("record the investigation", F.save(s, ff, staff, false, 61, 1, "__BASE__@__FAR__", j(__FAR_INVESTIGATED__)));
ignore must("with the investigation the paper is prepared", F.sign(s, ff, staff, 61, 1, "__BASE__@__FAR__", "prepare", "2026-02-02T09:05"));
check("the far paper is prepared and its figures frozen", (func() : Bool { let v = view(manager, "__BASE__@__FAR__"); field(v, ["status"]) == #str("prepared") and field(v, ["frozen", "difference"]) == #str(__FAR_DIFF__) and field(v, ["frozen", "investigate"]) == #bool(true) })());
check("another instance still reads its own paper, not the far one", field(view(staff, "__BASE__@__OTHER__"), ["live", "difference"]) == #str(__OTHER_DIFF__));

// the gate names the unsigned instance until it is prepared
let ready1 = must("readiness", F.readiness(s, ff, manager, false, 1));
check("the completion gate names the unsigned paper of a populated leadsheet", has(blockingNames(ready1), "__BASE__@__UNSIGNED__") and not has(blockingNames(ready1), "__BASE__"));
check("and not the prepared ones", not has(blockingNames(ready1), "__BASE__@__FAR__"));
ignore must("prepare the last paper", F.sign(s, ff, staff, 70, 1, "__BASE__@__UNSIGNED__", "prepare", "2026-02-02T10:00"));
check("once prepared it is no longer named", not has(blockingNames(must("readiness again", F.readiness(s, ff, manager, false, 1))), "__BASE__@__UNSIGNED__"));

// the file map: one node for the paper, aggregating its instances
let mapv = must("file map", F.fileMap(s, ff, manager, false, 1));
let node = rowWhere(Py.items(field(mapv, ["nodes"])), "id", "__BASE__");
check("the map has one node for the paper with every instance under it", Py.items(field(node, ["instances"])).size() == __N__ and field(node, ["status"]) == #str("prepared") and field(node, ["applicable"]) == #bool(true));
check("the completion view lists every instance as an upstream", (func() : Bool {
  var n = 0;
  for (u in Py.items(field(view(manager, "F14-COMPLETION"), ["upstream"])).vals()) { if (Text.startsWith(Py.textOr(u, "form", ""), #text "__BASE__@")) n += 1 };
  n == __N__
})());

// a re-imported trial balance moves the recorded balance: the prepared paper drifts, naming the trial balance
ignore must("import a scaled trial balance", E.importTrialBalance(s, staff, false, 80, 1, #obj([("profile_id", #str("spreadsheet-generic-csv")), ("source", #str(__SCALED__))])));
let drifted = view(manager, "__BASE__@__FAR__");
check("the paper drifts on its recorded balance", (func() : Bool { for (x in Py.items(field(drifted, ["stale"])).vals()) { if (x == #str("recorded")) return true }; false })());
check("the drift names the trial balance", (func() : Bool { for (d in Py.items(field(drifted, ["drift"])).vals()) { if (field(d, ["field"]) == #str("recorded") and field(d, ["source", "node"]) == #str("tb")) return true }; false })());

Debug.print("count: balance analytics checks = " # Nat.toText(checks));
Debug.print("count: papers instantiated per populated leadsheet = " # Nat.toText(instances));
Debug.print("count: figures against the oracle = " # Nat.toText(figures));
Debug.print("count: refusals = " # Nat.toText(refusals));
if (failed > 0) Runtime.trap("ANALYTICS RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("ANALYTICS GREEN");
'''


def instances_block():
    out = []
    for k, ls in enumerate(POPULATED):
        inp, expected, line, values = PAPERS[ls]
        fid = f'{BASE}@{ls}'
        out.append(f'instances += 1;')
        out.append(f'ignore must("fill {fid}", F.save(s, ff, staff, false, 20, 1, {mo(fid)}, j({jl({"values": values})})));')
        out.append(f'ignore must("compute {fid}", compute({mo(fid)}, {jl(inp)}));')
        out.append(f'figures += 4;')
        out.append(f'check("{ls}: the expectation is the oracle\'s", field(view(staff, {mo(fid)}), ["live", "expected"]) == #str({mo(line["expected"])}));')
        out.append(f'check("{ls}: the threshold is the oracle\'s", field(view(staff, {mo(fid)}), ["live", "threshold"]) == #str({mo(expected["threshold"])}));')
        out.append(f'check("{ls}: the difference is the oracle\'s", field(view(staff, {mo(fid)}), ["live", "difference"]) == #str({mo(line["difference"])}));')
        out.append(f'check("{ls}: whether to investigate is the oracle\'s", field(view(staff, {mo(fid)}), ["live", "investigate"]) == #bool({"true" if line["investigate"] else "false"}));')
        if ls not in (FAR, UNSIGNED):
            out.append(f'ignore must("prepare {fid}", F.sign(s, ff, staff, 21, 1, {mo(fid)}, "prepare", "2026-02-01T{9 + k // 12:02d}:{(k * 5) % 60:02d}"));')
    return '\n'.join(out)


def main():
    other = next(ls for ls in POPULATED if ls not in (FAR, UNSIGNED))
    far_values = dict(PAPERS[FAR][3], investigation='Management attributes the movement to the new export line; shipping documents and price lists corroborate it.')
    body = HEAD
    subs = {
        '__FIXTURE__': mo(FIXTURE), '__SCALED__': mo(SCALED), '__MAT_INPUT__': jl(MAT_INPUT), '__BASE__': BASE, '__N__': str(len(POPULATED)),
        '__REV_NET__': mo(str(NET['LS-REV'])), '__PM__': mo(PM), '__INSTANCES__': instances_block(),
        '__FAR__': FAR, '__UNSIGNED__': UNSIGNED, '__OTHER__': other,
        '__FAR_INVESTIGATED__': jl({'values': far_values}), '__FAR_DIFF__': mo(PAPERS[FAR][2]['difference']), '__OTHER_DIFF__': mo(PAPERS[other][2]['difference']),
    }
    for k, v in subs.items():
        assert k in body, k
        body = body.replace(k, v)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(body)
    print(f'wrote {os.path.relpath(OUT)}: {len(POPULATED)} instances, the far one {FAR} (difference {PAPERS[FAR][2]["difference"]} against a threshold of {PAPERS[FAR][1]["threshold"]}), {UNSIGNED} left for the gate')


if __name__ == '__main__':
    main()
