#!/usr/bin/env python3
"""Generate motoko/test/Consultation.test.mo: consultations and the withdrawal from an engagement.

RK-CONSULTATION is open until its conclusion is agreed by both sides or a difference of
opinion is resolved (ISA 220.35, .37 and .38): the contract refuses a conclusion without its
words, a resolution of a matter that cites an open consultation, and a withdrawal memorandum
(F39) that cites one; the completion form reads the consultations not concluded live and the
file is not assembled while one stands. The partner withdraws on the approved memorandum
(ISA 210.17, ISA 240.38, ISA 250.19): the reasons go to those charged with governance as a
written communication, the engagement closes on a terminal status, and nothing of its file
changes after. The counts the completion form reads are folded here, never typed.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
STD = os.environ.get('AUDIT_STANDARDS', '../thebes-audit-standards')
OUT = os.path.join(ROOT, 'motoko', 'test', 'Consultation.test.mo')
sys.path.insert(0, HERE)
from gen_graph_test import mo, load_forms, required_values  # noqa: E402

S = lambda name: json.load(open(os.path.join(STD, 'seed', name + '.json'), encoding='utf-8'))
KIND = [k for k in S('record_kinds') if k['id'] == 'RK-CONSULTATION'][0]
STATES = [f for f in json.loads(KIND['fields']) if f['name'] == 'state'][0]['type']
assert STATES == 'enum open|agreed|disagreed', STATES
FORMS = load_forms()
F39 = FORMS['F39-WITHDRAWAL']
F14 = FORMS['F14-COMPLETION']
assert F39['number'] == 39 and F39['sections'][1]['fields'][3]['cites'] == ['RK-CONSULTATION']
assert any(f['id'] == 'open_consultations' and f['autofill'] == 'records.RK-CONSULTATION.unresolved' for s_ in F14['sections'] for f in s_['fields'])
PROC = [p['id'] for p in S('procedures') if p['name'].startswith('Understanding the entity')][0]

OPEN = {'matter': 'Whether the loss of the main export customer after the year end is an adjusting event', 'with_whom': 'The technical department', 'party': 'technical_department',
        'consulted_at': '2026-02-05T10:00', 'advice': 'A non-adjusting event: disclose, and reassess going concern.', 'state': 'open', 'consulted_by': 'manager', 'object': 'form:F11-SUBSEQUENT-EVENTS'}
AGREED = dict(OPEN, state='agreed', conclusion='Non-adjusting event disclosed in note 31; going-concern assessment extended.', concluded_at='2026-02-07T15:00')
DISAGREED = {'matter': 'Whether the withdrawal is required by the firm\'s policy on suspected fraud', 'with_whom': 'The risk partner', 'party': 'firm_partner', 'consulted_at': '2026-03-02T09:00',
             'advice': 'Withdraw: management refuses to investigate the suspected fraud.', 'state': 'disagreed', 'conclusion': 'The engagement partner would continue with a modified opinion.', 'concluded_at': '2026-03-03T09:00', 'consulted_by': 'partner'}
RESOLVED = dict(DISAGREED, resolution='Escalated to the managing partner under the firm\'s policy: withdrawal confirmed.')
WITHDRAW_CONSULT = {'matter': 'Withdrawal from the engagement on suspected fraud', 'with_whom': 'The firm\'s risk committee', 'party': 'firm_partner', 'consulted_at': '2026-03-04T10:00',
                    'advice': 'Withdraw; notify the regulator under the money-laundering duty.', 'state': 'open', 'consulted_by': 'partner'}
WITHDRAW_AGREED = dict(WITHDRAW_CONSULT, state='agreed', conclusion='Withdrawal approved by the risk committee.', concluded_at='2026-03-05T12:00')
MINUTES = {'meeting': 'Board of directors', 'held_on': '2026-02-01', 'extract': 'The board noted the loss of the main export customer.', 'matter': 'Loss of the main export customer after the year end',
           'significance': 'significant', 'procedure': PROC, 'reviewed_by': 'senior', 'reviewed_at': '2026-02-03T10:00'}
unresolved = lambda rows: sum(1 for r in rows if r['state'] == 'open' or (r['state'] == 'disagreed' and not r.get('resolution', '').strip()))
F39_FILL = dict(required_values(F39), ground='fraud', circumstances='Management refuses to investigate the suspected diversion of export receipts.',
                alternatives='Continuing is not possible: the scope limitation is pervasive; no legal duty prevents withdrawing.', firm_approved_by='The risk committee', firm_approved_on='2026-03-05',
                management_discussed='yes', tcwg_discussed='yes', regulator='to_be_notified', regulator_note='The financial regulatory authority, under the money-laundering law, within 30 days.',
                report_implication='no_report', withdrawal_date='2026-03-10')


def jl(obj):
    return mo(json.dumps(obj, ensure_ascii=False, separators=(',', ':')))


def rec(kind, fields):
    return jl({'kind': kind, 'fields': fields})


HEAD = r'''// GENERATED by tools/gen_consultation_test.py. Do not edit.
// Attribution: Thebes Core Team. Licence: Apache 2.0.
import E "../src/Engine";
import F "../src/Forms";
import FF "../src/FirmForms";
import Gv "../src/Governance";
import Json "../src/Json";
import Py "../src/Py";
import Nat "mo:core/Nat";
import Principal "mo:core/Principal";
import Text "mo:core/Text";
import Debug "mo:core/Debug";
import Runtime "mo:core/Runtime";

let partner = Principal.fromBlob("\01");
let manager = Principal.fromBlob("\02");
let senior = Principal.fromBlob("\03");
let client = Principal.fromBlob("\05");
let s = E.init();
let ff = FF.init();

var checks = 0;
var failed = 0;
var refusals = 0;
func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };
func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(e)) Runtime.trap("bad test json: " # e) } };
func must(name : Text, r : E.R) : Json.J {
  checks += 1;
  switch (r) { case (#ok(v)) v; case (#err(m)) { failed += 1; Debug.print("FAIL " # name # ": " # m); #null_ } };
};
func refused(name : Text, r : E.R, why : Text) {
  checks += 1; refusals += 1;
  switch (r) {
    case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": was accepted") };
    case (#err(m)) { if (not Text.contains(m, #text why)) { failed += 1; Debug.print("FAIL " # name # ": wrong reason: " # m) } };
  }
};
func field(v : Json.J, path : [Text]) : Json.J { var cur = v; for (k in path.vals()) cur := Py.optJ(Json.get(cur, k)); cur };
func idOf(v : Json.J) : Nat { Py.natOr(v, "id", 0) };
func live(k : Text) : Json.J { switch (F.view(s, ff, manager, false, 1, "F14-COMPLETION")) { case (#ok(v)) field(v, ["live", k]); case (#err(m)) { checks += 1; failed += 1; Debug.print("FAIL view F14: " # m); #null_ } } };
func withConsultation(fill : Text, id : Nat) : Json.J { j(Text.replace(fill, #text "__CID__", Nat.toText(id))) };

// the engagement and its team
ignore must("open", E.createEngagement(s, partner, true, 1, j("{\"client\":\"Nile Trading SAE\",\"framework\":\"IFRS\",\"audit_standard\":\"ISA\",\"currency\":\"EGP\",\"period_start\":\"2025-01-01\",\"period_end\":\"2025-12-31\"}")));
for ((p, r) in [(manager, "manager"), (senior, "senior"), (client, "client")].vals()) ignore must("member " # r, E.setMember(s, partner, true, 2, 1, p, r));

// a consultation is open until its conclusion is agreed
refused("agreed says what was concluded", E.addRecord(s, manager, false, 3, 1, j(__BAD_AGREED__)), "states the conclusion reached");
refused("agreed says when", E.addRecord(s, manager, false, 3, 1, j(__BAD_WHEN__)), "says when");
refused("the state is of the model", E.addRecord(s, manager, false, 3, 1, j(__BAD_STATE__)), "state must be one of");
let c1 = idOf(must("a consultation opened", E.addRecord(s, manager, false, 4, 1, j(__OPEN__))));
check("the completion form counts the consultation not concluded", live("open_consultations") == #num("1"));
let m1 = idOf(must("minutes with a significant matter", E.addRecord(s, senior, false, 5, 1, j(__MINUTES__))));
refused("an open consultation cannot be cited as resolving a matter", E.updateRecord(s, senior, false, 6, m1, j(Text.replace(__RES_CITING__, #text "__CID__", Nat.toText(c1)))), "has no agreed conclusion and cannot be cited");
ignore must("to fieldwork", E.advanceStatus(s, partner, false, 7, 1, "fieldwork"));
ignore must("to completion", E.advanceStatus(s, partner, false, 7, 1, "completion"));
refused("the file is not assembled over an open consultation", F.assembleFile(s, ff, partner, false, 8, 1, "2026-03-25", "2026-03-26T10:00"), "record " # Nat.toText(c1));
ignore must("the conclusion is agreed by both", E.updateRecord(s, manager, false, 9, c1, j(__AGREED__)));
check("agreed, it no longer counts", live("open_consultations") == #num("0"));
ignore must("the agreed consultation resolves the matter", E.updateRecord(s, senior, false, 10, m1, j(Text.replace(__RES_CITING__, #text "__CID__", Nat.toText(c1)))));
check("nothing holds the file on this account", Gv.unresolved(s, 1).size() == 0);

// a difference of opinion is resolved under the firm's policies
let c2 = idOf(must("a consultation with a difference of opinion", E.addRecord(s, partner, false, 11, 1, j(__DISAGREED__))));
check("a difference of opinion without its resolution counts", live("open_consultations") == #num("1") and Gv.unresolved(s, 1).size() == 1);
ignore must("resolved under the firm's policies", E.updateRecord(s, partner, false, 12, c2, j(__RESOLVED__)));
check("resolved, it no longer counts", live("open_consultations") == #num("0"));
check("the page lists the consultations", Py.list(must("governance view", Gv.view(s, manager, false, 1)), "consultations").size() == 2);

// the withdrawal memorandum cites the consultation the firm's policy requires, agreed
let c3 = idOf(must("the consultation on withdrawing", E.addRecord(s, partner, false, 13, 1, j(__WITHDRAW_CONSULT__))));
ignore must("the memorandum is filled, citing the open consultation", F.save(s, ff, manager, false, 14, 1, "F39-WITHDRAWAL", withConsultation(__F39_FILL__, c3)));
refused("the memorandum is not prepared while the consultation is open", F.sign(s, ff, manager, 15, 1, "F39-WITHDRAWAL", "prepare", "2026-03-06T09:00"), "has no agreed conclusion");
ignore must("the memorandum cites a record that is not a consultation", F.save(s, ff, manager, false, 15, 1, "F39-WITHDRAWAL", withConsultation(__F39_FILL__, m1)));
refused("only a consultation is cited there", F.sign(s, ff, manager, 15, 1, "F39-WITHDRAWAL", "prepare", "2026-03-06T09:00"), "cites no RK-CONSULTATION record");
refused("the partner does not withdraw before the memorandum is approved", F.withdraw(s, ff, partner, false, 15, 1, j("{\"withdrawn_at\":\"2026-03-10T10:00\"}")), "must be approved");
ignore must("the consultation is agreed", E.updateRecord(s, partner, false, 16, c3, j(__WITHDRAW_AGREED__)));
ignore must("the memorandum cites it", F.save(s, ff, manager, false, 17, 1, "F39-WITHDRAWAL", withConsultation(__F39_FILL__, c3)));
ignore must("prepared", F.sign(s, ff, manager, 18, 1, "F39-WITHDRAWAL", "prepare", "2026-03-06T09:00"));
ignore must("reviewed", F.sign(s, ff, partner, 19, 1, "F39-WITHDRAWAL", "review", "2026-03-07T09:00"));
ignore must("approved", F.sign(s, ff, partner, 20, 1, "F39-WITHDRAWAL", "approve", "2026-03-08T09:00"));
refused("only the partner withdraws", F.withdraw(s, ff, manager, false, 21, 1, j("{\"withdrawn_at\":\"2026-03-10T10:00\"}")), "not permitted");
refused("the withdrawal is dated after the file's history", F.withdraw(s, ff, partner, false, 21, 1, j("{\"withdrawn_at\":\"2026-03-01T10:00\"}")), "earlier than the latest");
let commsBefore = Py.list(must("view", E.engagementView(s, partner, false, 1)), "records").size();
let w = must("the partner withdraws", F.withdraw(s, ff, partner, false, 22, 1, j("{\"withdrawn_at\":\"2026-03-10T10:00\"}")));
check("the engagement is withdrawn, on the ground the memorandum states", field(w, ["status"]) == #str("withdrawn") and field(w, ["ground"]) == #str("fraud"));
check("the reasons went to those charged with governance in writing", field(w, ["communication", "fields", "with"]) == #str("tcwg") and field(w, ["communication", "fields", "form"]) == #str("written") and Text.contains(Py.textOr(field(w, ["communication", "fields"]), "subject", ""), #text "Withdrawal"));
switch (E.engagement(s, 1)) { case (#ok(e)) check("the status is terminal", e.status == "withdrawn"); case (#err(m)) check("engagement: " # m, false) };
check("the communication is on the file", Py.list(must("view after", E.engagementView(s, partner, false, 1)), "records").size() == commsBefore + 1);
refused("nothing of a withdrawn file changes: a record", E.addRecord(s, manager, false, 23, 1, j(__OPEN__)), "withdrew from this engagement");
refused("nothing of a withdrawn file changes: a form", F.save(s, ff, manager, false, 23, 1, "F14-COMPLETION", j("{\"values\":{}}")), "withdrew from this engagement");
refused("nothing of a withdrawn file changes: a record's fields", E.updateRecord(s, manager, false, 23, c1, j(__AGREED__)), "withdrew from this engagement");
refused("a withdrawn engagement is not withdrawn twice", F.withdraw(s, ff, partner, false, 23, 1, j("{\"withdrawn_at\":\"2026-03-11T10:00\"}")), "withdrew from this engagement");
refused("a withdrawn file is not assembled", F.assembleFile(s, ff, partner, false, 23, 1, "2026-03-25", "2026-03-26T10:00"), "withdrew from this engagement");
switch (F.view(s, ff, manager, false, 1, "F39-WITHDRAWAL")) { case (#ok(v)) check("the memorandum is still read", field(v, ["status"]) == #str("approved")); case (#err(m)) check("view F39: " # m, false) };

Debug.print("count: consultation checks = " # Nat.toText(checks));
Debug.print("count: consultations recorded = 3");
Debug.print("count: refusals = " # Nat.toText(refusals));
if (failed > 0) Runtime.trap("CONSULTATION RED: " # Nat.toText(failed) # " of " # Nat.toText(checks) # " checks failed");
Debug.print("CONSULTATION GREEN");
'''


def main():
    subs = {
        '__BAD_AGREED__': rec('RK-CONSULTATION', {k: v for k, v in AGREED.items() if k != 'conclusion'}),
        '__BAD_WHEN__': rec('RK-CONSULTATION', {k: v for k, v in AGREED.items() if k != 'concluded_at'}),
        '__BAD_STATE__': rec('RK-CONSULTATION', dict(OPEN, state='pending')),
        '__OPEN__': rec('RK-CONSULTATION', OPEN), '__AGREED__': jl({'fields': AGREED}),
        '__MINUTES__': rec('RK-MINUTES-REVIEW', MINUTES),
        '__RES_CITING__': jl({'fields': dict(MINUTES, resolution='Resolved by consultation record:__CID__ (non-adjusting event, disclosed).')}),
        '__DISAGREED__': rec('RK-CONSULTATION', DISAGREED), '__RESOLVED__': jl({'fields': RESOLVED}),
        '__WITHDRAW_CONSULT__': rec('RK-CONSULTATION', WITHDRAW_CONSULT), '__WITHDRAW_AGREED__': jl({'fields': WITHDRAW_AGREED}),
        '__F39_FILL__': jl({'values': dict(F39_FILL, consultation='__CID__')}),
    }
    body = HEAD
    for k, v in subs.items():
        assert k in body, k
        body = body.replace(k, v)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(body)
    print(f'wrote {os.path.relpath(OUT)}: three consultations (open then agreed, disagreed then resolved, the withdrawal\'s), the memorandum F39 with {len(F39_FILL)} values, unresolved fold {unresolved([OPEN])}/{unresolved([AGREED])}/{unresolved([DISAGREED])}/{unresolved([RESOLVED])}')


if __name__ == '__main__':
    main()
