#!/usr/bin/env python3
"""Generate motoko/test/DecFuzz.test.mo from Python's `decimal` module.

Python is the oracle for motoko/src/Dec.mo: every case below is computed here
under the same context the reference computations use, and the Motoko module
must reproduce the printed result exactly. The seed is fixed, so the file is
reproducible.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import math, os, random
from decimal import (Decimal, Context, localcontext, InvalidOperation,
                     ROUND_HALF_EVEN, ROUND_HALF_UP, ROUND_FLOOR, ROUND_CEILING)

R = random.Random(20260910)
OUT = os.path.join(os.path.dirname(__file__), '..', 'motoko', 'test', 'DecFuzz.test.mo')
MODES = {'hu': ROUND_HALF_UP, 'he': ROUND_HALF_EVEN, 'fl': ROUND_FLOOR, 'ce': ROUND_CEILING}
SPECIAL = ['0', '-0', '0.00', '-0.000', '1', '-1', '0.5', '2.5', '-2.5', '0.005', '-0.005', '1E+2', '5E-7',
           '0.05', '0.75', '1234567.89', '-17500.00', '100', '365', '0.0001', '999999999999999999999999999999999999']


def ctx(prec):
    return Context(prec=prec, rounding=ROUND_HALF_EVEN, Emax=999999, Emin=-999999, traps=[InvalidOperation])


def rnd(maxdigits=45, lo=-25, hi=8):
    if R.random() < 0.08:
        return R.choice(SPECIAL)
    nd = R.choice([1, 2, 3, 5, 8, 12, 20, 34, 38, maxdigits])
    coef = R.randint(0, 10 ** nd - 1)
    return str(Decimal(f"{R.choice(['', '-'])}{coef}E{R.randint(lo, hi)}"))


cases = []


def case(op, a, b='', n=0, prec=34, mode='he', want=''):
    cases.append((op, a, b, n, prec, mode, want))


def main():
    for _ in range(400):
        a, b, p = rnd(), rnd(), R.choice([34, 40])
        with localcontext(ctx(p)):
            case('add', a, b, prec=p, want=str(Decimal(a) + Decimal(b)))
            case('sub', a, b, prec=p, want=str(Decimal(a) - Decimal(b)))
            case('mul', a, b, prec=p, want=str(Decimal(a) * Decimal(b)))
            if Decimal(b) != 0:
                case('div', a, b, prec=p, want=str(Decimal(a) / Decimal(b)))
            case('neg', a, prec=p, want=str(-Decimal(a)))
            case('abs', a, prec=p, want=str(abs(Decimal(a))))
        case('cmp', a, b, want=str(int(Decimal(a).compare(Decimal(b)))))
        case('str', a, want=str(Decimal(a)))
        case('floor', a, want=str(int(Decimal(a).to_integral_value(rounding=ROUND_FLOOR))))
        case('ceil', a, want=str(math.ceil(Decimal(a))))
    # exact divisions: the ideal-exponent path
    for _ in range(150):
        b = rnd(8, -4, 2)
        if Decimal(b) == 0:
            continue
        q = rnd(10, -6, 3)
        with localcontext(ctx(34)):
            a = str(Decimal(q) * Decimal(b))
            case('div', a, b, prec=34, want=str(Decimal(a) / Decimal(b)))
    for _ in range(500):
        a, t, m = rnd(40, -12, 6), R.randint(-8, 2), R.choice(list(MODES))
        with localcontext(ctx(34)):
            try:
                w = str(Decimal(a).quantize(Decimal(1).scaleb(t), rounding=MODES[m]))
            except InvalidOperation:
                continue
        case('quantize', a, n=t, mode=m, want=w)
    # exp at the sampling module's precision: arguments are -lambda, lambda in [0, 100]
    for _ in range(120):
        lam = Decimal(R.randint(0, 10 ** 15)) / Decimal(10 ** 13)
        a = str(-lam)
        with localcontext(ctx(40)):
            case('exp', a, prec=40, want=str(Decimal(a).exp()))
    for _ in range(30):
        a = rnd(12, -10, 1)
        if abs(Decimal(a)) > 50:
            continue
        with localcontext(ctx(40)):
            case('exp', a, prec=40, want=str(Decimal(a).exp()))
    # integer powers: (1 - p)**n in the binomial CDF, and squares in the trend fit
    for _ in range(150):
        base = str(Decimal(1) - Decimal(R.randint(1, 10 ** R.choice([2, 4, 12, 39]) - 1)) / Decimal(10) ** 40)
        with localcontext(ctx(40)):
            base = str(+Decimal(base))
            n = R.randint(0, 400)
            case('pow', base, n=n, prec=40, want=str(Decimal(base) ** n))
    for _ in range(80):
        base, n = rnd(20, -10, 3), R.randint(0, 6)
        if Decimal(base) == 0 and n == 0:
            continue
        with localcontext(ctx(34)):
            case('pow', base, n=n, prec=34, want=str(Decimal(base) ** n))

    ops = {}
    for c in cases:
        ops[c[0]] = ops.get(c[0], 0) + 1
    lines = [
        '// GENERATED by tools/gen_dec_cases.py from Python decimal. Do not edit.',
        '// Attribution: Thebes Core Team. Licence: Apache 2.0.',
        'import Dec "../src/Dec";',
        'import Nat "mo:core/Nat";',
        'import Int "mo:core/Int";',
        'import Debug "mo:core/Debug";',
        'import Runtime "mo:core/Runtime";',
        '',
        'let cases : [(Text, Text, Text, Int, Nat, Text, Text)] = [',
    ]
    for (op, a, b, n, p, m, w) in cases:
        lines.append(f'  ("{op}", "{a}", "{b}", {n}, {p}, "{m}", "{w}"),')
    lines += [
        '];',
        '',
        'func mode(m : Text) : Dec.Rounding {',
        '  switch (m) { case "hu" #halfUp; case "he" #halfEven; case "fl" #floor; case "ce" #ceiling; case _ #down }',
        '};',
        '',
        'func run(c : (Text, Text, Text, Int, Nat, Text, Text)) : Text {',
        '  let (op, a, b, n, p, m, _) = c;',
        '  let x = Dec.parse(a);',
        '  switch (op) {',
        '    case "add" Dec.toText(Dec.add(x, Dec.parse(b), p));',
        '    case "sub" Dec.toText(Dec.sub(x, Dec.parse(b), p));',
        '    case "mul" Dec.toText(Dec.mul(x, Dec.parse(b), p));',
        '    case "div" Dec.toText(Dec.div(x, Dec.parse(b), p));',
        '    case "neg" Dec.toText(Dec.neg(x, p));',
        '    case "abs" Dec.toText(Dec.abs(x, p));',
        '    case "cmp" Int.toText(Dec.compare(x, Dec.parse(b)));',
        '    case "str" Dec.toText(x);',
        '    case "floor" Int.toText(Dec.floorInt(x));',
        '    case "ceil" Int.toText(Dec.ceilInt(x));',
        '    case "quantize" Dec.toText(Dec.quantize(x, n, mode(m)));',
        '    case "exp" Dec.toText(Dec.exp(x, p));',
        '    case "pow" Dec.toText(Dec.powNat(x, Int.abs(n), p));',
        '    case _ Runtime.trap("unknown op " # op);',
        '  }',
        '};',
        '',
        'var passed = 0;',
        'var failed = 0;',
        'for (c in cases.vals()) {',
        '  let got = run(c);',
        '  if (got == c.6) { passed += 1 } else {',
        '    failed += 1;',
        '    if (failed <= 25) Debug.print("FAIL " # c.0 # " a=" # c.1 # " b=" # c.2 # " n=" # Int.toText(c.3) # " prec=" # Nat.toText(c.4) # " mode=" # c.5 # " want=" # c.6 # " got=" # got);',
        '  };',
        '};',
    ]
    for op in sorted(ops):
        lines.append(f'Debug.print("count: {op} cases = {ops[op]}");')
    lines += [
        'Debug.print("count: decimal cases examined = " # Nat.toText(cases.size()));',
        'Debug.print("count: decimal cases passed = " # Nat.toText(passed));',
        'if (failed > 0) Runtime.trap("DEC RED: " # Nat.toText(failed) # " cases differ from Python decimal");',
        'Debug.print("DEC GREEN");',
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'wrote {len(cases)} cases to {os.path.relpath(OUT)}: ' + ', '.join(f'{k}={v}' for k, v in sorted(ops.items())))


if __name__ == '__main__':
    main()
