#!/usr/bin/env python3
"""Generate motoko/test/CsvShaOracle.test.mo.

CSV: Python's csv.reader over a real file opened exactly as tb_import.read_rows
opens it (the profile's encoding, newline='') is the oracle for src/Csv.mo, so BOM
handling and every line-ending form are what the importer really sees.
SHA-256: hashlib is the oracle for src/Hash.mo, over boundary lengths and the
adapter fixtures.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import csv, glob, hashlib, json, os, random, tempfile

STD = os.environ.get('AUDIT_STANDARDS', os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'thebes-audit-standards'))
OUT = os.path.join(os.path.dirname(__file__), '..', 'motoko', 'test', 'CsvShaOracle.test.mo')
R = random.Random(20260911)


def mo(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif o < 32 or o == 127:
            out.append('\\u{%x}' % o)
        else:
            out.append(ch)
    return '"' + ''.join(out) + '"'


def moblob(b):
    return '"' + ''.join('\\%02x' % x for x in b) + '"'


CELLS = ['1000', 'Bank', '"12,500.00"', '', ' ', '"a ""quoted"" word"', '"multi\nline"', '"cr\r\nlf"', 'x"y', '"q"tail',
         'مراجعة', '(1,00)', '1.000.000,00-', 'TOTAL', '""', '"a,b"', '"a;b"', 'é', '  spaced  ']


def random_csv(delim):
    lines = []
    for _ in range(R.randint(0, 7)):
        if R.random() < 0.1:
            lines.append('')
            continue
        cells = [R.choice(CELLS) for _ in range(R.randint(1, 5))]
        lines.append(delim.join(c.replace(',', delim) if not c.startswith('"') else c for c in cells))
    term = R.choice(['\n', '\r\n', '\r'])
    text = term.join(lines)
    if R.random() < 0.6:
        text += term
    if R.random() < 0.05:
        text += '"unterminated'
    return text


def read_like_importer(text, encoding, delim):
    with tempfile.NamedTemporaryFile('wb', delete=False, suffix='.csv') as f:
        raw = (b'\xef\xbb\xbf' if R.random() < 0.3 else b'') + text.encode('utf-8')
        f.write(raw)
        path = f.name
    try:
        with open(path, encoding=encoding, newline='') as fh:
            rows = list(csv.reader(fh, delimiter=delim))
    finally:
        os.remove(path)
    return raw.decode('utf-8'), rows


def main():
    csv_cases = []
    for _ in range(400):
        delim = R.choice([',', ';'])
        enc = R.choice(['utf-8', 'utf-8-sig'])
        src, rows = read_like_importer(random_csv(delim), enc, delim)
        csv_cases.append((src, delim, enc == 'utf-8-sig', json.dumps(rows, ensure_ascii=False, separators=(',', ':'))))
    for f in sorted(glob.glob(STD + '/adapters/fixtures/*.csv')):
        src = open(f, encoding='utf-8', newline='').read()
        delim = ';' if 'sap' in f else ','
        rows = list(csv.reader(open(f, encoding='utf-8-sig', newline=''), delimiter=delim))
        csv_cases.append((src, delim, True, json.dumps(rows, ensure_ascii=False, separators=(',', ':'))))
    sha_cases = []
    for n in [0, 1, 3, 55, 56, 57, 63, 64, 65, 119, 120, 128, 1000]:
        b = bytes(R.randrange(256) for _ in range(n))
        sha_cases.append((b, hashlib.sha256(b).hexdigest()))
    for f in sorted(glob.glob(STD + '/adapters/fixtures/*')):
        b = open(f, 'rb').read()
        sha_cases.append((b, hashlib.sha256(b).hexdigest()))
    lines = ['// GENERATED by tools/gen_csv_cases.py from Python csv + hashlib. Do not edit.',
             '// Attribution: Thebes Core Team. Licence: Apache 2.0.',
             'import Csv "../src/Csv";', 'import Hash "../src/Hash";', 'import Json "../src/Json";',
             'import Array "mo:core/Array";', 'import Nat "mo:core/Nat";', 'import Text "mo:core/Text";',
             'import Debug "mo:core/Debug";', 'import Runtime "mo:core/Runtime";', '',
             'let csvCases : [(Text, Text, Bool, Text)] = [']
    lines += [f'  ({mo(s)}, {mo(d)}, {"true" if b else "false"}, {mo(w)}),' for s, d, b, w in csv_cases]
    lines += ['];', 'let shaCases : [(Blob, Text)] = [']
    lines += [f'  ({moblob(b)}, "{h}"),' for b, h in sha_cases]
    lines += ['];', '',
              'var csvOk = 0; var shaOk = 0; var failed = 0;',
              'for ((src, delim, bom, want) in csvCases.vals()) {',
              '  let rows = Csv.parse(src, Text.toArray(delim)[0], bom);',
              '  let got = Json.toText(#arr(Array.map<[Text], Json.J>(rows, func(r) { Json.texts(r) })));',
              '  if (got == want) csvOk += 1 else { failed += 1; if (failed <= 8) Debug.print("FAIL csv want=" # want # " got=" # got) };',
              '};',
              'for ((b, want) in shaCases.vals()) {',
              '  let got = Hash.sha256Hex(b);',
              '  if (got == want) shaOk += 1 else { failed += 1; Debug.print("FAIL sha want=" # want # " got=" # got) };',
              '};',
              'Debug.print("count: csv documents matching Python csv.reader = " # Nat.toText(csvOk));',
              'Debug.print("count: sha256 digests matching hashlib = " # Nat.toText(shaOk));',
              'if (failed > 0 or csvOk != csvCases.size() or shaOk != shaCases.size()) Runtime.trap("CSV/SHA RED");',
              'Debug.print("CSV SHA GREEN");']
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')
    print(f'wrote {len(csv_cases)} csv cases and {len(sha_cases)} sha cases')


if __name__ == '__main__':
    main()
