#!/usr/bin/env python3
"""Generate motoko/test/Odoo.test.mo: the Odoo connector's pull machine replayed against
the bodies recorded from a demo.odoo.com database (motoko/test/fixtures/odoo, captured
with a read-only user's key), checked against tools/odoo_connector_oracle.py byte for byte:
every request body, every mapped part and its fingerprint, the trial balance, the source
fingerprint and the `Population.begin` input. The parts are then fed to the real
Population module, which must accept completeness against the pulled balances and screen
exactly as the one-call oracle does. Refusals, retries, the write-access gate, a changed
ledger and the key discipline are each checked.

Attribution: Thebes Core Team. Licence: Apache 2.0.
"""
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import odoo_connector_oracle as O  # noqa: E402

HERE = os.path.dirname(__file__)
FIX = os.path.join(HERE, '..', 'motoko', 'test', 'fixtures', 'odoo')
OUT = os.path.join(HERE, '..', 'motoko', 'test', 'Odoo.test.mo')

KEY = 'ro-key-0123456789abcdef-NEVER-PERSISTED'
PARAMS = {"PC-MANUAL": {}, "PC-SELF-APPROVED": {}, "PC-LARGE-AMOUNT": {"threshold": "1000.00"},
          "PC-NO-DESCRIPTION": {"min_length": 3}, "PC-REVERSAL-AFTER-PERIOD": {"period_end": "2026-08-31"}}
UTC_OFFSET = 120  # Egypt


def lit(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t') + '"'


def main():
    meta = json.load(open(os.path.join(FIX, 'meta.json')))
    host, db, frm, to, pl = meta['host'], meta['database'], meta['from'], meta['to'], meta['page_lines']
    bodies = {}
    for tag in meta['requests']:
        bodies[tag] = open(os.path.join(FIX, tag.replace(':', '_') + '.body'), 'rb').read().decode('utf-8')
    pages = sorted(t for t in bodies if t.startswith('page:'))
    # oracle
    accounts = O.parse_accounts([bodies['accounts:0']])
    journals = O.parse_journals([bodies['journals:0']])
    reversals = O.parse_reversals([bodies['reversals:0']])
    opening = O.parse_groups([bodies['opening:0']])
    closing = O.parse_groups([bodies['closing:0']])
    kept, dropped = O.assessable(PARAMS)
    mapped = [O.map_page(bodies[t], accounts, journals, reversals, 2, UTC_OFFSET) for t in pages]
    body_shas = [hashlib.sha256(bodies[t].encode('utf-8')).hexdigest() for t in pages]
    tb = O.trial_balance(opening, closing, accounts, 2)
    begin = {"parts": [m['sha256'] for m in mapped], "lines": sum(m['lines'] for m in mapped),
             "source_sha256": O.source_sha256(body_shas), "params": kept, "trial_balance": tb, "places": 2}
    begin_text = O.compact(begin)
    count = int(bodies['count'])
    assert count == begin['lines'], (count, begin['lines'])
    # expected requests
    reqs = {}
    for tag in list(bodies) + ['recount']:
        model, method, body = O.request(tag, host, frm, to, pl)
        reqs[tag] = (f'{host}/json/2/{model}/{method}', body)
        if tag in meta['requests']:
            assert meta['requests'][tag]['body'] == body, tag
            assert meta['requests'][tag]['url'] == reqs[tag][0], tag

    w = []
    w.append('// Generated by tools/gen_odoo_test.py: the Odoo connector replayed against bodies recorded')
    w.append('// from a demo.odoo.com database, byte-identical to tools/odoo_connector_oracle.py. Do not edit.')
    w.append('// Attribution: Thebes Core Team. Licence: Apache 2.0.')
    w.append('import Odoo "../src/Odoo";')
    w.append('import Pop "../src/Population";')
    w.append('import Journals "../src/calc/Journals";')
    w.append('import Json "../src/Json";')
    w.append('import Py "../src/Py";')
    w.append('import Array "mo:core/Array";')
    w.append('import List "mo:core/List";')
    w.append('import Map "mo:core/Map";')
    w.append('import Nat "mo:core/Nat";')
    w.append('import Principal "mo:core/Principal";')
    w.append('import Text "mo:core/Text";')
    w.append('import Debug "mo:core/Debug";')
    w.append('import Runtime "mo:core/Runtime";')
    w.append('')
    w.append('var checks = 0;')
    w.append('var failed = 0;')
    w.append('func check(name : Text, cond : Bool) { checks += 1; if (not cond) { failed += 1; Debug.print("FAIL " # name) } };')
    w.append('func same(name : Text, got : Text, want : Text) { if (got != want) Debug.print("GOT  " # got # "\\nWANT " # want); check(name, got == want) };')
    w.append('let by = Principal.fromBlob("\\03");')
    w.append(f'let KEY = {lit(KEY)};')
    w.append(f'let HOST = {lit(host)};')
    w.append(f'let DB = {lit(db)};')
    w.append(f'let BEGIN = {lit(O.compact({"host": host, "database": db, "key": KEY, "from": frm, "to": to, "params": PARAMS, "page_lines": pl, "window": 2, "utc_offset_minutes": UTC_OFFSET}))};')
    w.append('func j(t : Text) : Json.J { switch (Json.parse(t)) { case (#ok(v)) v; case (#err(m)) Runtime.trap(m) } };')
    w.append('')
    w.append('// recorded bodies, by tag')
    for tag, body in bodies.items():
        w.append(f'let B_{tag.replace(":", "_").upper()} = {lit(body)};')
    w.append('func body(tag : Text) : Text {')
    w.append('  switch (tag) {')
    for tag in bodies:
        w.append(f'    case {lit(tag)} B_{tag.replace(":", "_").upper()};')
    w.append('    case "recount" B_COUNT;')
    w.append('    case _ Runtime.trap("no body for " # tag);')
    w.append('  }')
    w.append('};')
    w.append('')
    w.append('// the oracle')
    w.append('let REQUESTS : [(Text, Text, Text)] = [')
    for tag, (u, b) in reqs.items():
        w.append(f'  ({lit(tag)}, {lit(u)}, {lit(b)}),')
    w.append('];')
    w.append(f'let PART_SHAS : [Text] = [{", ".join(lit(m["sha256"]) for m in mapped)}];')
    w.append(f'let PART_LINES : [Nat] = [{", ".join(str(m["lines"]) for m in mapped)}];')
    w.append(f'let PART_IDS : [(Nat, Nat)] = [{", ".join("(%d, %d)" % (m["first_id"], m["last_id"]) for m in mapped)}];')
    for i, m in enumerate(mapped):
        w.append(f'let PART_{i} = {lit(m["part"])};')
    w.append(f'let SOURCE_SHA = {lit(begin["source_sha256"])};')
    w.append(f'let BEGIN_JSON = {lit(begin_text)};')
    w.append(f'let TRIAL_BALANCE = {lit(O.compact(tb))};')
    w.append(f'let NOT_ASSESSABLE : [Text] = [{", ".join(lit(c) for c in dropped)}];')
    w.append('')
    w.append('''func expected(tag : Text) : (Text, Text) {
  switch (Array.find<(Text, Text, Text)>(REQUESTS, func(r) { r.0 == tag })) { case (?r) (r.1, r.2); case null Runtime.trap("no expected request " # tag) }
};
func hasKey(t : Text) : Bool { Text.contains(t, #text KEY) };

/// Drive a pull to its end. `deliver` decides the status and body a tag lands with (or
/// null for a transport failure), `shuffle` delivers the second in-flight page first.
type Delivery = { #reply : (Nat, Text); #lost : Text; #hold };
func drive(s : Odoo.State, p : Odoo.Pull, deliver : (Text, Nat) -> Delivery, shuffle : Bool) : Nat {
  var at : Int = 1_000_000_000;
  var rounds = 0;
  var handle : Int64 = 1;
  var held = Map.empty<Text, Nat>();
  label run while (rounds < 400) {
    rounds += 1;
    let tags = Odoo.advance(s, p, at);
    if (p.status == "ready" or p.status == "failed" or p.status == "done") break run;
    for (t in tags.vals()) {
      switch (Odoo.requestFor(p, t)) {
        case (?r) {
          let (u, b) = expected(t);
          same("request " # t # " url", r.url, u);
          same("request " # t # " body", r.body, b);
          check("request " # t # " carries no key", not hasKey(r.url # r.body));
          Odoo.submitted(p, t, handle, at);
          handle += 1;
        };
        case null { failed += 1; Debug.print("FAIL no request for " # t) };
      };
    };
    // land everything in flight; the pages in reverse order when shuffling
    var inflight = Array.fromIter<Text>(Map.keys(p.inflight));
    if (shuffle) inflight := Array.reverse<Text>(inflight);
    at += 1_000_000_000;
    for (t in inflight.vals()) {
      let n = switch (Map.get(held, Text.compare, t)) { case (?v) v; case null 0 };
      switch (deliver(t, n)) {
        case (#reply((st, b))) ignore Odoo.landed(s, p, t, st, b, at);
        case (#lost(why)) ignore Odoo.failed(p, t, why);
        case (#hold) Map.add(held, Text.compare, t, n + 1);
      };
    };
    if (tags.size() == 0 and inflight.size() == 0 and List.size(p.queue) == 0) break run;
  };
  rounds
};
func recorded(tag : Text, _n : Nat) : Delivery { #reply((200, body(tag))) };

// ------------------------------------------------------------------ refusals at begin
do {
  let s = Odoo.init();
  func refused(name : Text, json : Text, why : Text) {
    switch (Odoo.begin(s, by, 1, 7, j(json))) {
      case (#ok(_)) { failed += 1; Debug.print("FAIL " # name # ": accepted") };
      case (#err(m)) same(name, m, why);
    }
  };
  func patched(patch : [(Text, Json.J)]) : Text {
    switch (j(BEGIN)) {
      case (#obj(kvs)) {
        var out : [(Text, Json.J)] = [];
        for ((k, v) in kvs.vals()) { switch (Array.find<(Text, Json.J)>(patch, func(x) { x.0 == k })) { case (?x) out := Array.concat(out, [x]); case null out := Array.concat(out, [(k, v)]) } };
        for ((k, v) in patch.vals()) { if (Array.find<(Text, Json.J)>(kvs, func(x) { x.0 == k }) == null) out := Array.concat(out, [(k, v)]) };
        Json.toText(#obj(out))
      };
      case _ Runtime.trap("BEGIN");
    }
  };
  refused("host: http", patched([("host", #str("http://demo3.odoo.com"))]), "the host must start with https://");
  refused("host: path", patched([("host", #str("https://demo3.odoo.com/web"))]), "the host is the scheme and name only, without a path");
  refused("host: trailing slash", patched([("host", #str("https://demo3.odoo.com/"))]), "the host is the scheme and name only, without a trailing slash");
  refused("host: query", patched([("host", #str("https://demo3.odoo.com?x=1"))]), "the host may not contain ?");
  refused("host: credentials", patched([("host", #str("https://user@demo3.odoo.com"))]), "the host may not contain @");
  refused("host: empty", patched([("host", #str("https://"))]), "the host is empty");
  refused("database missing", patched([("database", #str(""))]), "database is required");
  refused("key missing", patched([("key", #str(""))]), "key is required: an API key of a read-only Odoo user");
  refused("key with newline", patched([("key", #str("abcdefgh\\nij"))]), "the key may not contain whitespace");
  refused("from after to", patched([("from", #str("2026-10-01"))]), "from must not be after to");
  refused("bad date", patched([("to", #str("2026-13-01"))]), "to must be a date, YYYY-MM-DD");
  refused("only not-assessable criteria", patched([("params", #obj([("PC-SELF-APPROVED", #obj([]))]))]), "choose at least one criterion this source can answer");
  refused("page_lines too small", patched([("page_lines", Json.nat(10))]), "page_lines is 50 to 500");
  refused("window too large", patched([("window", Json.nat(9))]), "window is 1 to 4");
  refused("utc offset out of range", patched([("utc_offset_minutes", Json.int(900))]), "utc_offset_minutes is -840 to 840");
  check("url: disallowed method", Odoo.url(HOST, "account.move", "write") == null);
  check("url: disallowed model", Odoo.url(HOST, "res.users", "search_read") == null);
  check("url: allowed", Odoo.url(HOST, "account.move.line", "search_read") == ?(HOST # "/json/2/account.move.line/search_read"));
  same("posted_at: Egypt offset", Odoo.postedAt("2026-09-06 23:39:02", 120), "2026-09-07T01:39:02");
  same("posted_at: negative offset across midnight", Odoo.postedAt("2026-01-01 00:10:00", -60), "2025-12-31T23:10:00");
  same("posted_at: not a datetime", Odoo.postedAt("2026-09-06", 0), "");
};

// ------------------------------------------------------------------ the recorded pull, twice: pages in order and shuffled
func fullPull(shuffle : Bool) : (Odoo.State, Odoo.Pull) {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  let label_ = if (shuffle) "shuffled: " else "ordered: ";
  check(label_ # "not assessable listed", Array.equal<Text>(p.notAssessable, NOT_ASSESSABLE, Text.equal));
  check(label_ # "a second pull is refused while one runs", switch (Odoo.begin(s, by, 2, 7, j(BEGIN))) { case (#err(m)) m == "pull 1 is still running; wait for it to finish"; case _ false });
  check(label_ # "the view never shows the key", not hasKey(Json.toText(Odoo.view(p))));
  let rounds = drive(s, p, recorded, shuffle);
  same(label_ # "status", p.status # " " # p.failure, "ready ");
  check(label_ # "rounds bounded", rounds < 40);
  check(label_ # "write access false", p.writeAccess == ?false);
  check(label_ # "pages", List.size(p.pages) == PART_SHAS.size());
  for (i in PART_SHAS.keys()) {
    if (i < List.size(p.pages)) {
      let pg = List.at(p.pages, i);
      same(label_ # "part " # Nat.toText(i) # " fingerprint", pg.partSha, PART_SHAS[i]);
      check(label_ # "part " # Nat.toText(i) # " lines", pg.lines == PART_LINES[i]);
      check(label_ # "part " # Nat.toText(i) # " ids", pg.firstId == PART_IDS[i].0 and pg.lastId == PART_IDS[i].1);
      let want = switch (i) { case 0 PART_0; case 1 PART_1; case 2 PART_2; case _ "" };
      switch (Odoo.partText(s, p, i)) { case (#ok(t)) same(label_ # "part " # Nat.toText(i) # " text", t, want); case (#err(m)) { failed += 1; Debug.print("FAIL part text " # m) } };
      check(label_ # "page body " # Nat.toText(i) # " kept", Odoo.pageBody(s, p, i) == ?body("page:" # Nat.toText(i)));
    };
  };
  same(label_ # "source fingerprint", Odoo.sourceSha(p), SOURCE_SHA);
  check(label_ # "metadata bodies kept by tag", Array.equal<Text>(Odoo.metaTags(p), ["accounts:0", "closing:0", "journals:0", "opening:0", "reversals:0"], Text.equal));
  check(label_ # "the chart body is the agreed one", Odoo.metaBody(s, p, "accounts:0") == ?body("accounts:0"));
  check(label_ # "an unknown tag is not served", Odoo.metaBody(s, p, "gate") == null);
  same(label_ # "trial balance", Json.toText(#arr(Odoo.trialBalance(p))), TRIAL_BALANCE);
  same(label_ # "begin input", Json.toText(Odoo.beginJson(p)), BEGIN_JSON);
  (s, p)
};
do { ignore fullPull(true) };
do {
  let (s, p) = fullPull(false);
  // the real population: completeness against the pulled balances, screen against the oracle
  let pops = Pop.init();
  let pop = switch (Pop.begin(pops, by, 3, 7, Odoo.beginJson(p))) { case (#ok(v)) Py.natOr(v, "id", 0); case (#err(m)) Runtime.trap("begin: " # m) };
  var all : [Json.J] = [];
  for (i in Nat.range(0, List.size(p.pages))) {
    let t = switch (Odoo.partText(s, p, i)) { case (#ok(t)) t; case (#err(m)) Runtime.trap(m) };
    switch (Pop.putPart(pops, by, pop, i, t)) { case (#ok(_)) {}; case (#err(m)) { failed += 1; Debug.print("FAIL putPart " # Nat.toText(i) # ": " # m) } };
    all := Array.concat(all, Py.items(j(t)));
  };
  let c = switch (Pop.seal(pops, pop)) { case (#ok(c)) c; case (#err(m)) Runtime.trap("seal: " # m) };
  check("completeness accepted against the pulled trial balance", Py.truthy(Json.get(c, "accepted")));
  let oracleC = switch (Journals.completeness(#obj([("lines", #arr(all)), ("trial_balance", #arr(Odoo.trialBalance(p))), ("places", Json.nat(2))]))) { case (#ok(v)) v; case (#err(m)) Runtime.trap(m) };
  same("completeness equals the one-call oracle", Json.toText(c), Json.toText(oracleC));
  var v : Json.J = #null_;
  var steps = 0;
  label screen while (steps < 100) { steps += 1; v := switch (Pop.step(pops, pop, 25)) { case (#ok(v)) v; case (#err(m)) Runtime.trap(m) }; if (Py.textOr(v, "status", "") == "screened") break screen };
  let pp = switch (Pop.get(pops, pop)) { case (?x) x; case null Runtime.trap("pop") };
  let oracleS = switch (Journals.screen(#obj([("lines", #arr(all)), ("params", #obj(p.params))]))) { case (#ok(v)) v; case (#err(m)) Runtime.trap(m) };
  same("screen equals the one-call oracle", Json.toText(Pop.fullOutput(pops, pp)), Json.toText(oracleS));
  check("a manual entry was flagged (PC-MANUAL)", pp.flagged > 0);
  check("the reversal was flagged after the period", Text.contains(Json.toText(oracleS), #text "PC-REVERSAL-AFTER-PERIOD"));
  // the paper and the end of the pull
  p.popId := pop;
  let (input, output) = Odoo.paper(p);
  check("paper input carries no key", not hasKey(Json.toText(input)));
  check("paper output carries no key", not hasKey(Json.toText(output)));
  check("paper lists the not-assessable criterion", Text.contains(Json.toText(input), #text "PC-SELF-APPROVED"));
  Odoo.finish(p);
  same("key overwritten at the end", p.key, "");
  check("done", p.status == "done");
  check("after the pull a new one may begin", switch (Odoo.begin(s, by, 9, 7, j(BEGIN))) { case (#ok(q)) { q.id == 2 and not p.pagesKept }; case (#err(_)) false });
  check("the previous pull's pages are released", Odoo.pageBody(s, p, 0) == null and Odoo.metaBody(s, p, "accounts:0") == null);
};

// ------------------------------------------------------------------ the gate
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "gate") #reply((200, "true")) else #reply((200, body(t))) }, false);
  check("write access ends the pull", p.status == "failed" and Text.startsWith(p.failure, #text "the key has write access"));
  same("gate: key overwritten", p.key, "");
  check("gate: no pages were asked for", p.nextPage == 0);
};
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "gate") #reply((401, "{\\"name\\": \\"Unauthorized\\"}")) else #reply((200, body(t))) }, false);
  check("a refused key ends the pull", p.status == "failed" and Text.startsWith(p.failure, #text "Odoo refused the key (HTTP 401)"));
  same("401: key overwritten", p.key, "");
};

// ------------------------------------------------------------------ a ledger that changes
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "recount") #reply((200, "103")) else #reply((200, body(t))) }, false);
  check("a changed count is refused", p.status == "failed" and Text.startsWith(p.failure, #text "the ledger changed during the pull: 103 lines now, 102 pulled"));
  same("recount: key overwritten", p.key, "");
};
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  // page 1 answered with page 0's body: same ids again
  ignore drive(s, p, func(t, _) { if (t == "page:1") #reply((200, body("page:0"))) else #reply((200, body(t))) }, false);
  check("an overlapping page is refused", p.status == "failed" and Text.contains(p.failure, #text "page 1 overlaps the previous page"));
};
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  // the last page answered with a full page: more lines than declared
  ignore drive(s, p, func(t, _) { if (t == "page:2") #reply((200, body("page:1"))) else #reply((200, body(t))) }, false);
  check("a page of the wrong size is refused", p.status == "failed" and Text.contains(p.failure, #text "page 2 holds 50 lines, 2 expected"));
};
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "count") #reply((200, "0")) else #reply((200, body(t))) }, false);
  check("an empty period is refused", p.status == "failed" and Text.startsWith(p.failure, #text "no posted journal lines between"));
};

// ------------------------------------------------------------------ retries
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  // page 1 answers 429 twice, then succeeds
  ignore drive(s, p, func(t, n) { if (t == "page:1" and n < 2) #hold else #reply((200, body(t))) }, false);
  check("held pages still complete", p.status == "ready");
};
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  var tries = 0;
  ignore drive(s, p, func(t, _) { if (t == "page:1" and tries < 2) { tries += 1; #reply((429, "Too Many Requests")) } else #reply((200, body(t))) }, false);
  check("a page refused twice with 429 is retried and completes", p.status == "ready" and tries == 2);
};
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "page:1") #reply((503, "Service Unavailable")) else #reply((200, body(t))) }, false);
  check("a page that keeps failing ends the pull after the retries", p.status == "failed" and Text.contains(p.failure, #text "Odoo answered HTTP 503 (page:1, after 2 retries)"));
};
do {
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  ignore drive(s, p, func(t, _) { if (t == "opening:0") #lost("no agreement among the validators within the deadline") else #reply((200, body(t))) }, false);
  check("a request without agreement ends the pull after the retries", p.status == "failed" and Text.contains(p.failure, #text "no agreement among the validators within the deadline (opening:0, after 2 retries)"));
};
do {
  // an unsubmitted tag is queued and asked for again
  let s = Odoo.init();
  let p = switch (Odoo.begin(s, by, 1, 7, j(BEGIN))) { case (#ok(p)) p; case (#err(m)) Runtime.trap(m) };
  let first = Odoo.advance(s, p, 5);
  check("the initial requests", first.size() == Odoo.INITIAL.size());
  for (t in first.vals()) Odoo.unsubmitted(p, t);
  let again = Odoo.advance(s, p, 6);
  check("unsubmitted tags come back", again.size() == Odoo.INITIAL.size());
  check("overdue: none yet", Odoo.overdue(p, 7).size() == 0);
  Odoo.submitted(p, "gate", 1, 10);
  check("overdue after the deadline", Odoo.overdue(p, 10 + Odoo.DEADLINE + 1) == ["gate"]);
};
''')
    w.append('Debug.print("count: checks = " # Nat.toText(checks));')
    w.append('if (failed > 0) Runtime.trap("odoo connector: " # Nat.toText(failed) # " checks failed");')
    w.append('Debug.print("ODOO GREEN");')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(w) + '\n')
    print(OUT, len(w), 'lines;', len(pages), 'pages;', begin['lines'], 'lines;', len(tb), 'accounts')


if __name__ == '__main__':
    main()
